DOCSP-30546: aggregation fundamentals
mongodb/docs-rust pull request #10
Opened 2023-07-18 18:36 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30546>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30546-aggregation-funs/fundamentals/aggregation/), [index](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30546-aggregation-funs/#fundamentals), & see left hand nav

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-07-19 21:25 UTC, jordan-smith721 requested changes
Great work on this! Just have a few suggestions

2023-07-19 21:25 UTC, jordan-smith721 commented on source/fundamentals/aggregation.txt
> +and assembles the parts into the final product.
Suggestion: The example for this analogy is a little unclear to me. In the beginning of the paragraph it mentions a car factory, but then goes on to say "when building a machine..." It's also somewhat unclear that the "transforms and assembles the parts into the final product" part happens in separate distinct stages. Maybe breaking it down a little more would help. Something like (not a word for word suggestion but just a general idea):

"when building a car, the assembly line begins with a shell. Then, as the car shell moves through the assembly line, each station assembles a separate part, in the end resulting in a transformed final product."

2023-07-19 21:25 UTC, jordan-smith721 commented on source/fundamentals/aggregation.txt
> +``db.site_users`` collection with the following code:
The way this is worded makes me think I should already have this collection, which I don't think is supposed to be the case(?)

```suggestion
To run the examples in this section, load the sample data into a collection called
``db.site_users`` with the following code:
```

2023-07-19 21:25 UTC, jordan-smith721 commented on source/fundamentals/aggregation.txt
> +  maximum user age for users using the ``$avg``, ``$min``, and ``$max``
```suggestion
  maximum user age for users, using the ``$avg``, ``$min``, and ``$max``
```

2023-07-19 21:25 UTC, jordan-smith721 commented on source/includes/fundamentals/code-snippets/aggregation.rs
> +    let pipeline1 = vec![
Suggestion: Rename the pipeline variables so that they are more descriptive and aren't using a number to be distinct. This way examples can be flexible and be shown in any order, and more can be added/removed easily. Applies to all instances

```suggestion
    let age_pipeline = vec![
```

2023-07-19 21:25 UTC, jordan-smith721 commented on source/fundamentals/aggregation.txt
> +  field and counts the number of documents for each month.
```suggestion
  field and count the number of documents for each month.
```

2023-07-19 21:25 UTC, jordan-smith721 commented on source/fundamentals/aggregation.txt
> +  field and counts the number of documents for each genre.
```suggestion
  field and count the number of documents for each genre.
```

2023-07-20 14:32 UTC, rustagir commented on source/fundamentals/aggregation.txt
> +and assembles the parts into the final product.
reworded

2023-07-20 17:00 UTC, jordan-smith721 approved these changes
LGTM!

2023-07-20 21:03 UTC, merged

2023-10-02 15:24 UTC, abr-egn reviewed
LGTM with minor modifications

2023-10-02 15:24 UTC, abr-egn commented on source/includes/fundamentals/code-snippets/aggregation.rs
> +        doc! { "name": "Sonya Mehta", "age": 23, "genre_interests": vec!["fiction", "mystery", "memoir"], "last_active": Utc.with_ymd_and_hms(2019, 5, 13, 0, 0, 0).unwrap() },
We recommend that bson documents use the [`bson::DateTime`](https://docs.rs/bson/latest/bson/struct.DateTime.html) type rather than `chrono::Utc` for better interoperability.  The equivalent construction here would be `DateTime::builder().year(2019).month(5).day(13).build().unwrap()`.