DOCSP-30557: FAQ
mongodb/docs-rust pull request #102
Opened 2023-12-21 20:47 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30557>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-01-02 21:29 UTC, ccho-mongodb requested changes
Plenty of helpful information here! 

I left some comments mainly on making sure the information presented is clearly explained. Let me know if you have any questions.

2024-01-02 21:29 UTC, ccho-mongodb commented on source/faq.txt
> +to BSON, and deserialization, or conversion to the struct type:
Issue:
I think this sentence is difficult to follow because of all the comma-separated phrases and conjunctions.

Suggestion:
I think a list could help describe each of items that the derive statement enables. E.g.

"The following \`\`derive\`\`" statement instructs the driver to perform the following actions when needed:
- Serialize the struct, which converts the struct to BSON
- Deserialize the struct, which converts it from BSON to your struct
"

2024-01-02 21:29 UTC, ccho-mongodb commented on source/faq.txt
> +You can then instantiate a ``Collection`` instance with your custom struct type as its
Suggestion:
I think it could be good to show the code for the format of this. To accomplish this, perhaps the previous code example could have the struct name in the declaration (no need to show all the struct code) and then this code example could show instantiation of the Collection with the struct's type.

2024-01-02 21:29 UTC, ccho-mongodb commented on source/faq.txt
> +an error result. The ``Option`` enum has a ``None`` and a ``Some(T)`` variant, and it
Issue:

From this sentence, I'm unable to determine whether "Ok(T)" can wrap an error result since it mentions "output either ..." without specifying the associations.

Suggestion:

I think splitting the information up can make it easier to understand and reduce the chance of misinterpretation. E.g.

"The Result enum can return an Ok(T) or Err(E) variant. The Ok(T) variant wraps the value of the result of the operation. The Err(E) variant wraps the value of the error returned by the operation."

Suggestion applies to the next sentence describing Option as well.

2024-01-02 21:29 UTC, ccho-mongodb commented on source/faq.txt
> +a ``Result<InsertOneResult>`` type. You can use the ``?`` operator to instruct the driver
Issue:

I think the current order of information makes it difficult to determine how this is connected to the prior explanation until reading the last paragraph of this section.

Suggestion:

I think the relationship between "Result<InsertOneResult>" and Ok(T) and Err(E) should be mentioned in this sentence rather than at the end of the section. I also had difficulty seeing the connection in the reason and consequence signaled by "For this reason..." until after I read that section.

I think the explanation about the question mark operator could start in a separate paragraph since it explains one method of how to perform the unwrapping which is one of the answers to the FAQ entry.

"For example, the insert_one() method returns a Result<InsertOneResult> type to wrap either a successful response or an error.

To access the result, you can use the \`\`?`\`\` operator to unwrap \`\`InsertOneResult\`\`\. If the operation is successful, the \`\`?\`\` operator unwraps the ... If an error occurrs, ...
"

2024-01-02 21:29 UTC, ccho-mongodb commented on source/faq.txt
> +variant.
Suggestion:

I think showing an example could be helpful, especially since it directly answers the FAQ entry. Perhaps it could use "is_ok" or "is_err"?

2024-01-02 21:29 UTC, ccho-mongodb commented on source/faq.txt
> +For more information about the ``Result`` and ``Option`` enums, see the following
Suggestion:

I think there could be value in showing an example of Option since there's one for Result. Otherwise, it could be helpful to provide some guidance on how Option differs or is similar to Result.

2024-01-03 15:21 UTC, norareidy commented on source/faq.txt
> +- Maximum idle time, set by the ``max_idle_time`` option
Made a [ticket](https://jira.mongodb.org/browse/DOCSP-35254) for this! Do you think I should keep the information about connection pooling on this page too?

2024-01-03 18:43 UTC, norareidy commented on source/faq.txt
> +The ``Cursor<T>`` type implements the ``Stream`` trait and has access to the
I adjusted this section and included an example of when this error might occur & its resolution

2024-01-03 18:46 UTC, norareidy commented on source/faq.txt
> +conversions between custom Rust types, like structs and enums, and BSON. You can
Agreed that the commas make this confusing; I just left it at "conversions between custom Rust types and BSON"

2024-01-03 18:51 UTC, norareidy commented on source/faq.txt
> +After installing the ``serde`` crate, you can model the documents in a collection
I've seen the "install" syntax use but yeah saying "add" is better, since there's no other installation process other than adding the crate to your dependencies. Fixed

2024-01-05 04:57 UTC, ccho-mongodb approved these changes
Added a few more suggestions and issues, but otherwise LGTM. If you would like me to take another look after making updates, let me know!

2024-01-05 04:57 UTC, ccho-mongodb commented on source/faq.txt
> +crates registry.
Suggestion:

I think it would be helpful to stay consistent with the terminology (whether "add the crate" or "install"). Based on 
[the prior comment](https://github.com/mongodb/docs-rust/pull/102#discussion_r1439841831) and the first sentence of the next paragraph, perhaps this should be "add the crate".

2024-01-05 04:57 UTC, ccho-mongodb commented on source/faq.txt
> +statement before the ``Vegetable`` struct definition, which instructs the driver to
Suggestion:
From [the Derive page in Rust by Example](https://doc.rust-lang.org/rust-by-example/trait/derive.html), it seems like "derive" should be an "attribute" rather than "statement".

2024-01-05 04:57 UTC, ccho-mongodb commented on source/faq.txt
> +- ``Err(E)``, which wraps an error value if the operation is unsuccessful
Issue:

The style guide on [List Items](https://www.mongodb.com/docs/meta/style-guide/style/lists/#list-items) provides specific guidance on list items that separate the initial term and information about it:

> If you need to separate the initial term or phrase from the information that follows it, use a colon. However, if you don't need a separator, don't use one. (For an example of a list in which separators aren't necessary, see the list at the top of this topic.


Suggestion:

```suggestion
- ``Ok(T)``: wraps the value of the result of the operation if the operation is successful
- ``Err(E)`: wraps an error value if the operation is unsuccessful
```

Applies to all similar instances.

2024-01-05 04:57 UTC, ccho-mongodb commented on source/faq.txt
> +return value. If the operation is successful, the ``?`` operator unwraps the ``InsertOneResult``
Suggestion:

I think the first part of the sentence should directly introduce the rest of the sentence

In the current sentence, the first part mentions accessing the result and the rest of it explains only how to unwrap the return value.

```suggestion
To access the unwrapped result of ``insert_one()``, use the ``?`` operator. If the operation is successful, the ``?`` operator unwraps the ``InsertOneResult``
```

2024-01-05 04:57 UTC, ccho-mongodb commented on source/faq.txt
> +For example, the ``insert_one()`` method returns a ``Result`` type to wrap either a successful
Issue:

I think this information conflicts with the next paragraph (mentions InsertOneResult rather than Result).

Suggestion:

I think it would be helpful to call out the equivalence of InsertOneResult and Result. Perhaps something like (probably not the correct Rust terminology) "The insert_one() method returns an InsertOneResult type which extends the Result type"

2024-01-05 04:57 UTC, ccho-mongodb commented on source/faq.txt
> +variant. The following code uses the ``match`` keyword to process the ``insert_one()``
Suggestion:

No change necessary, but I think this might be a more succinct way to present this sentence since Result (InsertOneResult, once that equivalence is added) was explained earlier:

```suggestion
Alternatively, you can create a conditional to handle the unwrapped values of ``InsertOneResult``. The following code uses the ``match`` keyword to process the ``insert_one()``
```

2024-01-05 04:57 UTC, ccho-mongodb commented on source/faq.txt
> +- `If Let <https://doc.rust-lang.org/book/ch06-03-if-let.html>`__
Suggestion:

I think this could be confusing since the keywords "if" and "let" are lowercase in their usage and the content of the link describes behavior of using two keywords in a pattern rather than adjacent to each other: 

```suggestion
- Control Flow with `if let <https://doc.rust-lang.org/book/ch06-03-if-let.html>`__
```

2024-01-05 04:57 UTC, ccho-mongodb commented on source/faq.txt
> +- ``Some(T)``, which wraps a nonempty return value
Suggestion:

I think "nonempty" is usually spelled with a hyphen ("non-empty").

2024-01-05 04:57 UTC, ccho-mongodb commented on source/faq.txt
> +generic type parameter. The following example instantiates the ``my_coll`` collection
Suggestion:

I think lowercase collection might imply a collection name rather than the Collection struct.

```suggestion
generic type parameter. The following example instantiates the ``my_coll`` Collection
```

Alternatively, perhaps "variable" would be more conventional since this describes assignment rather than direct instantiation.

2024-01-05 04:57 UTC, ccho-mongodb commented on source/faq.txt
> +- ``Some(T)``, which wraps a nonempty return value
Suggestion:

I think the placement of the Result example directly after this makes it awkward. Instead, perhaps placing this before the line that starts with "Some {+driver-short+} methods return an ``Option`` type, such as the ``read_concern()``..." would make the information more organized and easier to locate.

2024-01-05 19:29 UTC, norareidy commented on source/faq.txt
> +statement before the ``Vegetable`` struct definition, which instructs the driver to
good point - will fix in other Rust docs too

2024-01-09 17:42 UTC, isabelatkinson approved these changes

2024-01-09 18:54 UTC, merged