DOCSP-30540: insert fundamental guide
mongodb/docs-rust pull request #11
Opened 2023-07-19 21:27 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30540>
[**Staging**](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30540-insert-funs/fundamentals/crud/write-operations/insert/), [WO landing](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30540-insert-funs/fundamentals/crud/write-operations/#std-label-rust-crud-write-operations), left nav

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-07-21 14:34 UTC, mongoKart requested changes

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +   the operation to fail with a ``BulkWriteFailure``.
S: Specify which operation(s) fail. 

Also torn on whether we need the name of the exception here. If you think it's important, maybe change "fail with" to "throw a BulkWriteFailure exception" or something similar.

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +.. TODO decide if using structs in CRUD fundamentals
Q: Will this be decided later?

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +following table describes the available options to set in
S:

```suggestion
following table describes the options available in
```

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +     - | If ``true``, allows the write to opt-out of document-level
I: verb + preposition doesn't need a hyphen, afaik

S:
```suggestion
     - | If ``true``, allows the write to opt out of document-level
```

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +     - | If ``true``, allows the write to opt-out of document-level
I: Would be clearer and [more stylish](https://www.mongodb.com/docs/meta/style-guide/writing/use-effective-verbs/#don-t-humanize-inanimate-objects) to avoid having the connector opt out.

S: What controls the validation decision here?

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +         logs. This option is only available on {+server+} versions 4.4
```suggestion
         logs. This option is available only on {+server+} versions 4.4
```

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +         the operation through the database profiler, ``currentOp``, and
I: What does "tagged to the operation" mean? Also repeats "operation"

S: Could the comment be "attached" or "tied" to the operation or something similar? Could also replace "trace the operation" to something like "trace its execution"

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +.. TODO decide if using structs in CRUD fundamentals
Same question as above

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +constructing and passing an optional ``InsertManyOptions`` struct. The
S: Can we omit "optional" here? The language already makes it sound optional

```suggestion
constructing and passing an ``InsertManyOptions`` struct. The
```

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +following table describes the available options to set in
```suggestion
following table describes the options available in
```

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +     - | If ``true``, allows the write to opt-out of document-level
Same comment as above

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +     - | If ``true``, the operation retuns when an insert fails without performing the
```suggestion
     - | If ``true``, the operation returns when an insert fails without performing the
```

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +         remaining writes. If ``false``, even if an insert fails, the
I: ambiguous meaning here. guessing it should be something like this:

```suggestion
     - | If ``true``, when an insert fails, the operation returns without inserting
        the remaining documents. If ``false``, even if an insert fails, the
```

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +         logs. This option is only available on {+server+} versions 4.4
Same comments as above

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +Assume you want to insert the following documents:
S:

```suggestion
Assume you want to insert the following documents into the ``books`` collection:
```

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +Ordered Behavior
I like this example. Does it make sense to mention/link to it above, and/or change the name to "Ordered Behavior Example"?

2023-07-21 14:34 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +.. - :ref:`rust-query-guide`
Q: confirming these will be added later

2023-07-21 15:17 UTC, rustagir commented on source/fundamentals/crud/write-operations/insert.txt
> +.. TODO decide if using structs in CRUD fundamentals
yes

2023-07-21 15:19 UTC, rustagir commented on source/fundamentals/crud/write-operations/insert.txt
> +     - | If ``true``, allows the write to opt-out of document-level
you can set document validation on a collection, so you could say the collection has the validation rules

2023-07-21 15:21 UTC, rustagir commented on source/fundamentals/crud/write-operations/insert.txt
> +     - | If ``true``, allows the write to opt-out of document-level
edited the wording, lmk what you think

2023-07-21 15:22 UTC, rustagir commented on source/fundamentals/crud/write-operations/insert.txt
> +         the operation through the database profiler, ``currentOp``, and
what about just trace it?

2023-07-21 15:23 UTC, rustagir commented on source/fundamentals/crud/write-operations/insert.txt
> +constructing and passing an optional ``InsertManyOptions`` struct. The
changed in both instances

2023-07-21 15:26 UTC, rustagir commented on source/fundamentals/crud/write-operations/insert.txt
> +.. - :ref:`rust-query-guide`
We will make a TODO resolution ticket at some point

2023-07-21 15:31 UTC, rustagir commented on source/fundamentals/crud/write-operations/insert.txt
> +completes successfully.
reworded some things, but mostly adhered to this structure

2023-07-21 16:08 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +         :manual:`Schema Validation </core/schema-validation>` in the Server manual.
Really clear. nicely done

2023-07-21 16:10 UTC, mongoKart commented on source/fundamentals/crud/write-operations/insert.txt
> +  duplicate ``_id`` value, but it inserts every other document.
Looks good!

2023-07-21 16:10 UTC, mongoKart approved these changes
Awesome work with those changes. Page looks good.

2023-07-21 16:36 UTC, merged

2023-09-29 17:14 UTC, abr-egn commented on source/includes/fundamentals/code-snippets/crud/insert.rs
> +    let doc: Document = doc! { "title": "Atonement", "author": "Ian McEwan" };
Type annotations are needed for `Collection` because otherwise the contained type would be ambiguous, but aren't needed or idiomatic for the rest of the `let` declarations.

2023-09-29 17:14 UTC, abr-egn reviewed
LGTM with one suggested change!