DOCSP-39895: Bulk write guide
mongodb/docs-rust pull request #117
Opened 2024-05-28 21:29 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-39895
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-06-03 20:15 UTC, rustagir requested changes
Good work so far! Lmk if you have any questions about my feedback.

2024-06-03 20:15 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +namespaces. Instead of making a call to the database for each operation,
You can also indicate that the `bulk_write()` method is in the `Client` class, which enables this feature against any namespace in the cluster

2024-06-03 20:15 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +  on this page.
S: fix indentation

2024-06-03 20:15 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +  on this page.
```suggestion
  method call. To view an example that passes a ``DeleteOneModel`` and an ``InsertOneModel`` to
  the same ``bulk_write()`` call, see the :ref:`Modify Behavior example <bulk-opts-example>`
  on this page.
```

2024-06-03 20:15 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +       | manual.
S: link to rust indexes guide instead?

2024-06-03 20:15 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +       | matching documents will be updated.
I: remove the newline breaks `|` from the beginning of each line in the paragraph

2024-06-03 20:15 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +       | matching documents will be updated.
Applies everywhere you might have done this

2024-06-03 20:15 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +     - | (Optional) A set of filters specifying which array elements an update applies to.
```suggestion
     - | (Optional) A set of filters specifying which array elements an update applies to if you are updating an array-valued field.
```

2024-06-03 20:15 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +-------------------------
S: link to this section earlier in the page. Maybe you can create a TOC like on some of the other CRUD rust pages

2024-06-03 20:15 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +
Q: could you refactor this example to be more intuitive? Perhaps you could rename the `db` database to be `ingredients` and the second namespace could be `recipes.dinner` or something

2024-06-03 20:15 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +
Just to have some association for why a user might be doing both in the same operation

2024-06-03 20:15 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/bulk.rs
> +    let mushrooms: Collection<Mushroom> = client.database("db").collection("mushrooms");
S: reduce horizontal scroll (applies to all)
```suggestion
    let mushrooms: Collection<Mushroom> = client
        .database("db")
        .collection("mushrooms");
```

2024-06-04 20:42 UTC, norareidy commented on source/fundamentals/crud/write-operations/bulk.txt
> +
Makes sense, updated!

2024-06-05 14:32 UTC, rustagir requested changes
A few more things but good work!

2024-06-05 14:32 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +In this guide, you can learn how to perform **bulk operations**.
```suggestion
In this guide, you can learn how to use the {+driver-short+} to perform **bulk operations**.
```

2024-06-05 14:32 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +in your cluster.
S; use wording from the [Server glossary](https://www.mongodb.com/docs/manual/reference/glossary/#:~:text=the%20preferred%20shell.-,namespace,-A%20namespace%20is)

```suggestion
Bulk operations perform multiple write operations against one or more
**namespaces**. A namespace is a combination of the database name and the collection name, in the format
``<database>.<collection>``. Since you perform bulk operations on a
the ``Client`` instance, you can perform bulk operations against any namespace
in the cluster accessed by your client.
```

2024-06-05 14:32 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +perform multiple operations within one call to the database.
S: right now, this sentence seems a little isolated, maybe you can make this a description of why one might use bulk ops.
```suggestion
You might perform a bulk operation to reduce the number of calls to the server. Instead of sending
a request for each operation, bulk operations perform multiple operations within one action.
```

2024-06-05 14:32 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +
S: add a short descriptive sentence to the section headers, as done here: https://github.com/mongodb/docs-rust/blob/330f2d7c8b4ac245672a1c5c80cc0f86db610307/source/fundamentals/crud/read-operations/retrieve.txt#L32-L45

2024-06-05 14:32 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +   on this page.
```suggestion
   in this guide.
```

2024-06-05 14:32 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +you want to insert.
```suggestion
To perform a bulk insert operation, create an ``InsertOneModel`` instance for each document
you want to insert, then pass a list of models to the ``bulk_write()`` method.
```

2024-06-05 14:32 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +you want to insert.
add this clause to all sections

2024-06-05 14:32 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +This example performs the following actions:
```suggestion

This example performs the following actions:
```

2024-06-05 14:32 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +-------------------------
Oh I must have missed it, but the TOC you added addresses this comment!

2024-06-05 14:32 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +insert the specified document.
S: I dont think this is true, I think that the unsuccessful delete does not return an error that will abort the operation. Instead, you could provide an example that raises a duplicate key error or something, as this would abort the operation

2024-06-05 14:32 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/bulk.rs
> +use mongodb::{
S: reduce horiz scroll in examples

2024-06-05 18:01 UTC, norareidy commented on source/fundamentals/crud/write-operations/bulk.txt
> +insert the specified document.
You're right, thanks for catching this - fixed

2024-06-06 20:50 UTC, rustagir approved these changes
lgtm with a few last comments! great work documenting this APi!

2024-06-06 20:50 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +To construct an ``InsertOneModel``, specify the following struct fields:
S: introduce this table (and in other sections) by clarifying that you set these fields by using the corresponding builder methods.

2024-06-06 20:50 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +to the ``bulk_write()`` method:
```suggestion
The following example attempts to perform update and insert operations on the ``mushrooms`` collection
and sets the ``ordered`` field to ``false`` by chaining the ``ordered()`` method
to the ``bulk_write()`` method: 
```

2024-06-06 20:50 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +attempt any subsequent operations after the unsuccessful update and will not insert the specified document.
```suggestion
The ``_id`` field is immutable and cannot be changed in an update operation. Since the ``UpdateOneModel``
includes instructions to update this field, the bulk operation returns a ``BulkWriteError`` and performs
only the insert operation. If you set the ``ordered`` field to ``true``, the driver does not
attempt any subsequent operations after the unsuccessful update operation, and the driver does not insert any documents.
```

2024-06-07 21:40 UTC, isabelatkinson reviewed
Looks great, just a few suggestions. Also recommend considering adding a section about generating verbose results using [this action method](https://docs.rs/mongodb/3.0.0-beta/mongodb/action/struct.BulkWrite.html#method.verbose_results).

2024-06-07 21:40 UTC, isabelatkinson commented on source/fundamentals/crud/write-operations/bulk.txt
> +       | When set to ``false``, the driver continues to attempt write operations if one fails.
Very minor, but the actual continue-on-error behavior is done by the server, not the driver. I'd remove mention of the driver here.

2024-06-07 21:40 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/crud/bulk.rs
> +    // begin-mixed-namespaces
Up to you whether this would be worth the additional text, but this could be a good spot to make the collections generic over a non-`Document` type and demonstrate how to use [this helper method](https://docs.rs/mongodb/3.0.0-beta/mongodb/struct.Collection.html#method.insert_one_model).

e.g.
```
#[derive(Serialize)]
struct Sweet {
    name: String,
    price: f32,
}

let sweets: Collection<Sweet> = client.database("ingredients").collection("sweets");
let sweet = Sweet {
    name: "brown sugar".to_string(),
    price: 3.99,
};
let insert_sweet_model = sweets.insert_one_model(sweet)?;

// ditto for dessert
```

2024-06-10 17:14 UTC, norareidy commented on source/includes/fundamentals/code-snippets/crud/bulk.rs
> +    // begin-mixed-namespaces
I added a section to Insert Operations instead that uses a `Mushroom` struct and `insert_one_model()`!

2024-06-10 19:11 UTC, norareidy commented on source/includes/fundamentals/code-snippets/crud/bulk.rs
> +    // begin-mixed-namespaces
Also added a section on bulk write return values, which includes a `verbose_results()` explanation

2024-06-10 20:06 UTC, rustagir reviewed
A few things, re-request if needed!

2024-06-10 20:06 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +see the :ref:`bulk-insert-structs-example` on this page.
```suggestion
You can also use custom struct types to represent your sample data. For
an example that performs a bulk operation by using ``Mushroom`` structs to model the same data,
see the :ref:`bulk-insert-structs-example` on this page.
```

2024-06-10 20:06 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +You can also model your documents as structs and insert them into the ``db.mushrooms`` namespace.
```suggestion
You can also model your documents by using structs and bulk insert struct instances
into the ``db.mushrooms`` namespace.
```

2024-06-10 20:06 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +from each ``Mushroom`` instance:
```suggestion
The following code uses the ``insert_one_model()`` method to construct an ``InsertOneModel``
from each ``Mushroom`` instance, then inserts both models in a bulk operation:
```

2024-06-10 20:06 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +----------------------
```suggestion
Return Type
------------
```

2024-06-10 20:06 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +You can also use the ``verbose_results()`` method to see more detailed information about each
```suggestion
You can also use the ``verbose_results()`` method to see detailed information about each
```

2024-06-10 20:06 UTC, rustagir commented on source/fundamentals/crud/write-operations/bulk.txt
> +      upserted_count: 0, deleted_count: 1 }
Q: if this example uses the `verbose_results()` method, why is it printing a `SummaryBulkWriteResult` instead of a `VerboseBulkWriteResult` result?

2024-06-10 20:06 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/bulk.rs
> +    let result = client.bulk_write(models).ordered(false).verbose_results().await?;
Q: why use `verbose_results()` here when the operation results in an error?

2024-06-10 20:30 UTC, norareidy commented on source/includes/fundamentals/code-snippets/crud/bulk.rs
> +    let result = client.bulk_write(models).ordered(false).verbose_results().await?;
oops, didn't mean to add this here - removed

2024-06-10 20:34 UTC, norareidy commented on source/fundamentals/crud/write-operations/bulk.txt
> +      upserted_count: 0, deleted_count: 1 }
`verbose_results()` returns a `VerboseBulkWriteResult`, but the `summary` field of the `VerboseBulkWriteResult` (which is what I'm printing) has a value of `SummaryBulkWriteResult`. Here's [the struct and its fields](https://github.com/mongodb/mongo-rust-driver/blob/895f0c157a1ed9a8e168857c4db92c9b0d87a8bc/src/results/bulk_write.rs#L37) in the source code.

2024-06-10 20:39 UTC, norareidy commented on source/fundamentals/crud/write-operations/bulk.txt
> +      upserted_count: 0, deleted_count: 1 }
Since this ends up giving you the same information as omitting the verbose_results() call, I changed it to print the `update_results` and `delete_results` instead

2024-06-10 22:53 UTC, isabelatkinson approved these changes
looks great!

2024-06-11 13:50 UTC, merged