DOCSP-30536: retrieve data funs
mongodb/docs-rust pull request #12
Opened 2023-07-20 19:54 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30536>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30536-retrieve/fundamentals/crud/read-operations/retrieve/)

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-07-21 22:22 UTC, ccho-mongodb requested changes
Good start!

I would recommend thinking of how a reader new to MongoDB might read through and use this page to learn about retrieving data given that it's describing foundational concepts rather than providing specific details.

As an aforementioned reader, I would want definitions for all the terms, straightforward examples that demonstrate that I learned from the page, and to be directed to pages that I can learn more about my particular use case.

If you want help visualizing this process, let me know!

2023-07-21 22:22 UTC, ccho-mongodb commented on source/includes/fundamentals/code-snippets/crud/retrieve.rs
> +        doc! { "$sort": { "_id.year" : 1 } }
Question:
Are the linebreaks and lack of them idiomatic formatting in Rust? If there aren't any rules, I wonder if it could be more readable by using multiple lines and indentation to make it more clear what these contain. 

Suggestion:
I think it would be more readable if it used a format or aggregation example that doesn't require horizontal scrolling in the docs view.

2023-07-21 22:22 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +      * { "_id": ObjectId("..."), "item": "placemat", "quantity": 80, "last_ordered": DateTime("2018-07-15 ...") }
Question:
I think the output can be difficult to read since it requires horizontal scrolling. Is there some command to convert the result to JSON and format it with indentations and linebreaks?

2023-07-21 22:22 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +.. _rust-crud-retrieve-api:
Issue:
[Make link text clear
](https://www.mongodb.com/docs/meta/style-guide/style/links-and-cross-references/#make-link-text-clear
)

> Strive to be clear about where exactly a link will take a reader. 

I think assigning links entitled "API documentation" are confusing because I would have expected to see the actual API documentation for the specified function, not a list of links that go to API documentation.
I think it is easy to forget what link you clicked if you cross-link to a section from which you need to find another link to click.

Suggestion:
I think it would be good to keep this section for anyone that might reach the end of the doc, but do not cross-link to it. Instead, when describing the link, go directly to the API docs. E.g. 
"For a full list of settings you can specify for each type, see the API documentation for`FindOptions <{+api+}/options/struct.FindOptions.html>`__ and `FindOneOptions <{+api+}/options/struct.FindOneOptions.html>`__
"

Otherwise, omit mention of the API docs if it's not necessary.

2023-07-25 14:29 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +Sample Data
Including "Read Operation" in the header seems redundant, since the page doesn't have other examples

2023-07-25 14:37 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/retrieve.rs
> +    my_coll.insert_many(docs, None).await?;
Ok, I will add this to a cleanup ticket, too

2023-07-25 14:39 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/retrieve.rs
> +    my_coll.insert_many(docs, None).await?;
https://jira.mongodb.org/browse/DOCSP-30463

2023-07-25 14:49 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +The ``find()`` method takes a query filter as a parameter. The method
added todo for specify a query

2023-07-25 14:56 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +.. include:: /includes/fundamentals/automatic-creation.rst
omitted since no longer using an insert snippet

2023-07-25 16:30 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +Sample Data
This suggestion is related to "Provide more details in the header". Prior to this section, the reader has no idea what the format of the page, including whether there are any examples as well as sample data. The suggested wording would provide a hint as to what the sample data is for (upcoming examples).

The other option I listed is to introduce the upcoming sections in the overview in which case you wouldn't need to provide more details which is probably preferable.

2023-07-25 17:31 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +- Sorts matched documents in descending order by ``quantity``
changed in both

2023-07-25 17:48 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +Examples
added cross links

2023-07-25 17:49 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +- `Option <https://doc.rust-lang.org/nightly/core/option/enum.Option.html>`__
Option includes `Some` and `None,` which are the return types for `find_one()`

2023-07-25 17:49 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +- `Option <https://doc.rust-lang.org/nightly/core/option/enum.Option.html>`__
I can link the specific variants instead

2023-07-25 17:50 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +- `Option <https://doc.rust-lang.org/nightly/core/option/enum.Option.html>`__
In the documentation, I can't see an option to change versions

2023-07-25 17:54 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +- Matches documents where the value of ``last_ordered`` is before 2018
changed data - no longer relevant

2023-07-25 17:55 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +       | Default: ``nil``
It is the order that documents are matched

2023-07-25 17:55 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/retrieve.rs
> +        doc! { "$sort": { "_id.year" : 1 } }
I will add this to the guidelines doc as a question

2023-07-25 18:12 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +      * { "_id": ObjectId("..."), "item": "placemat", "quantity": 80, "last_ordered": DateTime("2018-07-15 ...") }
Adding a formatter

2023-07-25 20:42 UTC, ccho-mongodb approved these changes
Looks mostly good! A few minor issues and suggestions. I can take another look if you want.

2023-07-25 20:42 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +type that contains these documents. If it does not match any documents,
Suggestion:
I think "Cursor type that contains these documents" might not be completely accurate since "contains" implies that they're stored inside. A cursor is a data structure that resembles a pointer -- it can retrieve a result set, but does not contain them.

"returns a Cursor type that you can access to retrieve the results."

2023-07-25 20:42 UTC, ccho-mongodb commented on source/includes/fundamentals/code-snippets/crud/retrieve.rs
> +    let mut results = my_coll.find(
Suggestion:
No change necessary, but I wonder whether "cursor" would be a suitable variable name to reinforce the description of the function returning a cursor.

2023-07-25 20:42 UTC, ccho-mongodb commented on source/includes/fundamentals/code-snippets/crud/retrieve.rs
> +    my_coll.insert_many(docs, None).await?;
Question: 
Just to confirm, this is something that you've already addressed? The sample data I see on the page no longer contains an insert statement. And I'm guessing you meant this ticket?
https://jira.mongodb.org/browse/DOCSP-31602

2023-07-25 20:42 UTC, ccho-mongodb commented on source/includes/fundamentals/code-snippets/crud/retrieve.rs
> +        println!("{}", serde_json::to_string_pretty(&doc).unwrap());
Suggestion:
If it's not too confusing or too much additional work, I wonder if this could output an array of documents of rather than two separate documents (without separating comma).

2023-07-25 20:42 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +documentation <rust-crud-retrieve-api>` for ``AggregateOptions``.
Suggestion:

Re: https://github.com/mongodb/docs-rust/pull/12/files#r1271146081

> I think it would be good to keep this section for anyone that might reach the end of the doc, but do not cross-link to it. Instead, when describing the link, go directly to the API docs.

To clarify I think it would be better to link directly to "<{+api+}/options/struct.AggregateOptions.html>`__" rather than clicking one link to go to the bottom (rust-crud-retrieve-api) of the page and then trying to figure out what they were looking for in the list of API documentation links.

2023-07-25 20:42 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +- `None <https://doc.rust-lang.org/nightly/core/option/enum.Option.html#variant.None>`__
Suggestion:

I think this section should refer to the API documentation for the driver rather than core Rust documentation. Since I think "Some" and "None" are fairly common in Rust, I don't think there's much value in including links to them in our docs unless there's a specific need, such as explaining a bug/limitation.

2023-07-25 20:42 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +it returns an empty ``Cursor`` type.
Suggestion:
I think it could be helpful to explain what it means to be "empty". If there's a method they can call to check that it is an empty Cursor type, I think that is worth mentioning. Otherwise, what differentiates it from a Cursor that is pointing to a non-empty result set?

2023-07-25 20:42 UTC, ccho-mongodb commented on source/includes/fundamentals/automatic-creation.rst
> +.. tip:: Non-existent Databases and Collections
Suggestion:
I think this file should be removed since I don't see it referenced anywhere.

2023-07-25 20:42 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +- `Option <https://doc.rust-lang.org/nightly/core/option/enum.Option.html>`__
Could be a good question for the Rust DBX team on what's the best place to link to, but I found https://doc.rust-lang.org/stable/core/option/enum.Option.html

2023-07-26 15:22 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/retrieve.rs
> +    my_coll.insert_many(docs, None).await?;
Oops, yes

2023-07-26 17:46 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +To use default values for each setting, specify ``None`` for the options
changed in both places

2023-07-26 17:50 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +         in the Server manual.
added a few links and TODOs for unwritten content

2023-07-26 18:04 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +- `None <https://doc.rust-lang.org/nightly/core/option/enum.Option.html#variant.None>`__
removing these entries

2023-07-26 18:08 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +it returns an empty ``Cursor`` type.
reworded to not discuss two cases, because a `Cursor` is returned either way

2023-07-26 18:10 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/retrieve.rs
> +        println!("{}", serde_json::to_string_pretty(&doc).unwrap());
What would be the benefit of printing the cursor that way? I figure we can cover different ways to retrieve data from a cursor on that page. LMK your thoughts.

2023-07-26 18:12 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +Sample Data
adding detail to overview

2023-07-26 18:37 UTC, ccho-mongodb commented on source/includes/fundamentals/code-snippets/crud/retrieve.rs
> +        println!("{}", serde_json::to_string_pretty(&doc).unwrap());
It's easier (at least for me) to see there are two documents when wrapped in an array and separated by a comma which would resemble an array in extended JSON. If that doesn't seem helpful, maybe it would be ok to revert to the raw string output.

2023-07-26 19:36 UTC, ccho-mongodb approved these changes
LGTM, just added a couple suggestions and a capitalization issue.

2023-07-26 19:36 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +documents to match.
Good description!

Suggestion:
No changes needed, but I wonder if it would be effective to do one of the following to help a reader confirm their understanding of a query filter:
- link to more info on query filters (perhaps https://www.mongodb.com/docs/manual/core/document/#query-filter-documents)
- provide an example of a query filter

2023-07-26 19:36 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +  and methods mentioned in this guide
Issue:

The sentence following a colon should not be capitalized unless the colon is followed by two or more sentences according to the Chicago Manual of Style. I think I provided this reference in another PR since there's a paywall:
https://www.grammarly.com/blog/capitalization-after-colons/

Suggestion:
I think it would be best to follow the CMoS recommendation of using lowercase after the colons in these instances.

2023-07-26 19:36 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/retrieve.txt
> +  and describes the sample data that is used by the examples
Suggestion:

I think "provides and describes" could be described more tersely as "presents". I think it might also be slightly better to specify what kind of examples this refers to.

```suggestion
- :ref:`Sample Data for Examples <rust-retrieve-sample-data>`: presents
  the sample data that is used by the read operation examples
```

2023-07-27 13:40 UTC, rustagir commented on source/fundamentals/crud/read-operations/retrieve.txt
> +documents to match.
There will be a link to the Specify a Query page when that's made

2023-07-27 13:44 UTC, merged

2023-09-25 15:30 UTC, abr-egn commented on source/fundamentals/crud/read-operations/retrieve.txt
> +consist of the ``find()`` and ``find_one()`` methods.
Should the `_with_session` variants be covered here?

2023-09-26 17:36 UTC, norareidy commented on source/fundamentals/crud/read-operations/retrieve.txt
> +consist of the ``find()`` and ``find_one()`` methods.
I've added a paragraph on the `_with_session` methods!