DOCSP-42093: 8.0 compatibility
mongodb/docs-rust pull request #126
Opened 2024-08-02 17:43 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-42093
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-42093-8.0-compat/compatibility/

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-08-02 18:50 UTC, shuangela requested changes
lgtm with one confusion

2024-08-02 18:50 UTC, shuangela commented on source/includes/mongodb-compatibility-table-rust.rst
>     * - 3.0 [#2.5-onwards-limitation]_
Q: Based on the slack convo, I'm a little confused why only 2.6 fully supports version 7.0 while newer versions don't? I assumed the engineer meant 2.6 and beyond, but could you clarify that? Everything else looks good

2024-08-05 20:21 UTC, norareidy commented on source/includes/mongodb-compatibility-table-rust.rst
>     * - 3.0 [#2.5-onwards-limitation]_
you're right - this should be the versions since 2.6! I'll get a tech review just to confirm

2024-08-06 14:12 UTC, shuangela approved these changes
LGTM!

2024-08-06 16:42 UTC, kevinAlbs approved these changes

2024-08-06 16:42 UTC, kevinAlbs commented on source/includes/mongodb-compatibility-table-rust.rst
>     * - 3.0 [#2.5-onwards-limitation]_
Yes. I expect Rust driver versions >=2.6 support server 7.0.

2024-08-06 17:07 UTC, merged