Docsp 30505 quick start pages
mongodb/docs-rust pull request #13
Opened 2023-07-20 19:55 UTC by nickldp

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30505>
## Staging
[Quick Start landing page ](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30505-QuickStart-pages/quick-start/#std-label-rust-quickstart)
[Download and Install](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30505-QuickStart-pages/quick-start/download-and-install/)
[Create a Deployment](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30505-QuickStart-pages/quick-start/download-and-install/)
[Create a Connection String](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30505-QuickStart-pages/quick-start/create-a-connection-string/)
[Connect to MongoDB](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30505-QuickStart-pages/quick-start/connect-to-mongodb/)
[Next Steps](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30505-QuickStart-pages/quick-start/next-steps/)

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [x] Are all the links working?

2023-07-21 15:02 UTC, rustagir requested changes
great work! left a few comments to clean up and fix code

2023-07-21 15:02 UTC, rustagir commented on source/code-snippets/quick-start/connect-async.rs
> +   println!("{:?}", my_movie);
S: Use this code so output is formatted as JSON 
```rust
let my_movie = coll.find_one(<your filter>, None).await?;
println!("{}", my_movie.unwrap());
```

2023-07-25 17:33 UTC, nickldp commented on source/code-snippets/quick-start/connect-async.rs
> +   let coll = client.database("sample_mflix").collection::<mongodb::options::UpdateModifications>("movies");
<Document> wasn't working but this is what the compiler suggested, using Collection<Document> now.

2023-07-28 17:36 UTC, rustagir requested changes

2023-07-28 17:36 UTC, rustagir commented on source/code-snippets/quick-start/connect-async.rs
> +   let my_movie = my_coll.find_one(doc! { "title" : "The Perils of Pauline" }, None).await?;
```suggestion
   let my_movie = my_coll.find_one(doc! { "title": "The Perils of Pauline" }, None).await?;
```

2023-07-28 17:36 UTC, rustagir commented on source/quick-start/download-and-install.txt
> +         bson = "2.6.1"
S: make this section more clear by just showing the entire dependencies block. Also, add a source constant for the bson version.

```suggestion
      Add the following crates to your project by including them in the 
      dependencies list located in your project's ``Cargo.toml`` file:
      
      - ``mongodb``, the {+driver-short+} crate
      - ``bson``, the MongoDB data representation crate
      
      The following code shows an example dependencies list that includes the preceding crates:
      
      .. code-block:: bash
         
         [dependencies]
         mongodb = "{+version+}"
         bson = "{+bson-version+}"
```

2023-07-28 17:36 UTC, rustagir commented on source/quick-start/download-and-install.txt
> +      - Records the dependency information in the ``Cargo.toml`` file
S: Create tabs that show how to install both the async and sync crates, since the example code in the later steps also shows both. Here are resources that show how to install either:
- [async](https://mongodb.github.io/mongo-rust-driver/manual/installation_features.html#configuring-the-async-runtime)
- [sync](https://mongodb.github.io/mongo-rust-driver/manual/installation_features.html#enabling-the-sync-api)

2023-07-28 17:36 UTC, rustagir commented on source/code-snippets/quick-start/connect-async.rs
> +   println!("{:?}", my_movie);
S: In one of my PRs, I experimented with printing results as formatted JSON. Let's implement this in the sync and async code, as well as update the output block. Here is the code:

```rust
// Find the movie "The Perils of Pauline" in the "movies" collection
let my_movie = my_coll.find_one(doc! { "title": "The Perils of Pauline" }, None).await?;

// Print the document
println!("{}", serde_json::to_string_pretty(&my_movie).unwrap());
```
Test the code and copy the output

2023-07-28 17:36 UTC, rustagir commented on source/quick-start/download-and-install.txt
> +      - Records the dependency information in the ``Cargo.toml`` file
S: remove this, also, per the style guide, only use lists if there are 2 or more items

2023-07-28 17:38 UTC, rustagir commented on source/code-snippets/quick-start/connect-async.rs
> +   println!("{:?}", my_movie);
You'll have to include the `serde_json` package as a dependency, so add this to the list of dependencies in the install step and explain what it does: https://docs.rs/serde_json/latest/serde_json/

2023-08-01 14:59 UTC, rustagir approved these changes
approving, but please resolve the last few comments!

2023-08-01 14:59 UTC, rustagir commented on source/quick-start/download-and-install.txt
> +               serde_json = "1.0.104"
```suggestion
               [dependencies]
               bson = "2.6.1"
               serde_json = "1.0.104"
               
               [dependencies.mongodb]
               version = "{+version+}"
               default-features = false
               features = ["async-std-runtime"]
```

2023-08-01 14:59 UTC, rustagir commented on source/quick-start/download-and-install.txt
> +               features = ["tokio-sync"]
```suggestion
               [dependencies.mongodb]
               version = "{+version+}"
               features = ["tokio-sync"]
```

2023-08-01 14:59 UTC, rustagir commented on source/quick-start/download-and-install.txt
> +and a new project directory with the driver dependencies recorded.
```suggestion
After you complete these steps, you should have Rust and Cargo installed 
and a new Rust project with the necessary driver dependencies.
```

2023-08-01 14:59 UTC, rustagir commented on source/quick-start/connect-to-mongodb.txt
> +            "plot": "Young Pauline is left a lot of money when her wealthy uncle dies. However, her uncle's secretary has been named as her guardian until she marries, at which time she will official
S: truncate to reduce horizontal scroll
```suggestion
            "plot": "Young Pauline is left a lot of money ...",
```

2023-08-01 14:59 UTC, rustagir commented on source/quick-start/connect-to-mongodb.txt
> +            },
```suggestion
            "_id": { ... },
```

2023-08-01 14:59 UTC, rustagir commented on source/quick-start/connect-to-mongodb.txt
> +            ] ...
S: even if you are truncating this document, make sure to show the close bracket for the JSON document

```suggestion
               "Edward Josè"
            ],
            ...
      }
```

2023-08-01 18:46 UTC, merged

2023-10-02 20:52 UTC, isabelatkinson commented on snooty.toml
> +min-rust-version = "1.57" # always set this to the minimum supported Rust version
Our MSRV is now 1.60 -- in the future, should we file a ticket to update this value when we bump it?

2023-10-02 20:52 UTC, isabelatkinson commented on source/code-snippets/quick-start/connect-async.rs
> +   println!("{}", serde_json::to_string_pretty(&my_movie).unwrap());
Ditto here from my previous review 🙂 https://github.com/mongodb/docs-rust/pull/16#discussion_r1341576234

2023-10-02 20:52 UTC, isabelatkinson commented on source/code-snippets/quick-start/connect-sync.rs
> +   println!("{}", serde_json::to_string_pretty(&my_movie).unwrap());
ditto above

2023-10-02 20:52 UTC, isabelatkinson commented on source/code-snippets/quick-start/connect-sync.rs
> +   let client = Client::with_uri_str(uri);
I think it would be a bit more clear to put the `?` operator at the end of this line rather than after `client` on line 12, i.e.
```
let client = Client::with_uri_str(uri)?;
```
This way makes it more apparent that the `with_uri_str` method returns a `Result`.

2023-10-03 13:56 UTC, rustagir commented on snooty.toml
> +min-rust-version = "1.57" # always set this to the minimum supported Rust version
I updated this in this commit - https://github.com/mongodb/docs-rust/commit/42da0efe608e1ad841cad55300b0e28595d4f44d

But yes, that would be great!