DOCSP-43425 Add sort data
mongodb/docs-rust pull request #131
Opened 2024-10-15 17:09 UTC by stephmarie17

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-43425>
Staging - <https://deploy-preview-131--docs-rust.netlify.app/fundamentals/crud/read-operations/sort/>

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-10-16 15:38 UTC, rustagir requested changes

2024-10-16 15:38 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +stage of the ``aggregate()`` method.
```suggestion
struct. To sort your results within an aggregation pipeline, create a ``$sort``
stage and pass the list of stages to the ``aggregate()`` method.
```

2024-10-16 15:38 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +documents by ``author`` as follows:
```suggestion
Use the ``sort()`` method of the ``FindOptions`` struct to sort
documents in ascending order of values of the ``author`` field as shown in the following code:
```

2024-10-16 15:38 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +aggregation pipeline to sort documents by ``author`` as follows:
```suggestion
Create a ``$sort`` stage that sorts documents in ascending order by the values of the ``author``
field as shown in the following code:
```

2024-10-16 15:38 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +Here are some examples of data sorted in ascending order:
```suggestion
The following list contains examples of data sorted in ascending order:
```

2024-10-16 15:38 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +Here are some examples of data sorted in descending order:
```suggestion
The following list contains examples of data sorted in descending order:
```

2024-10-16 15:38 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +~~~~~~~~~
```suggestion
Ascending Sort
~~~~~~~~~~~~~~
```

2024-10-16 15:38 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +``FindOptions`` struct.
S: remove redundant info

```suggestion
To specify an ascending sort,
pass the field you want to sort by and ``1`` to the ``sort()`` method of the
``FindOptions`` type.
```

2024-10-16 15:38 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +within the ``FindOptions`` struct.
```suggestion
To specify a descending
sort, pass the field you want to sort by and ``-1`` to the ``sort()`` method
of the ``FindOptions`` type.
```

2024-10-16 15:38 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +    id: i32,
S: remove these fields as they are not used in any example

2024-10-16 15:38 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +            length: 1088,
S: can we reduce the number of sample documents? I think 3-4 would be sufficient

2024-10-16 15:38 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +let mut cursor = my_coll.find(Some(filter), Some(find_options)).await?;
S: is it necessary to wrap the filters in Some()? This doesn't seem to be the case here: https://deploy-preview-131--docs-rust.netlify.app/fundamentals/crud/read-operations/retrieve/#find---example

2024-10-16 15:38 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +      { "_id": 1, "name": "The Brothers Karamazov", "author": Dostoevsky, "length": 824 }
S: investigate why these aren't being printed as Book types. Maybe you can use this api to print the cursor instead:
```rust

let mut cursor = my_coll
--
.find(doc! { "$and": vec!
[
doc! { "unit_price": doc! { "$lt": 12.00 } },
doc! { "category": doc! { "$ne": "kitchen" } }
] })
.sort(doc! { "unit_price": -1 })
.await?;
 
while let Some(result) = cursor.try_next().await? {
println!("{:?}", result);
}


```

2024-10-16 15:38 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +- :ref:`rust-query-guide`
S: add links in other guides to this sort guide

2024-10-16 19:17 UTC, stephmarie17 commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +let mut cursor = my_coll.find(Some(filter), Some(find_options)).await?;
Yeah I don't think so either, that was a Credal suggestion and I wasn't 100% sure about it based on other examples so I'll remove and see what tech review says.

2024-10-16 20:56 UTC, stephmarie17 commented on source/fundamentals/crud/read-operations/sort.txt
> +      { "_id": 1, "name": "The Brothers Karamazov", "author": Dostoevsky, "length": 824 }
Yes this one worked better! Also cleaner to read I think. Updating!

2024-10-16 21:26 UTC, stephmarie17 commented on source/fundamentals/crud/read-operations/sort.txt
> +~~~~~~~~~
Hmm I see what you mean, although other driver sort data pages just use `Ascending` so will opt to stick with that for consistency 👍

2024-10-17 14:11 UTC, rustagir approved these changes
looks good! few last small comments

2024-10-17 14:11 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +of the ``author`` field as shown in the following code:
```suggestion
Alternatively, you can create a ``$sort`` stage that sorts documents in ascending order by the values
of the ``author`` field as shown in the following code:
```

2024-10-17 14:11 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +    .sort(doc! { "author": 1 })  // 1 for ascending order, -1 for descending order
S: move code comment above this line to reduce horizontal scroll

2024-10-17 14:11 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +    doc! { "$sort": { "author": 1 } } // 1 for ascending order, -1 for descending order
S: move code comment above this line

2024-10-17 14:11 UTC, rustagir commented on source/fundamentals/crud/read-operations/sort.txt
> +- :ref:`rust-query-guide`
I was also thinking that you could add links to this page in the options [here](https://deploy-preview-131--docs-rust.netlify.app/fundamentals/crud/read-operations/retrieve/#:~:text=Default%3A%20None-,sort,-The%20sort%20to) and [here](https://deploy-preview-131--docs-rust.netlify.app/fundamentals/aggregation/#additional-information)
maybe also [here](https://deploy-preview-131--docs-rust.netlify.app/fundamentals/crud/read-operations/text-search/#sort-by-relevance)

2024-10-18 19:29 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +let find_options = FindOptions::builder()
When configuring a single option like this, it's less verbose to use the fluent-style API to set an option directly on the call to `find`:

```rust
let mut cursor = my_coll
    .find(doc! {})
    // 1 for ascending order, -1 for descending order
    .sort(doc! { "author": 1 })
    .await?;
```

I suggest using this pattern, or at least mentioning somewhere that this is an alternative to constructing an options struct.

2024-10-18 19:29 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +let mut cursor = my_coll.aggregate(pipeline, None).await?;
The `aggregate` method only accepts one parameter, so this should look like:

```
let mut cursor = my_coll.aggregate(pipeline).await?;
```

(This is new in the 3.0 API; you might have seen old examples like this in which the second parameter was for options.)

2024-10-18 19:29 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +let find_options = mongodb::options::FindOptions::builder()
```suggestion
let find_options = FindOptions::builder()
```
not sure if you have a convention for this, but we generally omit the full path for types like this and expect that the user would import the type (as is done in this file)

2024-10-18 20:52 UTC, stephmarie17 commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +let find_options = mongodb::options::FindOptions::builder()
Ah that one snuck in. Ty for catching!

2024-10-18 20:54 UTC, stephmarie17 commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +let mut cursor = my_coll.aggregate(pipeline, None).await?;
Good to know, removing! Q: in that case, once this page is merged, does it only make sense to backport the changes to the docs up to v3.0?

2024-10-18 20:57 UTC, stephmarie17 commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +let find_options = FindOptions::builder()
That's good to know, I was wondering what the best practice was for when to use the style above vs use FindOptions. I can update to include a multi-option example and use the fluent-style API for the single option example. Ty!

2024-10-21 20:23 UTC, isabelatkinson commented on source/fundamentals/crud/read-operations/sort.txt
> +struct. This is useful for configuring multiple options.
```suggestion
struct.
```

I suggest omitting the last sentence and rephrasing the title on line 70. We expect that the main use case for the `with_options` method is caching/reusing options across multiple method calls, so that the list of options doesn't need to be re-written. This is more useful when there are more options being configured, but it's not _necessarily_ preferable to construct an options struct when multiple options are set. Sorry, my original comment wasn't very clear on this distinction!

2024-10-21 20:23 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/crud/sort.rs
> +let mut cursor = my_coll.aggregate(pipeline, None).await?;
yes, these examples will be invalid for the pre-3.0 API

2024-10-21 20:56 UTC, stephmarie17 commented on source/fundamentals/crud/read-operations/sort.txt
> +struct. This is useful for configuring multiple options.
Ah ok that makes sense! Will update. For the ``Ascending`` and ``Descending`` examples, would you suggest updating to use the fluent-style API there as well as opposed to using the ``with_options`` method as they are now?

2024-10-22 18:48 UTC, isabelatkinson commented on source/fundamentals/crud/read-operations/sort.txt
> +struct. This is useful for configuring multiple options.
Yep, I think the fluent API is better-suited for these examples

2024-10-22 19:05 UTC, stephmarie17 commented on source/fundamentals/crud/read-operations/sort.txt
> +struct. This is useful for configuring multiple options.
Sounds good. Just updated 👍

2024-10-23 15:52 UTC, stephmarie17 commented on source/fundamentals/crud/read-operations/sort.txt
> +struct. This is useful for configuring multiple options.
@isabelatkinson If the latest changes look good to you, can you ✅ when you have a moment? Ty!

2024-10-23 17:43 UTC, isabelatkinson approved these changes

2024-10-23 18:02 UTC, merged