DOCSP-43424 Skip returned results
mongodb/docs-rust pull request #133
Opened 2024-10-23 21:22 UTC by stephmarie17

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <hhttps://jira.mongodb.org/browse/DOCSP-43425>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-10-24 16:09 UTC, norareidy requested changes
Really good work so far! I have some suggestions related to the structure of the page, so mainly requesting changes for that

2024-10-24 16:09 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +Aggregation
S: since this is another way of skipping documents, I'd make it a third subsection under "Skip Documents" rather than a separate section

2024-10-24 16:09 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +----
S: [nit] this header could be more descriptive. Maybe "Skip Documents in Operation Results" or just "Skip Documents":
```suggestion
Skip Documents
--------------
```

2024-10-24 16:09 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +To learn more about the operations mentioned in this guide, see the following:
S: add a word describing the links, like "guides" or "resources"
```suggestion
To learn more about the operations mentioned in this guide, see the following guides:
```

2024-10-24 16:09 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +following API Documentation:
S: you can lowercase "documentation" here
```suggestion
following API documentation:
```

2024-10-24 16:09 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +
S: same suggestions here about "with" and the "Sorts the results..." bullet point

2024-10-24 16:09 UTC, norareidy commented on source/includes/fundamentals/code-snippets/crud/skip.rs
> +
S: we try to add code comments above each example to help with LLM ingestion; each comment just describes what's happening in the code. Here's a [google doc](https://docs.google.com/document/d/1Bnhh1OsGRUuXo_6yVUASGWiSX6sWuqrEFxPP6sLZDHM/edit?usp=sharing) with the guidelines for code example comments!
```suggestion
// Retrieves documents in the collection, sorts results by their "author" values, 
// and skips the first two results
```

2024-10-24 18:32 UTC, stephmarie17 commented on source/fundamentals/crud/read-operations/skip.txt
> +Aggregation
Re-arranged this a little because I didn't want a separate "Example" section to nest, lmk what you think!

2024-10-24 21:48 UTC, norareidy approved these changes
A few more comments, but LGTM!

2024-10-24 21:48 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +  method of the ``FindOptions`` struct
S: Since the FindOptions struct only has one member [method](https://docs.rs/mongodb/3.1.0/mongodb/options/struct.FindOptions.html#method.builder) (`builder()`) and a bunch of [fields](https://docs.rs/mongodb/3.1.0/mongodb/options/struct.FindOptions.html#fields) you can set, I don't know if FindOptions::skip() is the right syntax. Maybe this could just say:
```suggestion
- :ref:`FindOptions struct <rust-findoptions-skip>`: Use the ``skip()`` option builder method to configure a ``FindOptions`` struct
```

2024-10-24 21:48 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +<rust-aggregation-skip>`.
S: I'd add this to the list above, since it's a third way to skip results. The bullet could say something like:
```suggestion
- :ref:`Aggregation pipeline <rust-aggregation-skip>`: Create a pipeline that uses the ``$skip`` stage
```

2024-10-24 21:48 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +to the ``find()`` method to skip documents.
S: I think you can swap the order of these sentences
```suggestion
To skip documents, you can chain the ``skip()`` method
to the ``find()`` method. The ``skip()`` method takes an integer that specifies the number of documents to
omit from the beginning of the result set.
```

2024-10-24 21:48 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +using the ``skip()`` setter method. Then, chain the ``with_options()`` method to
S: I suggested saying setter method before (my bad) but based on how [other pages](https://www.mongodb.com/docs/drivers/rust/current/fundamentals/crud/read-operations/cursor/#specify-cursor-behavior) describe these methods, I'd say "option builder method" instead:
```suggestion
using the ``skip()`` option builder method. Then, chain the ``with_options()`` method to
```

2024-10-24 21:48 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +- Limits the results to two documents
S: up to you, but since the focus of this page is skip() I don't think you need to include limit() in the example.

2024-10-24 21:48 UTC, norareidy commented on source/fundamentals/crud/read-operations/skip.txt
> +learn more, see the :ref:`rust-aggregation` guide.
S:
```suggestion
learn more about aggregation operations, see the :ref:`rust-aggregation` guide.
```

2024-10-25 21:54 UTC, isabelatkinson approved these changes

2024-10-25 22:11 UTC, merged