DOCSP-30549: tracing and logging
mongodb/docs-rust pull request #14
Opened 2023-07-21 18:25 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30549>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30549-tracing-logging/fundamentals/tracing-logging/), [index](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30549-tracing-logging/#fundamentals)

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-07-28 17:15 UTC, jordan-smith721 requested changes
Nice work! Just some minor suggestions

2023-07-28 17:15 UTC, jordan-smith721 commented on source/fundamentals/tracing-logging.txt
> +dependency to your ``Cargo.toml`` file:
Since a user may not have read the earlier section when they get here, maybe add a ref link to the example showing the other variables they need to enable here. Another option could be to show the whole Cargo.toml file here and highlight the line you're calling out.

2023-07-28 17:15 UTC, jordan-smith721 commented on source/fundamentals/tracing-logging.txt
> +If you run your application to trace against commands at the ``debug``
Nit: I don't think you're running your application specifically _to trace_, if I'm understanding this correctly. The tracing is an addition to running the application.

```suggestion
If you run your application and trace against commands at the ``debug``
```

2023-07-28 17:15 UTC, jordan-smith721 commented on source/fundamentals/tracing-logging.txt
> +When you perform a write operation, the driver generates trace messages:
Suggestion: Clarify when this happens so it's clear that we're still talking about the command above

```suggestion
With ``debug`` level tracing specified, when you perform a write operation, the driver generates trace messages:
```

2023-07-28 17:15 UTC, jordan-smith721 commented on source/fundamentals/tracing-logging.txt
> +   env_logger = "0.10.0"
Similar comment to earlier. If the user needs to have the dependencies specified earlier as well as these, then I would link to them or show them here.

2023-07-28 17:15 UTC, jordan-smith721 commented on source/fundamentals/tracing-logging.txt
> +When you open and use a connection, the driver generates log messages:
Similar to above comment - add clarification so that this connects with the above commands

```suggestion
With ``debug`` level logging specified, when you open and use a connection, the driver generates log messages:
```

2023-07-28 17:15 UTC, jordan-smith721 commented on source/fundamentals/tracing-logging.txt
> +If you run your application to log against connections at the ``debug``
Same suggestion as above:

```suggestion
If you run your application and log against connections at the ``debug``
```

2023-07-28 17:15 UTC, jordan-smith721 commented on source/fundamentals/tracing-logging.txt
> +----------------------
Comment this out for now if we aren't going to show any additional information at the moment (currently it's all commented out)

2023-08-01 15:01 UTC, rustagir commented on source/fundamentals/tracing-logging.txt
> +provides a continuous view. Logs might help you identify an issue in
In my research, I also couldn't find a great explanation of this. I'm going to ping the Rust team to get some clarification!

2023-08-01 15:04 UTC, rustagir commented on source/fundamentals/tracing-logging.txt
> +``RUST_LOG`` environmental variable when you compile and run your
I think this was just a terminology mistake

2023-08-01 15:12 UTC, rustagir commented on source/fundamentals/tracing-logging.txt
> +dependency to your ``Cargo.toml`` file:
changed in both tracing and logging sections

2023-08-01 15:13 UTC, rustagir commented on source/fundamentals/tracing-logging.txt
> +If you run your application to trace against commands at the ``debug``
changed in both sections

2023-08-01 21:05 UTC, jordan-smith721 approved these changes
LGTM once we get the clarification from the Rust team on the tracing vs logging explanation

2023-08-07 16:52 UTC, rustagir commented on source/fundamentals/tracing-logging.txt
> +provides a continuous view. Logs might help you identify an issue in
Per the Rust team, "there's not actually a huge difference between the `tracing` and `log` crates."
The design document that I was linked to says:
"tracing supports emitting data in a more structured form than log does, with arbitrary key-value pairs (vs. the string and fixed metadata log records support). This feature is sort of similar to the structured logging the server now does, where the logs are in JSON rather than being strings. Structured logging makes it easier for applications/tools to consume events/log messages programmatically." -- I will highlight this on the page

2023-08-07 17:26 UTC, merged

2023-10-02 20:57 UTC, isabelatkinson reviewed
lgtm!