DOCSP-30541: change documents
mongodb/docs-rust pull request #15
Opened 2023-07-25 18:59 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30541>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30541-update-guide/fundamentals/crud/write-operations/change/), [WO](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30541-update-guide/fundamentals/crud/write-operations/) / build

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-07-26 22:30 UTC, jordan-smith721 requested changes
Nice work on this so far! I think there are some changes we can make to make it a little more clear and concise

2023-07-26 22:30 UTC, jordan-smith721 commented on source/fundamentals/crud/write-operations/change.txt
> +<rust-replace-example>` in this section.
Similar suggestion to the update overview. I think as an overview, this could benefit from a little more information, and I don't think the link to the example is necessary (especially if the example gets moved up a heading level)

```suggestion
You can perform a replace operation with the ``replace_one()`` method. This method removes all existing fields of a document except for the _id field and substitutes the removed fields with the new fields and values.
```

2023-07-26 22:30 UTC, jordan-smith721 commented on source/fundamentals/crud/write-operations/change.txt
> +document that will replace an existing document. Replacement documents
Suggestion: clarify
```suggestion
The ``replace_one()`` method requires a **replacement document**, which specifies the
fields and values that will replace an existing document. Replacement documents
```

2023-07-26 22:30 UTC, jordan-smith721 commented on source/fundamentals/crud/write-operations/change.txt
> +contains the following properties:
Similar to above suggestion:

```suggestion
The ``replace_one`` method returns  an
``UpdateResult`` type if the operation is successful. The ``UpdateResult`` type
contains information about the update operation in the following properties:
```

2023-07-26 22:30 UTC, jordan-smith721 commented on source/fundamentals/crud/write-operations/change.txt
> +```````````````
Suggestion: Move this up a level to show in the "On this page" 
```suggestion
Replace Example
~~~~~~~~~~~~~~~
```

2023-07-26 22:30 UTC, jordan-smith721 commented on source/fundamentals/crud/write-operations/change.txt
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Suggestion: Since this covers both Update and Replace, rather than just Replace, move it up a heading level

```suggestion
Modify Update and Replace Behavior
----------------------------------
```

2023-07-26 22:30 UTC, jordan-smith721 commented on source/fundamentals/crud/write-operations/change.txt
> +- Options to modify the default behavior of the method
If the options are an optional parameter, can we call that out here?

2023-07-26 22:30 UTC, jordan-smith721 commented on source/fundamentals/crud/write-operations/change.txt
> +- ``find_one_and_replace()`` *(not discussed in this guide)*
Question: Why are these not discussed in this guide? Are they too complex and need a new page, or are they just no longer used? Do these need to be brought up at all, and if so can we give a little more information on why they're not included in this guide? Or maybe at minimum link to the API documentation.

IMO calling them out as available methods but then saying they're not discussed is more confusing than helpful.

2023-07-26 22:30 UTC, jordan-smith721 commented on source/fundamentals/crud/write-operations/change.txt
> +instance:
Do you think it would be helpful to also show an example of how to pass this UpdateOptions instance to an operation? We do somewhat show that in the graphic at the top of the page, and we also show how to pass "None" in the previous examples, but we don't really show how to do it anywhere without placeholders. I guess it may be pretty intuitive at this point, so I'll defer to your decision on it

2023-07-26 22:30 UTC, jordan-smith721 commented on source/fundamentals/crud/write-operations/change.txt
> +.. - :ref:`rust-compound-operations`
Are these intentionally all commented out? If so I would comment out this whole section until there is content to put in it. As it stands right now it says, "see the following guides: " and then doesn't show anything

2023-07-28 17:40 UTC, rustagir commented on source/fundamentals/crud/write-operations/change.txt
> +- ``find_one_and_replace()`` *(not discussed in this guide)*
Ok, I can add some detail to the TODO on how to include these, but removing them from this list

2023-07-28 17:42 UTC, rustagir commented on source/fundamentals/crud/write-operations/change.txt
> +instance:
Sure, I can add this to the code.

2023-07-28 17:50 UTC, rustagir commented on source/fundamentals/crud/write-operations/change.txt
> +.. - :ref:`rust-compound-operations`
I uncommented the manual link

2023-07-28 17:59 UTC, rustagir commented
I changed the name to Modify Documents per the poll in our channel

2023-07-28 18:51 UTC, jordan-smith721 approved these changes
LGTM!

2023-07-28 18:57 UTC, merged

2023-09-29 19:50 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/crud/change.rs
> +use bson::Document;
code here looks good, I'd recommend running the formatter on this file though as it looks like some of the formatting here deviates from our usual style. `rustfmt +nightly --unstable-features --edition 2021 <filename>` should do the trick