DOCSP-45153 Add MONGODB-OIDC
mongodb/docs-rust pull request #152
Opened 2024-11-21 17:41 UTC by stephmarie17

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-45153>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-11-22 14:52 UTC, mongoKart requested changes
a few small things, but great job overall!

2024-11-22 14:52 UTC, mongoKart commented on source/fundamentals/enterprise-auth.txt
> +specifies the authentication mechanism by using the following placeholders:
S: feels cleaner to avoid using "following" twice (i know this is tough to avoid). could you do something similar to what you did in the next example (lines 173-183)?

2024-11-22 14:52 UTC, mongoKart commented on source/fundamentals/enterprise-auth.txt
> +  the ``TOKEN_RESOURCE`` to with the value of the audience parameter configured
```suggestion
  the ``TOKEN_RESOURCE`` to the value of the audience parameter configured
```

2024-11-22 14:52 UTC, mongoKart commented on source/fundamentals/enterprise-auth.txt
> +GCP IMDS
Q: does the rust driver natively support gcp?

2024-11-22 14:52 UTC, mongoKart commented on source/fundamentals/enterprise-auth.txt
> +function to use OIDC to authenticate.
S:

```suggestion
including the AWS Elastic Kubernetes Service (EKS). To use OIDC to authenticate
against unsupported platforms, you must define a custom callback
function.
```

2024-11-22 14:52 UTC, mongoKart commented on source/fundamentals/enterprise-auth.txt
> +struct to ``oidc::Callback::machine``:
S: present this as a series of steps:

First, set the ``AWS_WEB_IDENTITY_TOKEN_FILE`` environment variable...then, set this field, as shown in the following example:

2024-11-22 14:52 UTC, mongoKart commented on source/fundamentals/enterprise-auth.txt
> +   ``RefreshToken``, and any timeouts, then returns them.
```suggestion
2. The callback negotiates with the IDP to obtain an ``AccessToken`` and
     any timeout values, then returns them. It might also return a 
    ``RefreshToken`` (I assume this depends on server config? If so, I'd mention this)
```

2024-11-22 19:13 UTC, stephmarie17 commented on source/fundamentals/enterprise-auth.txt
> +GCP IMDS
Yep found out that it does, I got an example from Kevin via Slack 👍

2024-11-25 17:54 UTC, stephmarie17 commented on source/fundamentals/enterprise-auth.txt
> +in the server manual.
I noticed in the Rust docs, other pages just say "Server manual" so I opted to just capitalize server here just to stay consistent and avoid touching a lot of other lines with this PR, but will check with the main repo steward to see how we want to use this going forward.

2024-11-25 17:55 UTC, stephmarie17 commented on source/fundamentals/enterprise-auth.txt
> +struct to ``oidc::Callback::machine``:
Rephrased this a bit and added some additional relevant resources.

2024-11-25 18:02 UTC, mongoKart approved these changes
LGTM!

2024-11-27 16:21 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/enterprise-auth.rs
> +        let (access_token, expires, refresh_token) = negotiate_with_idp(ctx, idpInfo.Issuer).await?;
Some of this doesn't look like valid Rust/part of the driver API. I suggest running `cargo build` to ensure that the code here compiles, I can help out with this if needed!

2024-12-04 21:07 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/enterprise-auth.rs
> +    async fn cb(params: CallbackContext) -> mongodb::error::Result<IdpServerResponse> {
Suggest updating to the following:

```
let callback = Callback::human(move |context| {
    async move {
        // Do the human flow using the provided context. See here for more details:
        // https://auth0.com/docs/authenticate/login/oidc-conformant-authentication/oidc-adoption-auth-code-flow
        todo!()
    }
    .boxed()
});
let credential = Credential::builder()
    .mechanism(AuthMechanism::MongoDbOidc)
    .oidc_callback(callback)
    .build();
client_options.credential = Some(credential);
let client = Client::with_options(client_options)?;
```

I think we're best off here describing what should be in the callback and linking to documentation, as the actual contents will depend on the user's workflow.

2024-12-04 21:07 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/enterprise-auth.rs
> +            doc! {"ENVIRONMENT": "gcp", "TOKEN_RESOURCE": "<audience>"}
```suggestion
            doc! { "ENVIRONMENT": "gcp", "TOKEN_RESOURCE": "<audience>" }
```

2024-12-04 21:07 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/enterprise-auth.rs
> +            .await;
```suggestion
            .await?;
```

2024-12-04 22:17 UTC, stephmarie17 commented on source/includes/fundamentals/code-snippets/enterprise-auth.rs
> +    async fn cb(params: CallbackContext) -> mongodb::error::Result<IdpServerResponse> {
I see what you mean, that makes sense. Updated to use a placeholder in the snippet and an explainer before that, please take a look and let me know if that works here. Ty!

2024-12-05 20:31 UTC, isabelatkinson approved these changes
looks good! I have a few more small suggestions but I'll leave it up to you whether to add the changes 🙂

2024-12-05 20:31 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/enterprise-auth.rs
> +            todo!()
suggest using the following which will still compile if a user copy/pastes in the code snippet

```suggestion
            todo!("human flow")
```

2024-12-05 20:31 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/enterprise-auth.rs
> +use mongodb::options::oidc::{self, CallbackContext, IdpServerResponse};
looks like indentation is still a bit off in a few places (lines 80-84, lines 102-106)

2024-12-05 20:31 UTC, isabelatkinson commented on source/fundamentals/enterprise-auth.txt
> +custom flow. Refer to `Authorization Code Flow with OIDC
it might be worth mentioning here that the callback should return a `Result<IdpServerInfo>` since that's not shown explicitly in the code example

2024-12-05 21:27 UTC, stephmarie17 commented on source/includes/fundamentals/code-snippets/enterprise-auth.rs
> +            todo!()
Thank you, updated this and added `;` after the placeholder and it compiled fine 👍

2024-12-05 21:29 UTC, stephmarie17 commented on source/fundamentals/enterprise-auth.txt
> +custom flow. Refer to `Authorization Code Flow with OIDC
Updated the explainer paragraph before the code snippet and added an API docs link to the resources at the bottom of the guide.

2024-12-05 22:22 UTC, merged