Docsp 31495 specify query pg
mongodb/docs-rust pull request #16
Opened 2023-07-26 20:49 UTC by nickldp

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-31495>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-31495-Specify-Query-pg/fundamentals/crud/query/>

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?

2023-07-26 20:59 UTC, nickldp commented
Was unsure on whether my options should be empty or sort by title. Most of the examples use the empty options while the last one uses the sort by title. Please leave an opinion on what is better!

2023-07-27 20:58 UTC, rustagir requested changes
good start! In general, this page should match the general layout given in the other merged CRUD pages. Reference those, as well as the existing Go page for this content, to help guide your next revision

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +--------------------
S: Change all headings

```suggestion
Comparison
------------
```

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +with values in a collection. Common comparison operators include
```suggestion
Comparison operators allow you to query for documents by comparing them
to values in the query filter. Common comparison operators include
```

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +value greater than 5 and prints them out:
S: same feedback - move to file and separate into a new section

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +
S: Somewhere, explain that an empty query filter returns all documents in a collection

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +   let find_options = FindOptions::builder().sort(doc! { "title": 1 }).build();
S: leave options as `None` in all examples

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +operator or a literal value query. The following operation uses the
```suggestion
Logical operators require with at least two match criteria and match documents based on
if they meet some, all, or none of these criteria. A common ....

 ... The following operation uses the
```

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +   let query = doc! { "qty": doc! { "$not": doc! { "$gt": 5 }}};
S: change this example to use `$and` or `$or` to display the syntax of using multiple query statements

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +  two queries are equivalent:
```suggestion
  If a query filter contains a literal value query with multiple field-value pairs,
  the driver matches documents that meet all of the criteria.
  
  For example, the following queries produce equivalent results:
```

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +entry for :manual:`Comparison Query Operators </reference/operator/query-comparison/>`.
I: This should link to the logical operators section in the manual.
S: change to link to the correct place, also add this similar link for each section

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +type of field. The following operation uses the element operator
S: simplify the language, the parallelism between presence, absence, and type is confusing

```suggestion
Element operators allow you to match documents based on the types of specified fields and if they include specified fields. The following operation uses the element operator
```

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +the :manual:`$exists operator </reference/operator/query/exists/>`.
S: Instead of linking to the specific operator, link to the list of operators in the element category

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +the :manual:`$mod operator </reference/operator/query/mod/>`.
S: Add an additional information & API documentation

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +regex and text searches, when querying for documents in a collection.
```suggestion
Evaluation operators match documents by analyzing values in specified fields.
```

2023-07-27 20:58 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +Common evaluation operators include ``$regex`` and ``$text``.
S: explain what these operators do at a high level

2023-08-01 14:26 UTC, rustagir requested changes

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +and :ref:`query operators <rust-query-operators>` with the ``Find()``
I: this isn't a rust method
S: use ``find()``

```suggestion
and :ref:`query operators <rust-query-operators>` with the ``find()``
```

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +method to match a subset of documents.
```suggestion
The examples in the following sections show how to specify queries by using the ``find()``
method to match documents in a collection.
```

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +  the sample data that is used by the read operation examples.
S: text after colons should be lowercase (change in all bullet pts)
```suggestion
- :ref:`Sample Data for Examples <rust-query-sample-data>`: presents
  the sample data that is used by the read operation examples.
```

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +
I: this guide is still missing bitwise and array operators. https://www.mongodb.com/docs/manual/reference/operator/query/#query-selectors
This page should cover all but geospatial
S: add sections describing these operators

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +   { "_id": 2, "name": "apple", "quantity": 4, "price": 2, "description": "a red or green fruit" },
S; change the description field in document 2 to be shorter so that there is no horizontal scroll

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +that has the value of "pear":
S: monospace all field and value names wherever present
```suggestion
literal query to search for documents containing a field called ``"name"``
that has the value of ``"pear"``:
```

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +      :language: rust
S: the output for all of these should be in json or none

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +   .. input:: /includes/fundamentals/code-snippets/crud/query.rs
S: make copyable
add `:copyable: true`

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +for documents with a quantity value greater than 5 and prints them out:
```suggestion
The following operation uses the comparison operator ``$gt`` to match
documents with a ``quantity`` value greater than ``5``:
```

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +if they meet some, all, or none of these criteria. For instance, you can use the ``$or``
S: replace for instance with for example per the [style guide](https://www.mongodb.com/docs/meta/style-guide/terminology/alphabetical-terms/#f:~:text=figures%20and%20tables.-,for%20instance,-Use%20for%20example)

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +is less than 5 and prints them out:
S: monospace fields and values, remove "prints them out"

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +.. note::
S: add a space

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +      :language: rust
S: make all output visible false by default
:visible: false

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +specified fields and if they include specified fields.
```suggestion
Element operators allow you to match documents based on the types of
specified fields or if they include specified fields. 
```

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +fields.
S: provide more explanation on what analyzing means in this context

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +:manual:`Query Operators </reference/operator/query/>`.
```suggestion
To learn more about query operators, see :manual:`Query Selectors </reference/operator/query/>` in the Server manual.
```

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +- `Find() <{+api+}//#finding-documents-in-a-collection>`__
I; broken link
S: link to 
```suggestion
- `find() <{+api+}/struct.Collection.html#method.find>`__
```

2023-08-01 14:26 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +    }
S: use snake case variable names and print using the json formatter (applies to all)
```suggestion
    while let Some(result) = cursor.try_next().await? {
        let doc: Document = bson::from_document(result)?;
        println!("{}", serde_json::to_string_pretty(&doc).unwrap());
    }
```

2023-08-01 14:26 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +    let mut cursor = my_coll.find(query, None);
I: this and the next example are missing await? calls
```suggestion
    let mut cursor = my_coll.find(query, None).await?;
```

2023-08-01 14:26 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +    }
update output to match what the program prints in each section

2023-08-01 14:26 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +           doc! { "qty": doc! { "$gt": 5 } },
I: the field name ``qty`` doesn't exist in the sample data. did you mean ``quantity``? Change everywhere present, it affects the output.

2023-08-01 14:26 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +    let query = doc! { "qty": doc! { "$mod": [ 3, 0 ] } };
```suggestion
    let query = doc! { "quantity": doc! { "$mod": [ 3, 0 ] } };
```

2023-08-01 14:26 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +      { "_id": 3, "name": "banana", "quantity": 36, "price": 4 }
I: this output does not match the expected output by searching for a literal of "pear" -- please double check and make sure all of your output matches what actually is printed when you run the file.

2023-08-01 14:26 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +    //end-evaluation
S: add an `Ok(())` call to the end of the main method
```suggestion
    //end-evaluation
    
    Ok(())
```

2023-08-01 20:25 UTC, rustagir requested changes

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +
S: Add the new sections to this list

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +  the sample data that is used by the read operation examples.
S: remove the periods from these descriptions
```suggestion
- :ref:`Sample Data for Examples <rust-query-sample-data>`: presents
  the sample data that is used by the read operation examples
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +- :ref:`Literal Value Queries <rust-literal-values>`: describes how to
```suggestion
- :ref:`Literal Values <rust-literal-values>`: describes how to
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +   { "_id": 4, "name": "pear", "quantity": 28, "price": 6, "vendorS": ["A", "C" ] }
S: since there's still horizontal scroll, can we remove either the `quantity` or `price` fields? Also, it looks like theres a capitalization error in `vendors`
```suggestion
   { "_id": 1, "name": "orange", "quantity": 7, "price": 5 },
   { "_id": 2, "name": "apple", "quantity": 4, "price": 2, "description": "Granny Smith" },
   { "_id": 3, "name": "banana", "quantity": 36, "price": 4 },
   { "_id": 4, "name": "pear", "quantity": 28, "price": 6, "vendors": ["A", "C" ] }
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +information about its ``quantity``, and its ``price``:
S: update this description so that it describes all of the fields. I also don't think the description needs to have monospace, as its not directly referencing the fields, but what they describe
```suggestion
The examples in this guide use the following sample documents. Each
document represents a fruit in a store's inventory, and contains
information about its quantity and price. Some documents contain additional fields that describe
the fruit or its vendors:
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +      :language: rust
This still needs to be resolved
```suggestion
      :language: json
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +   filter = doc! { "<field>": doc! { "<operator>": "<value>" } };
S: these still need `let` declarations
```suggestion
.. code-block:: rust
   :copyable: false

   let filter = doc! { "<field>": "<value>" };

To match criteria that include query operators use the following format:

.. code-block:: rust
   :copyable: false

   let filter = doc! { "<field>": doc! { "<operator>": "<value>" } };
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +entry for :manual:`Comparison Query Operators </reference/operator/query-comparison/>`.
S: all of the sentences that link to the manual should be formatted as laid out in [this comment](https://github.com/mongodb/docs-rust/pull/16#discussion_r1280712796)

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +individual fields or the entire collection's documents.
S: right now, this sentence still doesn't explain what an evaluation operator actually does. I think it would help readers to understand what evaluation entails
```suggestion
Evaluation operators analyze individual fields or a collection's documents to
determine if they meet certain criteria. Each evaluation operator performs a different function.
For example, the ``$mod`` operator performs a mathematical operation on a field value, and the ``$where`` operator allows you to evaluate values against JavaScript expressions.
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +a remainder of 0:
S: including the remainder clause is redundant, as if a number is divisible by some divisor, the remainder must be 0 by definition
```suggestion
The following operation uses the evaluation operator ``$mod`` to search
for documents with a ``quantity`` value that is divisible by 3:
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +bits set as ``6`` (which is "00000110"):
```suggestion
The following example matches documents where the ``price`` has the same
bits set as ``6``, which is equivalent to ``00000110`` in binary:
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +Array operators check the values or amount of elements in an array field.
```suggestion
Array operators check the values or amount of elements in an array-valued field.
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +"C":
```suggestion
The following example matches documents where the ``vendor`` contains
``"C"``:
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +"C":
S: correct this description so that it matches what the code example does. the code example matches documents where the ``vendors`` field is exactly `[ "A", "C" ]`

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +Query Operators </reference/operator/query-array/>` page.
S: fix link text
```suggestion
For a full list of bitwise operators, see the :manual:`Array
Query Operators </reference/operator/query-array/>` page.
```

2023-08-01 20:25 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +    ];
S: update this to match the sample data used on the page

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +         "qty": doc! { "$gt": 4 }
```suggestion
         "quantity": doc! { "$gt": 4 }
```

2023-08-01 20:25 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +            doc! { "qty": { "$gt": 4 }}
```suggestion
            doc! { "quantity": { "$gt": 4 }}
```

2023-08-01 20:25 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +           doc! { "qty": doc! { "$gt": 10 } },
```suggestion
           doc! { "quantity": doc! { "$gt": 10 } },
```

2023-08-02 18:45 UTC, rustagir approved these changes
approving but please resolve last few things!

2023-08-02 18:45 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +  querying for documents in a collection
```suggestion
- :ref:`Bitwise Operators <rust-bitwise-operators>`: describes how to
  query based on the equivalent bits set of a base-10 value
```

2023-08-02 18:45 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +   { "_id": 3, "name": "banana", "quantity": 36},
```suggestion
   { "_id": 3, "name": "banana", "quantity": 36 },
```

2023-08-02 18:45 UTC, rustagir commented on source/fundamentals/crud/read-operations/query.txt
> +- :ref:`Comparison Operators <rust-query-operators>`: describes how to
S: make the link text exactly match what the sections are called (applies to all in this list)
```suggestion
- :ref:`Comparison <rust-query-operators>`: describes how to
```

2023-08-02 18:45 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +    // $mod means "modulo" and returns the remainder after division
S: this code comment isnt exactly correct - the `$mod` operator checks if the value divided by a divisor has the specified remainder
```suggestion
    // $mod means "modulo" and checks if the remainder is a specific value
```

2023-08-02 19:11 UTC, merged

2023-09-29 19:22 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +use bson::Document;
it looks like some of the tab sizing/spacing in this file is inconsistent - running `rustfmt` on this file should fix that

2023-09-29 19:22 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/crud/query.rs
> +    let query = doc! { "$and": vec! [
it isn't necessary to include `vec!` here - the `doc!` macro will properly interpret square brackets on their own. e.g.
```
let doc = doc! { "array": [1, true, "abc"] };
```