DOCSP-30531: db collection page
mongodb/docs-rust pull request #17
Opened 2023-07-28 19:24 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30531>
Staging - 

## Self-Review Checklist

- [] Is this free of any warnings or errors in the RST?
- [] Did you run a spell-check?
- [] Did you run a grammar-check?
- [] Are all the links working?

2023-08-01 17:26 UTC, ccho-mongodb requested changes
I like the example, but think document validation belongs on a separate page instead of within Create a Collection. I added a few issues and suggestions as well.

2023-08-01 17:26 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +**Document validation** lets you restrict the types of documents that
Suggestion:

I think repeating the heading text isn't necessary and may not be the best way to word this intro sentence.

```suggestion
You can use **document validation**  to restrict the types of documents that
```

2023-08-01 17:26 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +validation rules.
Suggestion:

I think "you can successfully execute only" is awkward and "you can" implies the user might be responsible for success/failure.

"If you implement document validation, the server allows you to execute only write operations that follow those validation rules."

2023-08-01 17:26 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +setting the following fields in a ``CreateCollectionOptions`` instance:
Suggestion:
I think "implement document validation" should match with the prior description "if you implement document validation" to make it clear they're the same thing. I would prefer "implement" for activation of a feature or implementation of an interface. I think "specify" might be preferable only when providing a value to something.

2023-08-01 17:26 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +  validation rules. To learn more about specifying a validation action, see :manual:`validationAction
Issue:

I wasn't able to find this information in the Server manual link -- only "whether to error on invalid documents or just warn...".

Suggestion:
If there are only two values, incorporate them into this description.
"specifies whether the server should raise an error or warn when you insert documents that don't follow the validation rules. Possible values: "ValidationAction::Error", "ValidationAction::Warn"."

Similar comment for the other Server manual links.

2023-08-01 17:26 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +  ``"always"``.
Suggestion:
I think the example could be simplified by reducing this to two or three values instead of four since only two are used in the example data.

2023-08-01 17:26 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +With these document validation rules, you can successfully insert the
Suggestion:

I think "with these ..." implies that they're passed along in the insert, which could be avoided by rewording the sentence.

```suggestion
When you set these document validation rules, you can successfully insert the
```

I think starting two sequential sentences with "When" and "However," is a common pattern that can make it easier to follow.

2023-08-02 14:01 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +  </reference/command/collMod/?utm_source=compass&utm_medium=product#mongodb-collflag-validator>` in the Server manual.
manually removed the flags

2023-08-02 14:02 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +perform an insert operation against a collection of a nonexistent
fixed in 2 places

2023-08-02 14:05 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +.. note:: List Databases
The list commands are run on the instance one "above" the type that each section describes-- for example, to list databases you would call the method on the `Client` and to list collections you would call the method on the `Database`. Given that this is the case, does it makes sense for the sections to be under the database/collection headers or in new top level sections

2023-08-02 14:16 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +   about each database, call the ``list_databases()`` method.
Did for both "List" sections

2023-08-02 14:16 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +The following example uses the ``database()`` method to access a
changed structure since I moved the list section out of the admonition anyways

2023-08-02 14:18 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +To drop, or permanently delete, a database, call the ``drop()`` method
removed the admonition since the point is clear in the text now

2023-08-02 14:19 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +To learn about how to run a database command, see :ref:`rust-run-command`.
since omitting the section from the page, no longer relevant

2023-08-02 14:19 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +Run a Database Command
I can add this to addtl info instead.

2023-08-02 14:20 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +- `ValidationLevel <{+api+}/options/enum.ValidationLevel.html>`__
Choosing to move the links to the end of each section

2023-08-02 14:37 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +Document Validation
moving to its own page, but divided on whether or not to nest it under the Databases & Collections page. Open to feedback on placement

2023-08-02 14:50 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +   You must parameterize your ``Collection`` instance by specifying what
I believe that to even get a handle on a collection, you need to parameterize the collection.

2023-08-02 14:56 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +To drop, or permanently delete, a database, call the ``drop()`` method
Given your other comment, I'll leave this content in the text and in the admonition in both sections. LMK if it is redundant

2023-08-02 14:57 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +<{+api+}/options/struct.CreateCollectionOptions.html>`__.
addressed when I split up and moved the api links

2023-08-02 14:58 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +**Document validation** lets you restrict the types of documents that
no longer relevant since content was moved and reworded

2023-08-02 21:28 UTC, ccho-mongodb requested changes
Thanks for all the changes! I found a few more issues and am not sure the new organization of the headers is ideal.

2023-08-02 21:28 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +   using a custom type, you can avoid repeated serialization code
Question:
Is "custom type" the "type that models your data"? If so, could that be clarified here?

2023-08-02 21:28 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +   and improve your application's performance.
Suggestion:

I think it's slightly unclear what this means and think it would be helpful to clarify.

Does using the Document type require repeated serialization code? I would've expected that you could work in BSON-like documents without repeating serialization code, similar to other drivers. What would the required serialization code look like?

If there isn't repeated serialization code, could the benefit be clarified?

2023-08-02 21:28 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +Document Validation
Resolving since that's outside this PR now.

2023-08-02 21:28 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +  validation rules. To learn more about specifying a validation action, see :manual:`validationAction
Resolving since no longer relevant to this PR. However, to answer your question, it depends on how it's presented. It should not be presented as the only source of information, especially if it does not explain how to use that information.

2023-08-03 17:22 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +MongoDB organizes data in a hierarchal structure, in which data exists as
To me, starting two sentences with MongoDB is a little stiff. I will rework the sentences.

2023-08-03 17:27 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +  ``Client`` instance
added a TODO to link the client options page when it is completed.

2023-08-03 17:33 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +   You must parameterize your ``Collection`` instance by specifying what
Methods like `drop()` and `create_index()` do not manipulate any data, true, but what I was trying to communicate in my response was that to even successfully compile any code that calls the `collection()` method, you need to parameterize the collection while calling `collection()`. So, even to call `drop()` or some other non-CRUD method, you need to parameterize the collection, even if the data is never manipulated in any way.

2023-08-03 17:49 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +You can access a database by calling the following methods on a ``Client``
updated both sections to which this applicable.

2023-08-03 17:52 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +database and collection.
reworded in both applicable sections

2023-08-03 17:53 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +
Now that I inlined the API documentation, this is addressed

2023-08-29 16:01 UTC, ccho-mongodb approved these changes
Looks good to me. Identified a few minor issues and suggestions to address before merging.

2023-08-29 16:01 UTC, ccho-mongodb commented on source/fundamentals/database-collection.txt
> +To learn how to run a database command, see :ref:`rust-run-command`.
Suggestion:

I think this information should be omitted from this page since database commands don't necessarily relate to database or collection operations.

2023-08-29 17:46 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +database contains.
reordered information in these sections + added some explanation for what you can do with collections to the Create a Collection section

2023-08-29 17:48 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +Create a Collection
I agree that it should be moved up, but I think that it should be after "Access a Collection" because that section explains that accessing a collection and inserting data implicitly creates a collection.

2023-08-29 17:54 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +To see a list of collections in a database, call the
Reworded to To see the names of the collections in a database

2023-08-29 17:58 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +   need to access.
also edited in the drop a database section

2023-08-29 18:01 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +.. _addl-info-db-coll:
Yes, thats a mistake. this isnt linked anywhere though, so Ill just remove the anchor

2023-08-29 18:21 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +.. literalinclude:: /includes/fundamentals/code-snippets/db-coll.rs
added in all places that reference `db` in the code

2023-08-29 20:55 UTC, merged

2023-09-27 15:59 UTC, isabelatkinson commented on source/includes/fundamentals/code-snippets/db-coll.rs
> +    let db: mongodb::Database = client.database("test_db");
it's generally not necessary/idiomatic to include type labels in Rust unless a generic type needs to be specified, so I'd suggest removing the `: mongodb::Database` label here (and ditto line 24).