DOCSP-30544: compound operations (crud)
mongodb/docs-rust pull request #20
Opened 2023-08-01 20:47 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30544>
**Staging**
- [page](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30544-compound-crud/fundamentals/crud/compound-operations/) + see LH nav
- [crud landing](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30544-compound-crud/fundamentals/crud/)

build

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-08-02 20:25 UTC, mongoKart requested changes
looking good. some small changes throughout

2023-08-02 20:25 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +- :ref:`Sample Data for Examples <rust-compound-sample-data>`: presents
```suggestion
- :ref:`Sample Data for Examples <rust-compound-sample-data>`: Presents
```

applies to all items in this list

2023-08-02 20:25 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +documents, it returns a ``None`` type.
I: The document does the matching, not the method. Applies to whole page

S:

```suggestion
criteria, the method returns a ``Some`` type. If no documents match,
it returns a ``None`` type.
```

2023-08-02 20:25 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +   If you don't need to find and delete a document in a single
Q: Is there any advantage to calling them separately? Doing other processing between the method calls, maybe? Just don't want to confuse people about which way is preferred.

Applies to other notes on page too.

2023-08-02 20:25 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +the options parameter.
```suggestion
To use default values for each setting, specify the value ``None`` for
the options parameter.
```

Applies to same paragraph in each page section too

2023-08-02 20:25 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +         run for.
```suggestion
         run.
```

Applies in later paragraphs too

2023-08-02 20:25 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +     - | The sort to use when returning results. By default, the driver
```suggestion
     - | The sorting order[?] to use when returning results. By default, the driver
```

Applies to whole page

2023-08-02 20:25 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +.. list-table::
I: Some entries in this table are missing types; others are missing default values. Can you double-check?

Also applies to later tables on page

2023-08-02 20:25 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +         as variables in aggregation expressions. This option is available
I: use active voice

S: Rephrase second sentence in active voice, with who/what is accessing the variables as the subject

Applies to same entry in later tables too

2023-08-02 20:25 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +.. note:: Instantiating Options
S: Delete this note, given the following example

Applies to later sections too

2023-08-02 20:25 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +To learn more about performing the operations mentioned, see the
```suggestion
To learn more about performing the previous operations, see the
```

2023-08-04 19:33 UTC, rustagir commented on source/fundamentals/crud/compound-operations.txt
> +- :ref:`Sample Data for Examples <rust-compound-sample-data>`: presents
I think you and chris followed up about this rule, and it looked like items should be lowercased

2023-08-04 19:34 UTC, rustagir commented on source/fundamentals/crud/compound-operations.txt
> +documents, it returns a ``None`` type.
changed in the three sections

2023-08-04 19:34 UTC, rustagir commented on source/fundamentals/crud/compound-operations.txt
> +   If you don't need to find and delete a document in a single
yes, you risk data changes between calls by separating the calls

2023-08-04 19:38 UTC, rustagir commented on source/fundamentals/crud/compound-operations.txt
> +.. list-table::
I havent been able to locate some of the default values, but i can definitely add types for all of the entries in every table.

2023-08-04 19:45 UTC, rustagir commented on source/fundamentals/crud/compound-operations.txt
> +.. note:: Instantiating Options
Don't you think mentioning the design pattern might be useful to users who see the example and dont know whats going on?

2023-08-04 20:08 UTC, mongoKart commented on source/fundamentals/crud/compound-operations.txt
> +.. note:: Instantiating Options
Sure, that makes sense. What do you think about taking it out of an admonition and just letting it be text?

2023-08-04 20:08 UTC, mongoKart approved these changes
LGTM + 1 suggestion

2023-08-07 15:06 UTC, merged

2023-09-27 17:56 UTC, kevinAlbs reviewed
LGTM with suggestions.

2023-09-27 17:56 UTC, kevinAlbs commented on source/includes/fundamentals/code-snippets/crud/compound.rs
> +    let _res = my_coll.find_one_and_delete(filter, opts).await?;
Suggest removing `_` prefix from example snippet. I expect user may use `res` to check result. Same comment applies to other `_res` declarations.

2023-09-27 17:56 UTC, kevinAlbs commented on source/includes/fundamentals/code-snippets/crud/compound.rs
> +    println!("Deleted document:\n{}", serde_json::to_string_pretty(&res).unwrap());
`unwrap` panics on error. Suggest avoiding `unwrap` for consistent error handling.

Suggest printing the `Option<Document>` directly:

```
println!("Deleted document:\n{:?}", res);
```

Same comment applies to other calls of `unwrap`.