DOCSP-30526: network compression
mongodb/docs-rust pull request #21
Opened 2023-08-02 18:31 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30526>
Staging:
- [NC page](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30526-network-comp/fundamentals/connections/network-compression/)
- [connections landing page](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30526-network-comp/fundamentals/connections/)

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?

2023-08-02 21:41 UTC, jordan-smith721 requested changes
Looks good, just a few suggestions

2023-08-02 21:41 UTC, jordan-smith721 commented on source/fundamentals/connections/network-compression.txt
> +To enable compression on your connection in a connection string, specify
Suggestion: Simplify to avoid the double "connection" so close together

```suggestion
To enable compression using a connection string, specify
```

2023-08-02 21:41 UTC, jordan-smith721 commented on source/fundamentals/connections/network-compression.txt
> +To enable compression using within your ``ClientOptions`` instance, set
```suggestion
To enable compression within your ``ClientOptions`` instance, set
```

2023-08-02 21:41 UTC, jordan-smith721 commented on source/fundamentals/connections/network-compression.txt
> +the ``compressors`` field and pass the options when creating a client.
```suggestion
the ``compressors`` field, then pass the options when creating a client.
```

2023-08-02 21:41 UTC, jordan-smith721 commented on source/fundamentals/connections/network-compression.txt
> +For the compressors that have a ``level`` field, set the field to
```suggestion
For the compressors that have a ``level`` field, set the value to
```

2023-08-02 21:41 UTC, jordan-smith721 commented on source/fundamentals/connections/network-compression.txt
> +compressor to your ``mongodb`` dependency:
After reading the rest of the page - I think it might be good to add some kind of note here stating that you can also add more than one feature flag to the list

2023-08-02 21:41 UTC, jordan-smith721 commented on source/fundamentals/connections/network-compression.txt
> +.. note::
It might be useful to have this note in the Connection String section as well since some readers may miss it if they don't read this far, but the example there shows using multiple as well.

2023-08-08 14:49 UTC, rustagir commented on source/fundamentals/connections/network-compression.txt
> +To use a compressor, add the relevant feature flag to your
We can just call them compressors throughout the page. I think that the compressor features employ certain algorithms, but the feature itself can be called a compressor

2023-08-08 14:52 UTC, rustagir commented on source/fundamentals/connections/network-compression.txt
> +To enable compression using within your ``ClientOptions`` instance, set
oops

2023-08-08 14:54 UTC, rustagir commented on source/fundamentals/connections/network-compression.txt
> +compressor to your ``mongodb`` dependency:
moving the note from the end of the page to this section!

2023-08-08 14:55 UTC, rustagir commented on source/fundamentals/connections/network-compression.txt
> +.. note::
moved the note up to a more visible location

2023-08-08 16:27 UTC, jordan-smith721 approved these changes
LGTM

2023-08-08 16:29 UTC, merged

2023-09-27 15:07 UTC, kevinAlbs reviewed
LGTM. Commented with a suggested minor change.