DOCSP-31848: document validation
mongodb/docs-rust pull request #22
Opened 2023-08-02 19:25 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-31848>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-31848-doc-validation/fundamentals/document-validation/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?

2023-09-08 08:00 UTC, ccho-mongodb requested changes
Great start!

The main issue I currently have with the content is the lack of connection between "document validation" used in this PR and "schema validation" used by the Server manual. If using two distinct terms for the same concept is required, then I think the similarities and differences need to be clarified.

2023-09-20 17:27 UTC, norareidy commented on source/fundamentals/document-validation.txt
> +   field to ``true`` in the write method's options parameter.
I didn't include the full list of scenarios in which you would need bypass_document_validation (both operations when level is "strict", insert when level is "moderate", etc) but I added that you would only need to use it if your validation_level settings do not already exempt the operation from validation.

2023-09-20 17:47 UTC, norareidy commented on source/fundamentals/document-validation.txt
> +**document validation** for your MongoDB collections.
All references to document validation are now schema validation -- wasn't necessary to use a different term

2023-09-20 17:49 UTC, norareidy commented on source/fundamentals/document-validation.txt
> +validation rules.
Now that "document validation" is no longer used, let me know if there is still more explanation needed about the connection between server and driver implementation

2023-09-20 17:54 UTC, norareidy commented on source/fundamentals/document-validation.txt
> +  the validation rules to existing documents during update operations.
Used slightly different wording but made this change

2023-09-20 17:55 UTC, norareidy commented on source/fundamentals/document-validation.txt
> +  raise an error if a write operation violates the validation rule.
Added the `Error` value

2023-09-20 19:04 UTC, norareidy commented on source/fundamentals/document-validation.txt
> +   :emphasize-lines: 6-10
I've added a section about the JSON schema

2023-09-24 02:53 UTC, ccho-mongodb approved these changes
Looks great. There are a few issues to address and some suggestions, but approving since resolving them should be straightforward. Feel free to reach out for another review if you think it would be helpful.

2023-09-24 02:53 UTC, ccho-mongodb commented on source/fundamentals/schema-validation.txt
> +   You may need to perform write operations that violate a collection's
Issue:
Vale identified a style guide issue. I think this introduction to a new scenario is confusing due to presenting two conditions.

Suggestion:

I think in this case, introducing how to "Bypass Schema Validation" as presented in the title of the callout first could work better than explaining the conditions under which they might need to accomplish it.
E.g.

"To bypass a collection's validation rules, set the bypass_document_validation field to true in the write method's options parameter. This ignores any validation rules on the collection and any exemptions of them defined by the validation_level.
...
"

2023-09-24 02:53 UTC, ccho-mongodb commented on source/fundamentals/document-validation.txt
> +   :emphasize-lines: 6-10
Suggestion:
I think the highlighted lines are still slightly confusing since they do not correspond to anything mentioned in the directly preceding content. I think that either an explanation of why those particular lines are highlighted or omitting the highlighting could be less confusing.

2023-09-24 02:53 UTC, ccho-mongodb commented on source/fundamentals/schema-validation.txt
> +- :manual:`Specify JSON Schema </core/schema-validation/specify-json-schema/#std-label-schema-validation-json>`
Suggestion:
I think it could be good to use the titles of the pages linked, e.g.
```suggestion
- :manual:`Specify JSON Schema Validation </core/schema-validation/specify-json-schema/#std-label-schema-validation-json>`
```

2023-09-24 02:53 UTC, ccho-mongodb commented on source/fundamentals/schema-validation.txt
> +- :manual:`validationAction </reference/command/collMod/#mongodb-collflag-validationAction>`
Suggestion:
I think it could be helpful to limit the number of links external to the driver documentation, especially when they point to adjacent sections on a page.
These three links could be replaced by a single one, e.g.
```
- :manual: `Validation operations for the collMod command </reference/command/collMod/#validate-documents>`
```

2023-09-24 02:53 UTC, ccho-mongodb commented on source/fundamentals/schema-validation.txt
> +guide, see the following documentation:
Suggestion:
Similar to [this comment from another PR](https://github.com/mongodb/docs-rust/pull/28#discussion_r1335054083), I think it would be more concise to omit mention of "discussed" since it implies a conversation.

2023-09-24 02:53 UTC, ccho-mongodb commented on source/fundamentals/schema-validation.txt
> +To set validation rules with the ``validator()`` method, pass a JSON schema
Issue:
From the style guide entry on [using](https://www.mongodb.com/docs/meta/style-guide/terminology/alphabetical-terms/#u):

> by using with Use by using, or recast the sentence. Don't use using (alone) or with. By using is easier for worldwide audiences to understand.

Suggestion:

```suggestion
To set validation rules by using the ``validator()`` method, pass a JSON schema
```

Alternatively, reword the sentence which I think follows a similar structure to previously written sections such as "Implement Schema Validation":

"You can set validation rules by passing your JSON schema to the validator() method."

2023-09-24 02:53 UTC, ccho-mongodb commented on source/fundamentals/schema-validation.txt
> +- The ``validation_action()`` method specifies that the driver should
Issue:
Vale reported a style guide issue.

Suggestion:
I think specifying the exact behavior resolves this, e.g.

"The validation_action() method specifies whether the driver raises an Error when a write operation violates a validation rule."

2023-09-25 16:12 UTC, merged