Docsp 30532 stable api
mongodb/docs-rust pull request #25
Opened 2023-08-22 17:54 UTC by pierwill

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30532>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30532-stable-api/fundamentals/stable-api/

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-08-24 20:30 UTC, rustagir requested changes
Good first pass! Looking forward to seeing the next one.

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +   The {+stable-api+} feature requires MongoDB Server 5.0 or later.
```suggestion
   To use {+stable-api+} feature, you must connect to a deployment running MongoDB Server version 5.0 or later.
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +behaviors compatible with the **API version** you specify. An API
```suggestion
The {+stable-api+} feature forces the server to run operations with
behaviors that are compatible with the **API version** you specify. An API
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +When you use the Stable API feature with an official MongoDB driver, you
```suggestion
When you use the {+stable-api+} feature with an official MongoDB driver, you
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +When you use the Stable API feature with an official MongoDB driver, you
```suggestion
When you use the Stable API feature with the {+driver-short+}, you
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +:manual:`{+stable-api+} </reference/stable-api/>`.
S: we are trying to use the "see xxx in the Server manual" wherever applicable!
```suggestion
To learn more about the commands that the server covers, see
:manual:`{+stable-api+} </reference/stable-api/>` in the Server manual.
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +The ``ServerApi`` struct contains your :ref:`server API version and options <rust-stable-api-options>`.
S: Only use the name of the type/method. And, make links more clear
```suggestion
To specify an API version, define a ``ServerApi`` struct and set the ``server_api`` field
of your ``ClientOptions`` instance to this struct.
The ``ServerApi`` struct contains your server API version and options.
To learn more about the options, see the :ref:`Modify Behavior <rust-stable-api-options>` section of this guide.
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +https://docs.rs/mongodb/latest/mongodb/options/struct.ClientOptions.html#structfield.server_api
Did you mean to include this line?

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +After you specify an API version, the client runs operations that are compatible with the API version for the duration of your connection.
S: remove redundancy
```suggestion
After you specify an API version, the client runs operations that are compatible with the API version.
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +   The {+driver-long+} currently only supports ``mongodb::options::ServerApiVersion::V1``.
```suggestion
   The {+driver-long+} currently only supports {+stable-api+} version 1.
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +You can further modify the behavior of the {+stable-api+} feature by setting fields on the ``ServerApi`` type.
```suggestion
You can modify the behavior of the {+stable-api+} feature by setting fields in the ``ServerApi`` struct.
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +While the fields can be set manually, prefer using the ``ServerApi`` ``builder()`` function.
S: avoid passive voice
```suggestion
While you can set the fields in a ``ServerApi`` struct manually, you can use the builder design pattern to define the struct more efficiently.
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +   :widths: 30 70
S: reformat the table here to be like the one used in the [Insert guide](https://github.com/mongodb/docs-rust/blob/c9205ba3b55ea5443af10abfc0129c49cb34c807/source/fundamentals/crud/write-operations/insert.txt#L96-L125)

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +     - | The API version to use.
```suggestion
     - | The {+stable-api+} version to use.
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +This example specifies for the server to perform the following actions:
```suggestion
This example enables the {+stable-api+} feature with the following specifications:
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +- Return errors for deprecated features
```suggestion
- Uses {+stable-api+} version 1
- Returns errors for features that aren't part of version 1
- Returns errors for deprecated features
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +API Documentation:
```suggestion
To learn more about any of the methods or types discussed in this
guide, see the following API Documentation:
```

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +- `SetStrict() <{+api+}/mongo/options#ServerAPIOptions.SetStrict>`__
I: these links are all broken
S: update the links to use the Rust API documentation

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +   :end-before: end-stable-api
S: constrain this include to start at "let server_api = ..." and end in the line that creates the client

2023-08-24 20:30 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +   :end-before: end-stable-api-behavior
S: constrain this include to start at the options instantiation and end when the client is created. Also, it looks like this code example doesnt include the builder method for `deprecation_errors`

2023-08-25 15:50 UTC, pierwill commented on source/fundamentals/stable-api.txt
> +https://docs.rs/mongodb/latest/mongodb/options/struct.ClientOptions.html#structfield.server_api
Ah! Nope.

2023-08-28 20:49 UTC, rustagir requested changes
Great job revising the PR! This is almost ready, but since its your first PR here, I'd like to take another look before you merge!

2023-08-28 20:49 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +   servers you are connecting to support this feature.
S: let's change this to an important admonition

```suggestion
.. important::

   To use the {+stable-api+} feature, you must connect to a deployment running MongoDB Server version 5.0 or later.

   You should only use the {+stable-api+} feature if all the MongoDB
   servers you are connecting to support this feature.
```

2023-08-28 20:49 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +When you use the Stable API feature with an official MongoDB driver, you
It's only a suggestion, but making sure you saw this because I didn't see any changes in the copy!

2023-08-28 20:49 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +{+stable-api+} version and connects to a server.
S: reword so it doesnt sound like the Client is the thing that is setting the stable api version

Perhaps something like:
```suggestion
The following example sets the {+stable-api+} version when instantiating a ``Client`` 
instance and connects to a server.
```

2023-08-28 20:49 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +- `ServerAPI() <{+api+}/options/struct.ServerApi.html>`__
S: since this is not a method

```suggestion
- `ServerAPI <{+api+}/options/struct.ServerApi.html>`__
```

2023-08-28 20:49 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +- `ServerApiVersion <{+api+}/options/enum.ServerApiVersion.html>`__
S: also link `with_options()`

2023-08-28 20:49 UTC, rustagir commented on source/fundamentals/stable-api.txt
> +   The {+driver-long+} currently only supports {+stable-api+} version 1.
```suggestion
   The {+driver-long+} currently supports only {+stable-api+} version 1.
```

2023-08-28 20:49 UTC, rustagir commented on source/includes/fundamentals/code-snippets/stable-api-behavior.rs
> +    let client = Client::with_options(client_options)?;
S: since the code snippets aren't long or complicated, let's remove the code comments. Also applies to the other file

2023-08-29 14:25 UTC, rustagir approved these changes
LGTM!

2023-08-29 14:30 UTC, merged

2023-09-26 13:29 UTC, kevinAlbs commented on source/fundamentals/stable-api.txt
> +       | Default: ``ServerAPIVersion1``
`version` is required. Suggest removing:

> Default: ``ServerAPIVersion1``

2023-09-26 13:29 UTC, kevinAlbs commented on source/fundamentals/stable-api.txt
> +       | Type: ``ServerAPIVersion``
Suggest replacing `ServerAPIVersion` with `ServerApiVersion` to match Rust driver API casing.

2023-09-26 13:29 UTC, kevinAlbs commented on source/fundamentals/stable-api.txt
> +       | Specified with the ``ServerAPIVersion`` enum.
Suggest replacing `ServerAPIVersion` with `ServerApiVersion` to match Rust driver API casing.

2023-09-26 13:29 UTC, kevinAlbs commented on source/fundamentals/stable-api.txt
> +- `ServerAPI <{+api+}/options/struct.ServerApi.html>`__
Suggest replacing `ServerAPI` with `ServerApi` to match Rust driver API casing.