DOCSP-30537: cursor fundamentals
mongodb/docs-rust pull request #28
Opened 2023-09-01 16:07 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30537>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30537-cursor/fundamentals/crud/read-operations/cursor/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?

2023-09-14 17:01 UTC, ccho-mongodb requested changes
Looks pretty good. Added suggestions and issues. Would like to take another look at the revision specifically for the structural changes.

2023-09-23 19:26 UTC, ccho-mongodb requested changes
Great work!
I think its nearly there; I left a few issues and suggestions to address.

Also, if possible, please try to address Vale comments before requesting a review. If the Vale rules seem invalid, please add comments explaining why you think they are false positives.

2023-09-23 19:26 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/cursor.txt
> +code than the built-in pattern, since you can call a variety of useful
Issue:
1) Vale reported avoiding "useful".
2) I think the subordinate clause (after the comma) does not negate the preceding clause and therefore should not be separated by a comma.

Suggestion:
I think it would be better to avoid subjective opinion and general terms. Instead, I think it could be helpful to identify a characteristic about the functions in the Stream trait that helps make the code more concise.

2023-09-23 19:26 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/cursor.txt
> +combinator functions on the cursor provided by the ``Stream`` trait.
Issue:
I wasn't able to find a definition of "combinator functions" through a Google search. 

Suggestion:
If this terminology is correct, I think it would be helpful to provide a definition.
Otherwise, I think it would be helpful to avoid creating new terminology.

2023-09-23 19:26 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/cursor.txt
> +  a ``Result<Option<T>>`` type, which is easier to use with the ``?``
Suggestion:
I think it would be good to avoid subjective opinions such as "easier". I think this statement also doesn't mention what it means to use it with the ? operator.

I think omitting he clause starting from the comma would address these.

2023-09-23 19:26 UTC, ccho-mongodb commented on source/includes/fundamentals/code-snippets/crud/cursor.rs
> +    println!("\nOutput from next() iteration:");
I think this is still present in lines [29](https://github.com/mongodb/docs-rust/pull/28/files#diff-1cd341276e351622bcccfeac66ea9ff68b885f97007e60e9c3e4756fd28e60bbR29) and [44](https://github.com/mongodb/docs-rust/pull/28/files#diff-1cd341276e351622bcccfeac66ea9ff68b885f97007e60e9c3e4756fd28e60bbR44) of cursor.rs.


If you want to separate the two results with a line break, placing a println!() between the two results should be sufficient as mentioned.

Not a necessary change if you strongly believe it's better to keep as is.

2023-09-25 21:19 UTC, norareidy commented on source/fundamentals/crud/read-operations/cursor.txt
> +code than the built-in pattern, since you can call a variety of useful
I reworded the description of the Stream trait benefits, let me know if it seems like a sufficient explanation!

2023-09-25 21:19 UTC, norareidy commented on source/fundamentals/crud/read-operations/cursor.txt
> +combinator functions on the cursor provided by the ``Stream`` trait.
The Rust API docs use the term but I've taken it out

2023-09-25 23:20 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/cursor.txt
> +either the cursor is exhausted or the cursor receives the next batch.
Issue:

I think the last part of this sentence, "the cursor receives the next batch", is not a consequence of calling advance(), but rather something it triggers.

Suggestion:

I think it could still be [helpful to explain the cursor's exhausted state](https://github.com/mongodb/docs-rust/pull/28#discussion_r1335051022) and not just the local buffer's exhausted state.

E.g.

The cursor requests the next batch when it reaches the end of a batch of results. 
If the cursor has no more results to return, it is *exhausted*, which means that it has returned all the results and that you cannot use it anymore.

2023-09-25 23:20 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/cursor.txt
> +To learn more about the methods and types discussed in this
No change necessary, but I think this should probably match the format of the sentence under "Additional Information" just for consistency.

2023-09-25 23:48 UTC, ccho-mongodb approved these changes
LGTM!
Could you resolve the merge conflicts and then address the few additional suggestions before merging? Thanks.

2023-09-25 23:48 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/cursor.txt
> +``StreamExt`` provides numerous functions that combine operations and
Suggestion:

This is a little tough to explain, but I think the preposition needs to be "to" in order to imply a goal rather than the action it takes. I think while the functions can combine operations, they don't perform the consolidation of code. Instead, you're responsible for selecting the right ones to perform the consolidation.

"numerous functions to [help you] combine operations", "numerous functions to [help you] consolidate code"
vs
"numerous functions that combine operations", "numerous functions that consolidate code"


```suggestion
``StreamExt`` provides numerous functions to combine operations and
```

2023-09-25 23:48 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/cursor.txt
> +code than the built-in pattern, since you can call a variety of useful
Looks good!

2023-09-25 23:48 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/cursor.txt
> +combinator functions on the cursor provided by the ``Stream`` trait.
Ah it looks like they're called [combinators](https://learning-rust.github.io/docs/combinators/). If you think the audience would be familiar with what they are, feel free to include without a definition.

2023-09-25 23:48 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/cursor.txt
> +  ``Result<Vec<T>>`` type, which makes it easier to use with the
Suggestion:
I think this might be another instance of [this comment](https://github.com/mongodb/docs-rust/pull/28#discussion_r1335056751). I think it could be good to address this similarly.

2023-09-25 23:48 UTC, ccho-mongodb commented on source/fundamentals/crud/read-operations/cursor.txt
> +
Suggestion:

Since you removed the leading "\n" character, I think the output lacks this additional line break. As mentioned in [this suggestion](https://github.com/mongodb/docs-rust/pull/28#discussion_r1335057126), you could add a separate println!() between the printong of the two method call results. Otherwise, I would make the output resemble output from the code.

Applies to all instances.

2023-09-26 14:17 UTC, norareidy commented on source/fundamentals/crud/read-operations/cursor.txt
> +``StreamExt`` provides numerous functions that combine operations and
Ah that makes sense, changed!

2023-09-26 14:32 UTC, norareidy commented on source/fundamentals/crud/read-operations/cursor.txt
> +
Since I added the println on line 28 of the cursor.rs file, it seems to be printing the correct way when I run it -- but I'll make sure all the outputs match what is actually printed

2023-09-26 20:28 UTC, kevinAlbs approved these changes
LGTM with two small suggested code changes.

2023-09-26 20:28 UTC, kevinAlbs commented on source/includes/fundamentals/code-snippets/crud/cursor.rs
> +    let _opts: FindOptions = FindOptions::builder()
```suggestion
    let opts : FindOptions = FindOptions::builder()
```

Suggest removing `_` prefix.

2023-09-26 20:28 UTC, kevinAlbs commented on source/includes/fundamentals/code-snippets/crud/cursor.rs
> +        println!("{:?}", cursor.deserialize_current()?);
```suggestion
        println!("{}", cursor.deserialize_current()?);
```

Suggest using empty format `{}` for consistency with other examples printing a `Document`.

2023-09-27 14:29 UTC, merged