DOCSP-30530: enterprise auth
mongodb/docs-rust pull request #29
Opened 2023-09-07 14:52 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30530>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30530-enterprise-auth/fundamentals/enterprise-auth/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?

2023-09-12 17:40 UTC, pierwill requested changes

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +The driver supports only the :ref:`LDAP (Plain) <rust-LDAP>`
```suggestion
The {+driver-short+} supports only the :ref:`LDAP (PLAIN) <rust-LDAP>`
```

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +authentication mechanism. To learn how to use other methods to
S: Make a new graf for Kerberos, and mention that it is not supported by the driver.

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +Edition. When you connect to MongoDB, you can use an authentication
S: Consider removing "you ~can~" throughout and use imperative instead.

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +   This authentication mechanism sends the password to the server in
```suggestion
   This authentication mechanism sends your password to the server in
```

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +   plaintext, so you should use this mechanism only after enabling TLS
```suggestion
   plaintext. Only use this mechanism only after enabling TLS
```

2023-09-12 17:40 UTC, pierwill commented on source/includes/fundamentals/code-snippets/enterprise-auth.rs
> +    let scram_sha_256_cred = Credential::builder()
```suggestion
    let plain_cred = Credential::builder()
```

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +``AuthMechanism::Plain``. This example specifies the
```suggestion
``AuthMechanism::Plain`` and pass it to client_options.builder. This example specifies the
```

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +   the ``Credential`` struct defaults to this database name, so you do
```suggestion
   the ``Credential`` struct defaults to ``$external``, so you do
```

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +You can alternatively authenticate by using a connection string URI by
```suggestion
Alternatively, you can authenticate by using a connection string URI by
```

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +This example shows how to specify this authentication mechanism in
```suggestion
This example shows how to specify the authentication mechanism in
```

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +   authenticates using the PLAIN Simple Authentication and Security Layer
S: Consider moving up. And maybe something more clear, like: "The LDAP mech is called PLAIN because..."

2023-09-12 17:40 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +guide, see the following API Documentation:
```suggestion
guide, see the following Rust API Documentation:
```

2023-09-22 17:55 UTC, rustagir commented on source/fundamentals/enterprise-auth.txt
> +Edition. When you connect to MongoDB, you can use an authentication
Will try to implement where it sounds natural

2023-09-22 18:04 UTC, rustagir commented on source/fundamentals/enterprise-auth.txt
> +guide, see the following API Documentation:
seems self-explanatory as is, plus sometimes this section links to other documentation than the driver, such as in [this PR](https://github.com/mongodb/docs-rust/pull/28/files)

2023-09-27 17:36 UTC, pierwill approved these changes

2023-09-27 17:36 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +because the mechanism authenticates by using the PLAIN Simple Authentication and
```suggestion
because the mechanism uses the PLAIN Simple Authentication and
```

2023-09-27 17:36 UTC, pierwill commented on source/fundamentals/enterprise-auth.txt
> +
S: Maybe a link to https://www.mongodb.com/docs/manual/reference/connection-string/ .

2023-09-28 18:46 UTC, kevinAlbs approved these changes
LGTM with suggested changes applied.

2023-09-28 18:46 UTC, kevinAlbs commented on source/fundamentals/enterprise-auth.txt
> +authentication mechanism.
```suggestion
The {+driver-short+} supports the :ref:`LDAP (PLAIN) <rust-LDAP>`
enterprise authentication mechanism.
```

Suggest removing "only" and clarifying this applies to "enterprise". The non-enterprise authentication mechanisms are an available alternative (SCRAM + X509).

2023-09-28 18:46 UTC, kevinAlbs commented on source/includes/fundamentals/code-snippets/enterprise-auth.rs
> +        .mechanism(AuthMechanism::Plain)
```suggestion
        .mechanism(AuthMechanism::Plain)
        .source("$external".to_string())
```

Suggest adding `$external` source. I expect it is needed to authenticate with LDAP. Use of `$external` is shown in the Java docs: https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/enterprise-auth/

2023-09-28 18:46 UTC, kevinAlbs commented on source/fundamentals/enterprise-auth.txt
> +   let uri = "mongodb://<username>:<password>@<hostname>/?authMechanism=PLAIN";
```suggestion
   let uri = "mongodb://<username>:<password>@<hostname>/?authSource=$external&authMechanism=PLAIN";
```

Use of `$external` is shown in the Java docs: https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/enterprise-auth/

2023-09-29 18:16 UTC, merged