DOCSP-30559: compatibility
mongodb/docs-rust pull request #3
Opened 2023-07-14 20:33 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30559>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30559-compat/compatibility/

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-07-14 21:43 UTC, mongoKart requested changes
nice. a couple small things

2023-07-14 21:43 UTC, mongoKart commented on source/includes/language-compatibility-table-rust.rst
> +The MongoDB Rust driver requires Rust 1.57 or later.
S: Source constant

Applies throughout

2023-07-14 21:43 UTC, mongoKart commented on source/includes/mongodb-compatibility-table-rust.rst
> +   * - 2.3 [#2.2-limitation]_
Q: Confirming this should point to the same footnote as 2.2

2023-07-14 21:43 UTC, mongoKart commented on source/includes/mongodb-compatibility-table-rust.rst
> +The Rust driver is not compatible with MongoDB server versions older than 3.6.
```suggestion
The Rust driver is not compatible with MongoDB Server versions older than 3.6.
```

2023-07-14 21:43 UTC, mongoKart commented on source/index.txt
> +each driver version, see :ref:`rust-compatibility`.
I: This sentence is a little hard to parse (and contains the word "version" four times, which might be a record). Removed "recommended" because I don't think that page actually recommends anything.

```suggestion
To see the versions of MongoDB Server and Rust that are compatible with
each version of the {+driver-short+}, see :ref:`rust-compatibility`.
```

2023-07-14 21:43 UTC, mongoKart commented on source/index.txt
> +each driver version, see :ref:`rust-compatibility`.
The above has "see" twice, which I don't love. Could also do this:

```suggestion
For more information about the {+driver-short+}'s compatibility with 
different versions of MongoDB Server and the Rust language, see
:ref:`rust-compatibility`.
```

2023-07-17 14:03 UTC, rustagir commented on source/includes/mongodb-compatibility-table-rust.rst
> +   * - 2.3 [#2.2-limitation]_
I'm going to rework these to be reusable.

2023-07-17 14:09 UTC, rustagir commented on source/index.txt
> +each driver version, see :ref:`rust-compatibility`.
good call

2023-07-18 15:04 UTC, mongoKart approved these changes
LGTM + some link suggestions!

2023-07-18 15:04 UTC, mongoKart commented on source/includes/mongodb-compatibility-table-rust.rst
> +   :manual:`OCSP </core/security-transport-encryption/>`.
S: Link straight to OCSP

```suggestion
   :manual:`OCSP </core/security-transport-encryption/#ocsp--online-certificate-status-protocol->`.
```

2023-07-18 15:04 UTC, mongoKart commented on source/includes/mongodb-compatibility-table-rust.rst
> +   :manual:`OCSP </core/security-transport-encryption/>`,
S: Link straight to OCSP

```suggestion
   :manual:`OCSP </core/security-transport-encryption/#ocsp--online-certificate-status-protocol->`,
```

2023-07-18 15:04 UTC, mongoKart commented on source/includes/mongodb-compatibility-table-rust.rst
> +   :manual:`OCSP </core/security-transport-encryption/>`,
S: Link straight to OCSP

```suggestion
   :manual:`OCSP </core/security-transport-encryption/#ocsp--online-certificate-status-protocol->`,
```

2023-07-18 15:04 UTC, mongoKart commented on source/includes/mongodb-compatibility-table-rust.rst
> +   :atlas:`Serverless Instances </reference/serverless-instance-limitations>`.
S: Don't link to limitations page (double check the link i suggested)

```suggestion
   :atlas:`Serverless Instances </create-database-deployment/#serverless-instances>`.
```

2023-07-18 15:18 UTC, merged