DOCSP-30561 Performance
mongodb/docs-rust pull request #30
Opened 2023-09-12 17:01 UTC by pierwill

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-09-18 19:18 UTC, rustagir requested changes

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +It constructs and tears down a ``Client`` instance with every request.
S: Improve the introduction of this code example by actually describing what it contains at a more specific level:
Something like:

"Creating a new ``Client`` instance for each request results in slower performance. The following code defines a method that instantiates a new ``Client`` before performing other operations:"

However, I'm not sure it serves users to include content on this page that describes what NOT to do. It might be confusing and a user quickly reading the page might copy the wrong snippet. Happy to talk more about this, but my suggestion is to only describe the downsides of creating a new client but only show the code snippet for the more efficient best practice code.

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +allowing many requests to share the same client:
S: same comment as above, improve this code introduction

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +A ``Client`` instance is bound to the instance of the ``tokio`` or ``async-std`` runtime in which it was created.
S; avoid passive voice

```suggestion
A ``Client`` instance is bound to the instance of the ``tokio`` or ``async-std`` runtime in which you created it.
```

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +Attempting to execute operations on a different runtime instance can cause incorrect behavior and unpredictable failures.
```suggestion
If you use a ``Client`` instance to execute operations on a different runtime, you might experience unexpected behavior or failures.
```

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +as the ``tokio::test`` or ``async_std::test`` helper macros create a new runtime for each test.
```suggestion
If you are using the ``test`` helper macro from the ``tokio`` or ``async_std`` crate to test your application, you might accidentally run operations on a different runtime than you intended. This is because these helper macros 
create a new runtime for each test.
```

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +
I: This code needs an introduction that explains why it will fail, etc.
S: describe the code before including it

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +or bundle the runtime along with the ``Client`` instance and don't use the test helper macros.
```suggestion
To avoid this issue, you can take the following approaches:
- Create a new ``Client`` instance for every ``async`` test
- Attach the runtime to the ``Client`` instance without using the ``test`` helper macros
```

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +   :dedent:
I: code snippets need introductions
S: add introductions for each

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +
I: needs introduction
S: add intro "The following code xxx"

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +as the driver is designed to work well in such situations.
```suggestion
If you can run parallel data operations, creating asynchronous, concurrent tasks achieves maximum performance.
```

2023-09-18 19:18 UTC, rustagir commented on source/fundamentals/performance.txt
> +- `Arc <https://doc.rust-lang.org/std/sync/struct.Arc.html>`__
S: add a heading for API documentation

2023-09-18 19:18 UTC, rustagir commented on source/includes/fundamentals/code-snippets/performance-new-client.rs
> +    CLIENT.list_database_names(None, None).await?;
I; typo
```suggestion
    let client = Client::with_uri_str("mongodb://example.com").await?;
    client.list_database_names(None, None).await?;
```

2023-09-20 18:01 UTC, rustagir requested changes
this is moving in the right direction. Mostly suggestions for clarity

2023-09-27 19:36 UTC, rustagir approved these changes
approving with some suggestions. let me know if you want me to take another look anyways!

2023-09-27 19:36 UTC, rustagir commented on source/fundamentals/performance.txt
> +The ``Client`` type is safe for concurrent use by multiple threads.
S; combine sentences
```suggestion
You can use the same ``Client`` instance to perform multiple tasks, as the ``Client`` type is safe for concurrent use by multiple threads.
```

2023-09-27 19:36 UTC, rustagir commented on source/fundamentals/performance.txt
> +the following code creates a new ``Client`` instance for each test run with ``tokio::test``.
```suggestion
the following code creates a new ``Client`` instance for each test run by using the ``tokio::test`` macro.
```

2023-09-27 19:36 UTC, rustagir commented on source/fundamentals/performance.txt
> +As an example of the latter,
```suggestion
Implementing the second strategy,
```

2023-09-27 19:36 UTC, rustagir commented on source/fundamentals/performance.txt
> +This ensures there is no unintended interaction between runtimes.
```suggestion
As an example of the latter,
the following code creates a new ``Client`` instance for each test run with ``tokio::test``, 
ensuring that there is no unintended interaction between runtimes:
```

2023-09-27 19:36 UTC, rustagir commented on source/fundamentals/performance.txt
> +which allows you to execute many requests by using same client:
S: style guidance around "execute": https://www.mongodb.com/docs/meta/style-guide/terminology/terms-for-global-audience/#:~:text=Windows%20is%20discontinued.-,execute,-v

Also replace elsewhere in the page

```suggestion
which allows you to perform many operations by using same client:
```

2023-09-27 19:36 UTC, rustagir commented on source/fundamentals/performance.txt
> +If you can run parallel data operations, creating asynchronous, concurrent tasks achieves maximum performance.
```suggestion
If you can run parallel data operations, you can optimize performance by running asynchronous, concurrent tasks.
```

2023-09-27 19:36 UTC, rustagir commented on source/fundamentals/performance.txt
> +.. TODO link to Async page when done
S: structure this section like the other fundamentals pages by having the Additional Information heading with links, and then the API Documentation subheading. Under the addtl information heading. you could link to the runtimes page, https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30545-serialization/fundamentals/connections/connection-guide/#mongodb-client,

2023-10-03 20:20 UTC, kevinAlbs requested changes

2023-10-03 20:20 UTC, kevinAlbs commented on source/includes/fundamentals/code-snippets/performance-parallel.rs
> +        collection.insert_one(some_data)
Compiling results in this error:

```rust
error[E0061]: this method takes 2 arguments but 1 argument was supplied
    --> src/main.rs:103:24
     |
103  |             collection.insert_one(some_data)
     |                        ^^^^^^^^^^----------- an argument is missing
     |
```

Suggested snippet:

```rust
    for i in 0..5 {
        let client_ref = client.clone();
        let somedata_ref = some_data.clone();

        task::spawn(async move {
            let collection = client_ref
                .database("items")
                .collection::<Document>(&format!("coll{}", i));

            collection.insert_one(somedata_ref, None).await
        });
    }
```

2023-10-03 20:20 UTC, kevinAlbs commented on source/includes/fundamentals/code-snippets/perf.rs
Remove unused file? Appears to be duplicate of performance.rs.

2023-10-03 20:20 UTC, kevinAlbs commented on source/fundamentals/performance.txt
> +Runtime
A similar `Runtime` section is included in the [Performance - MongoDB Rust Driver](https://mongodb.github.io/mongo-rust-driver/manual/performance.html#runtime) page. I expect this section is less valuable to new users of the driver, as this is intended for testing.

Consider removing the `Runtime` section. Alternatively: move it below the `Parallelism` section. I expect the `Parallelism` is more relevant to users.

2023-10-03 20:20 UTC, kevinAlbs commented on source/includes/fundamentals/code-snippets/performance-new-runtime.rs
Remove unused file? Appears unreferenced.

2023-10-05 17:20 UTC, kevinAlbs approved these changes

2023-10-05 18:36 UTC, merged