DOCSP-30562: operation error handling
mongodb/docs-rust pull request #35
Opened 2023-09-25 18:24 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30562>
Staging:
- https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30562-ops-error-handling/op-error-handling/
- https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30562-ops-error-handling/#operation-error-handling

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST? > ignore the error, it is being handled in a different PR
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?

2023-09-25 20:34 UTC, norareidy requested changes
Great work, just a few suggestions from me!

2023-09-25 20:34 UTC, norareidy commented on source/op-error-handling.txt
> +you try to execute a write operation.
S:

1. This sentence is a little wordy and repeats "when," you could change to something like:
"... the value of the ``kind`` field is ``Write``. This value applies when an error occurs during a write operation."

2. style guide is weird about "execute," could replace with "run" (or rephrased like the suggestion above)

2023-09-25 20:34 UTC, norareidy commented on source/op-error-handling.txt
> +Most of the exceptions that the driver throws when executing operations
S: style guide prefers "generate" to "throw" (in the "Write for a Global Audience" section)

2023-09-25 20:34 UTC, norareidy commented on source/op-error-handling.txt
> +different kinds of errors.
S: it might be worthwhile to include a list of some of these variants, just because "many variants for different kinds of errors" seems pretty vague

2023-09-25 20:34 UTC, norareidy commented on source/op-error-handling.txt
> +pool might be cleared due to a concurrent operation error. In this
S: instead of using "might" as a helping verb twice, you can reword this to make the verbs a little simpler:
"A concurrent operation error might interrupt a successful connection to a MongoDB server and clear the connection pool"

2023-09-25 20:34 UTC, norareidy commented on source/op-error-handling.txt
> +operations on a replica set with three nodes, the driver would return
```suggestion
operations on a replica set with three nodes, the driver returns
```

2023-09-25 20:34 UTC, norareidy commented on source/op-error-handling.txt
> +The driver raises a ``WriteConcernError`` error when you execute a write
```suggestion
The driver raises a ``WriteConcernError`` error when you run a write
```

2023-09-25 20:34 UTC, norareidy commented on source/op-error-handling.txt
> +
S: you link to some API documentation on this page (Error, ErrorKind, etc) that could be good to add here

2023-09-25 20:34 UTC, norareidy commented on source/op-error-handling.txt
> +
actually I'm not sure if we usually include API links in a separate section that are also linked in the text, so disregard if not

2023-09-25 20:34 UTC, norareidy commented on source/op-error-handling.txt
> +   This page addresses only operation error handling. If you encounter
```suggestion
   This page only addresses operation error handling. If you encounter
```

2023-09-26 20:13 UTC, rustagir commented on source/op-error-handling.txt
> +you try to execute a write operation.
reworded

2023-09-26 20:22 UTC, rustagir commented on source/op-error-handling.txt
> +The driver raises a ``WriteConcernError`` error when you execute a write
changed all to perform

2023-09-26 20:23 UTC, rustagir commented on source/op-error-handling.txt
> +
For this kind of page (not a fundamentals page), I think linking inline could be helpful. What do you also think about removing the additional information section and moving the content that's currently there to the places where they are more relevant?

2023-09-26 20:24 UTC, rustagir commented on source/op-error-handling.txt
> +   This page addresses only operation error handling. If you encounter
Per the[ style guide](https://www.mongodb.com/docs/meta/style-guide/terminology/alphabetical-terms/#o:~:text=Don%27t%20hyphenate.-,only,-Place%20only%20preceding), the only is currently in the correct place

2023-09-27 14:34 UTC, norareidy commented on source/op-error-handling.txt
> +   This page addresses only operation error handling. If you encounter
Oh good to know, sorry about that!

2023-09-27 14:44 UTC, norareidy commented on source/op-error-handling.txt
> +   :emphasize-lines: 1
S: I'm not sure if this first line needs to be highlighted -- since you describe the RetryableWriteError label before and after the code block, maybe you could highlight line 3 instead (or remove the highlighting). Not a necessary change though if you want to emphasize the kind field

2023-09-27 14:46 UTC, norareidy commented on source/op-error-handling.txt
> +
That sounds good to me!

2023-09-27 14:46 UTC, norareidy approved these changes
LGTM with one suggestion!

2023-09-27 15:49 UTC, kevinAlbs approved these changes
LGTM with suggested change.

2023-09-27 15:49 UTC, kevinAlbs commented on source/op-error-handling.txt
> +are of the `Error <{+api+}/error/struct.Error.html>`__ type. The
```suggestion
Errors returned by the driver when performing operations are of the `Error <{+api+}/error/struct.Error.html>`__ type. The
```

[`Result` documents](https://github.com/mongodb/mongo-rust-driver/blob/6a9ef26bd1adc721fb59e61a6895d95cef3e3200/src/error.rs#L37):
> The result type for all methods that can return an error in the `mongodb` crate.

I expect all errors are returned as `Error`.

Suggest avoiding the word "exception", since Rust does not have exceptions.

2023-09-27 17:54 UTC, merged