DOCSP-30560: Connection troubleshooting
mongodb/docs-rust pull request #38
Opened 2023-09-26 18:45 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30560>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-09-27 14:52 UTC, rustagir requested changes
good job! just a few small things

2023-09-27 14:52 UTC, rustagir commented on source/connection-troubleshooting.txt
> +       {+driver-short+}
S: add another TODO here to link to the operation error page thats in progress

2023-09-27 14:52 UTC, rustagir commented on source/connection-troubleshooting.txt
> +   must be `percent encoded <https://tools.ietf.org/html/rfc3986#section-2.1>`__:
```suggestion
   If your username or password includes any of the following characters, you must
   `percent encoded <https://tools.ietf.org/html/rfc3986#section-2.1>`__ it:
```

2023-09-27 14:52 UTC, rustagir commented on source/connection-troubleshooting.txt
> +one of the hosts is unreachable.
S: could we include an example of what this looks like or link to an example? Theres an example in the connection guide: https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30560-connection-troubleshoot/fundamentals/connections/connection-guide/#connect-to-a-replica-set

2023-09-27 14:52 UTC, rustagir commented on source/connection-troubleshooting.txt
> +for authentication, specify the ``authSource`` in the connection string. The
```suggestion
for authentication, specify the ``authSource`` option in the connection string. The
```

2023-09-27 14:52 UTC, rustagir commented on source/connection-troubleshooting.txt
> +   message: "sample message" }), labels: {} }', src\main.rs:00:00
I: I'm not sure that this error type fits the description given in the introduction. From the API docs, it looks like CommandError is raised when a database command fails, not when the driver fails to send a command. Could you follow up with eng about this?

2023-09-27 14:52 UTC, rustagir commented on source/index.txt
> -   /connection-troubleshooting
I: In the index, make sure to add an entry for this guide such as here: https://github.com/mongodb/docs-golang/blob/05cd370aeccb7c23ad5ed43d822892ff899ee143/source/index.txt#L89-L94

2023-09-28 14:58 UTC, norareidy commented on source/connection-troubleshooting.txt
> +   message: "sample message" }), labels: {} }', src\main.rs:00:00
Yes I did some more research on this and you're right -- what do you think about just taking out this section? it basically just links to other sections on the page anyway

2023-09-28 17:40 UTC, rustagir approved these changes
lgtm with a few small fixes!

2023-09-28 17:40 UTC, rustagir commented on source/connection-troubleshooting.txt
> +The following sections describe methods that may help resolve the issue.
S: replace may with might ([SG](https://www.mongodb.com/docs/meta/style-guide/terminology/alphabetical-terms/#:~:text=than%20matrices.-,may,-Use%20may%20to))

2023-09-28 17:40 UTC, rustagir commented on source/connection-troubleshooting.txt
> +   must `percent encode <https://tools.ietf.org/html/rfc3986#section-2.1>`__ them:
In this note, it might also be helpful to tell users what to do with the percent encoded values. For example adding a sentence like "You can then use your percent encoded username and password as credentials in your connection string."

2023-09-28 19:13 UTC, merged

2023-10-05 19:30 UTC, kevinAlbs reviewed
LGTM with suggested change.

2023-10-05 19:30 UTC, kevinAlbs commented on source/connection-troubleshooting.txt
> +Each ``MongoClient`` instance supports a maximum number of concurrent open
Suggest using `Client` rather than `MongoClient` to match Rust driver API [Client](https://docs.rs/mongodb/latest/mongodb/struct.Client.html).