DOCSP-30545: serialization guide
mongodb/docs-rust pull request #39
Opened 2023-09-26 18:45 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30545>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30545-serialization/fundamentals/serialization/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?

2023-09-27 15:54 UTC, isabelatkinson reviewed
the serde info looks great, you hit all the points I had in mind! I just have one suggestion regarding collection parameterization

2023-09-27 15:54 UTC, isabelatkinson commented on source/fundamentals/database-collection.txt
> +   data operations.
This used to be true but no longer is; we removed the default generic type for `Collection` in the 2.0 driver release. Users are required to specify a type for their collection now.

As a side note (I'm not sure if this would actually be worth mentioning in the docs), the compiler can infer the type of the collection if a CRUD method is called with a concrete data type in the same scope. For example, the following will compile:

```
// no type annotation
let collection = client.database("db").collection("coll");
// compiler can infer that collection is a Collection<Document> because a `Document` is being inserted
collection.insert_one(doc! { "x": 1 }, None).await?;
```

2023-09-27 17:55 UTC, rustagir commented on source/fundamentals/database-collection.txt
> +   data operations.
thanks for the clarification! I think that is worth mentioning, I'll revise that section.

2023-09-27 20:48 UTC, norareidy requested changes
Really good, just added some suggestions

2023-09-27 20:48 UTC, norareidy commented on source/fundamentals/serialization.txt
> +The following code defines a sample ``Vegetable`` struct that derives the
S:
```suggestion
The following code defines a sample ``Vegetable`` struct that implements the
```

2023-09-27 20:48 UTC, norareidy commented on source/fundamentals/serialization.txt
> +``Deserialize`` traits from the ``serde`` crate as the generic parameter for a
Applies to other mentions of "generic parameter" as well (unless Rust usually references generic parameters rather than generic type parameters)

2023-09-27 20:48 UTC, norareidy commented on source/fundamentals/serialization.txt
> +the ``serialize_with`` attribute attached to the field. In the following
```suggestion
the ``serialize_with`` attribute attached to the field with a ``DateTime`` value. In the following
```

2023-09-27 20:48 UTC, norareidy commented on source/includes/fundamentals/code-snippets/serialization.rs
> +    let my_coll: Collection<Vegetable> = client.database("db").collection("vegetables");
S: There's some horizontal scroll for this example, maybe split into two lines

2023-09-27 20:48 UTC, norareidy commented on source/includes/fundamentals/code-snippets/serialization.rs
> +    // ... perform some operations with Circle
S: there's also a little horizontal scroll for this example

2023-09-27 20:48 UTC, norareidy commented on source/fundamentals/serialization.txt
> +to see how the driver serializes a sample ``Order`` struct to BSON:
S:

 1. put the second half of this sentence first, i.e.: "To see how the driver serializes a sample ``Order`` struct to BSON, select from ..."

 2. style guide doesn't love "below", you could use "Select from the following Struct and BSON tabs" instead

2023-09-27 20:48 UTC, norareidy commented on source/fundamentals/serialization.txt
> +to see how the driver serializes a sample ``Order`` struct to BSON:
S: same suggestion as above (lines 171-172)

2023-09-27 20:48 UTC, norareidy commented on source/fundamentals/serialization.txt
> +the ``serialize_with`` attribute attached to the field. In the following
```suggestion
the ``serialize_with`` attribute attached to the field with a ``u32`` value. In the following
```

2023-09-27 20:48 UTC, norareidy commented on source/fundamentals/serialization.txt
> +example, the ``delivery_date`` field has a value of type ``DateTime``:
S: since this code example is showing how to represent DateTime as a string in BSON, it would be helpful for the example's introductory text to include that: 
"In the following example, the `serialize_with` attribute specifies the conversion of the DateTime type to a string type in BSON:" (or something similar)

2023-09-27 20:48 UTC, norareidy commented on source/fundamentals/serialization.txt
> +example, the ``quantity`` field has a value of type ``u32``:
S: same suggestion as above (line 203)

2023-09-27 20:48 UTC, norareidy commented on source/fundamentals/serialization.txt
> +API documentation <https://serde.rs/attributes.html>`__
```suggestion
API documentation <https://serde.rs/attributes.html>`__.
```

2023-09-28 14:54 UTC, rustagir commented on source/fundamentals/serialization.txt
> +in your collection. To learn more about specifying a generic parameter,
changed in all places

2023-09-28 14:58 UTC, rustagir commented on source/fundamentals/serialization.txt
> +the ``serialize_with`` attribute attached to the field. In the following
changed for examples 2 & 3

2023-09-28 17:21 UTC, rustagir commented on source/fundamentals/serialization.txt
> +to see how the driver serializes a sample ``Order`` struct to BSON:
changed both

2023-09-28 20:34 UTC, norareidy approved these changes
LGTM + small suggestions

2023-09-28 20:34 UTC, norareidy commented on source/fundamentals/serialization.txt
> +specify an attribute on a struct field or enum variant, include it
S: just to clarify what "it" refers to, 

```suggestion
specify an attribute on a struct field or enum variant, include the attribute
```

2023-09-28 20:34 UTC, norareidy commented on source/fundamentals/serialization.txt
> +serialization and deserialization on specific fields and variants. To
S: not a necessary change but I do find the length/complexity of this sentence a little hard to follow. Maybe break it up, like: 

"The serde crate provides the serialize_with and deserialize_with attributes, which take helper functions as values. These helper functions customize serialization and deserialization on specific fields and variants."

2023-09-28 20:34 UTC, norareidy commented on source/fundamentals/serialization.txt
> +To see a full list of these modules, see the `serde_helpers API
S: nit, but to prevent using "see" twice:

```suggestion
For a full list of these modules, see the `serde_helpers API
```

2023-09-28 20:35 UTC, norareidy commented on source/fundamentals/serialization.txt
> +To see a full list of these modules, see the `serde_helpers API
applies elsewhere too if you do decide to reword

2023-10-02 20:59 UTC, isabelatkinson approved these changes

2023-10-03 16:19 UTC, merged