DOCSP-33325: Update configuration instructions
mongodb/docs-rust pull request #41
Opened 2023-09-27 17:04 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-33325>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-09-27 21:23 UTC, ccho-mongodb approved these changes
Looks pretty good! Lots of helpful information.
I provided a few suggestions that I think could help structure the information and make it more concise. Approving, but feel free to reach out if you want me to take another look.

2023-09-27 21:23 UTC, ccho-mongodb commented on source/quick-start/download-and-install.txt
> +         If you leave out the ``bson`` crate from your dependencies list, include the
Issue:

From the style guide on use effective verbs and [concise terms](https://www.mongodb.com/docs/meta/style-guide/terminology/concise-terms/), use "omit" instead of "leave out".

Suggestion:
```suggestion
         If you leave out the ``bson`` crate from your dependencies list, include the
```

```suggestion
         If you omit the ``bson`` crate from your dependencies, add the
```

2023-09-27 21:23 UTC, ccho-mongodb commented on source/quick-start/download-and-install.txt
> +      need to specify the ``bson`` crate in your ``Cargo.toml`` file.
Suggestion:
I think if the "mongodb" dependency always resolves "bson", there's no reason to mention including it independently in this section. I think the only place in which the reference documentation might describe the "bson" crate being used without "mongodb" might be in a page on "bson".

Instead, I think just mentioning that "mongodb" includes "bson" should be sufficient.

2023-09-27 21:23 UTC, ccho-mongodb commented on source/quick-start/download-and-install.txt
> +      Alternatively, you can configure the dependencies in your ``Cargo.toml`` file to
Suggestion:
Since this is a how-to guide/task, I think it would be good to use the imperative mood whenever possible as mentioned in the style guide.

In this case, it would help to provide the reason why they would choose to use both rather than to present it as an option. E.g.

"If you you need to use both asynchronous and synchronous runtimes, use the following dependency list:"

2023-09-27 21:23 UTC, ccho-mongodb commented on source/quick-start/download-and-install.txt
> +         the corresponding feature flag is required.
Suggestion:
I think this section could be made more concise by separating the important and supplemental information. I think the important informational items are as follows:

- The driver uses the tokio asynchronous runtime crate by default.
- If you need to use a different runtime crate, replace the values in the feature flag. For example: ...
- If you need to use both asynchronous and synchronous runtimes, use the following: ...

And somewhere in there, add a tip callout (show alternative ways of doing something) that tokio asynchronous runtime crate is the default and does not need to be specified.

2023-09-28 17:06 UTC, norareidy commented on source/quick-start/download-and-install.txt
> +      You can add the following crates to your project by including them in
Ah okay, I changed the wording because you don't need to add all the crates listed but I've changed it back

2023-09-28 17:45 UTC, norareidy commented on source/quick-start/download-and-install.txt
> +      The ``mongodb`` crate re-exports the ``bson`` crate, so you do not need
Yes I think exports would make more sense here. I'm not sure which dependency would be resolved first (but don't think I need to explain that based on changes I made from your next comment)

2023-09-28 20:08 UTC, ccho-mongodb approved these changes
LGTM - a couple more suggestions and a minor issue.

2023-09-28 20:08 UTC, ccho-mongodb commented on source/quick-start/download-and-install.txt
> +      - the ``sync`` crate with the ``"sync"`` feature flag
Suggestion:
While the names of the crates might be sufficient for some readers, I think it could be helpful to link to their crate docs pages.  E.g. 

You can specify the following runtime crates:
- async-std, which is the async-std-runtime (link) crate
- sync, which is the sync (link) crate

2023-10-02 20:21 UTC, abr-egn requested changes

2023-10-02 20:21 UTC, abr-egn commented on source/quick-start/download-and-install.txt
> +      - The ``sync`` crate with the ``"sync"`` feature flag. For more information
`sync` isn't a crate, it's the name for feature flag for the synchronous wrapper API using the `async-std` runtime in the driver.

This is a bit of a mess for historical reasons; I think the best way to summarize it is:

**async API using the `tokio` crate runtime**:
This is the default, so nothing's needed.  Can also be written
```
features = ["tokio-runtime"]
```
for explicitness.

**sync API using the `tokio` runtime**:
```
features = ["tokio-sync"]
```

**async API using the `async-std` crate runtime**:
```
default-features = false
features = ["async-std-runtime"]
```

**sync API using the `async-std` crate runtime**:
```
default-features = false
features = ["sync"]
```

When the sync API is enabled for either runtime the async API is also available.

2023-10-03 17:48 UTC, norareidy commented on source/quick-start/download-and-install.txt
> +      - The ``sync`` crate with the ``"sync"`` feature flag. For more information
This makes a lot of sense, thanks!

2023-10-04 14:21 UTC, abr-egn approved these changes

2023-10-04 15:27 UTC, merged