DOCSP-30506 Async and Sync Runtimes
mongodb/docs-rust pull request #54
Opened 2023-10-04 16:23 UTC by pierwill

- DOCSP-30506
- Build log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=651d90a3492df295cf7ca197
- Staging: 

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-10-05 15:19 UTC, rustagir requested changes

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +In this guide, you can learn how to configure and use the driver's asynchronous and synchronous APIs.
```suggestion
In this guide, you can learn about the {+driver-short+}'s asynchronous and synchronous runtimes.
This guide explains how to enable the available runtimes and structure your code to use each API.
```

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +The driver also includes a synchronous API for simplicity, or when parallelism is not necessary.
S: replace this section with a list of the runtime that the driver supports. 

For example:
```
The driver supports the following asynchronous runtime crates:
- ``tokio`` (the default runtime)
- ``async-std-runtime``

To learn more about these runtimes, see the :ref:`...` section.

The driver supports the following synchronous runtime crates:
....

To learn more about these runtimes, see the :ref:`...` section.
```

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +   :backlinks: nones
```suggestion
   :backlinks: none
```

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +The driver uses ``tokio`` by default.
```suggestion
The driver uses the ``tokio`` runtime by default.
```

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +   features = ["async-std-runtime"]
S: I think the instructions on how to install the different crates should be first in this section. Maybe you can have some tabs on how to install each one.

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +   :dedent:
S: This section could benefit from a short explanation of why/when users should use an async programming framework. [This page](https://rust-lang.github.io/async-book/01_getting_started/02_why_async.html) has some interesting notes. Also, it would be great to make some distinctions b/t the two async (and sync) crates. What makes them different? Can follow up with eng if needed.

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +---------------------
I: this heading is mismatched from the other heading, and contains the wrong amount of underscores
```suggestion
Configure the Synchronous Runtime
------------------------------------
```

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +Use the `Client() <{+api+}/struct.Client.html>`__ type for asynchronous programming.
S: make a subsection for "Asynchronous Example" (same for sync section)

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +The driver also provides a blocking, synchronous API.
S: same comment applies here. Why use sync? what makes the two sync runtimes different?

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +The sync-specific types can be imported from ``mongodb::sync`` (e.g. ``mongodb::sync::Client``).
S: Move into a new section

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +To enable this, add the ``sync`` or ``tokio-sync`` feature to your ``Cargo.toml``.
Show config for both runtimes

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +The sync-specific types can be imported from ``mongodb::sync`` (e.g. ``mongodb::sync::Client``).
S: use active voice
```suggestion
When using the synchronous runtime, you must use types from the ``mongodb::sync`` module to perform operations. The synchronous API calls through to the asynchronous API internally, so you can use ``sync`` types as you might use types from the asynchronous API.
```

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +Each request must finish before the next can begin.
```suggestion
The driver waits for each request to complete before continuing.
```

2023-10-05 15:19 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +-----------------
```suggestion
~~~~~~~~~~~~~~~~~
```

2023-10-10 22:06 UTC, pierwill commented on source/fundamentals/async-sync.txt
> +   :dedent:
This gets into some pretty deep questions about application design that we might not want to cover in the drivers docs.

2023-10-10 22:07 UTC, pierwill commented on source/fundamentals/async-sync.txt
> +The driver also provides a blocking, synchronous API.
In the overview, it says "for simplicity, or when parallelism is not necessary". Does that make sense?

2023-10-11 19:02 UTC, rustagir requested changes
good start- let me know if you want to discuss any comments.

2023-10-11 19:02 UTC, rustagir commented on source/fundamentals/async-sync.txt
> +It uses the synchronous client type imported from the ``sync`` module on the first line.
S: combine these two lines for concision

2023-10-11 20:01 UTC, pierwill commented on source/fundamentals/async-sync.txt
> +The driver also includes a synchronous API for simplicity, or when parallelism is not necessary.
I did :) I added links to the subsections like you recommended. I personally think it's a bit nicer to have this overview flow instead of having the unordered list. But I'm happy to make the change if you think it'd be better.

2023-10-11 20:05 UTC, pierwill commented on source/fundamentals/async-sync.txt
> +   :dedent:
I decided to use a new file since these two examples could diverge in the future.

2023-10-16 16:30 UTC, rustagir requested changes

2023-10-16 16:30 UTC, rustagir commented on source/fundamentals/runtimes.txt
> +The driver also includes a synchronous API for simplicity, or when parallelism is not necessary.
S: in this sentence, describe both sync runtime feature flags as you did in the paragraph describing the async ones.

2023-10-16 16:30 UTC, rustagir commented on source/fundamentals/runtimes.txt
> +You can explicitly choose a runtime by specifying either the ``tokio-runtime`` or ``async-std-runtime`` feature flag in your ``Cargo.toml``.
```suggestion
You can explicitly choose a runtime by specifying adding the ``"tokio-runtime"`` or ``"async-std-runtime"``
feature flags to your ``mongodb`` dependency.
```

2023-10-16 16:30 UTC, rustagir commented on source/fundamentals/runtimes.txt
> +To enable this, add the ``sync`` or ``tokio-sync`` feature to your ``Cargo.toml``.
```suggestion
To use the synchronous runtime, add the either the ``"sync"`` or ``"tokio-sync"`` feature flag
to your ``mongodb`` dependency.
```

2023-10-16 16:30 UTC, rustagir commented on source/fundamentals/runtimes.txt
> +
```suggestion
Select from the following tabs to see how to add feature flags for each corresponding crate:
```

2023-10-16 16:30 UTC, rustagir commented on source/fundamentals/runtimes.txt
> +
S: add tabs here to show both sync runtimes

2023-10-16 16:30 UTC, rustagir commented on source/fundamentals/runtimes.txt
> +When the ``insert_one`` method runs inside the ``for`` loop, the driver waits for each request to complete before continuing.
```suggestion
When the ``insert_one`` method runs inside the ``for`` loop, the driver waits for each request to complete before continuing on to the next operation.
```

2023-10-16 16:30 UTC, rustagir commented on source/fundamentals/runtimes.txt
> +``"tokio-sync"`` flag to your ``mongodb`` dependency:
```suggestion
For example, to enable both ``tokio`` runtimes, you can add the ``tokio`` dependency to your dependencies list and add the
``"tokio-sync"`` flag to your ``mongodb`` dependency:
```

2023-10-16 16:30 UTC, rustagir commented on source/includes/fundamentals-sections.rst
> +- :ref:`Asynchronous and Synchronous Runtimes <rust-runtimes>`
S: convert this to use the same verb format as the other entries

2023-10-17 13:43 UTC, rustagir approved these changes
approving with some last comments!

2023-10-17 13:43 UTC, rustagir commented on source/fundamentals/runtimes.txt
> +===============================================
S: I think the title was fine before, only the link text in the fundamentals section needed to be changed. Feel free to change this back, if you prefer.

2023-10-17 13:43 UTC, rustagir commented on source/fundamentals/runtimes.txt
> +by adding feature flags to the ``mongodb`` dependency in your ``Cargo.toml`` file.
```suggestion
By default, the driver uses the ``tokio`` asynchronous runtime, but you can select a specific runtime
by adding feature flags to the ``mongodb`` dependency in your ``Cargo.toml`` file.
```

2023-10-17 13:43 UTC, rustagir commented on source/fundamentals/runtimes.txt
> +feature flags to the ``mongodb`` dependency.
```suggestion
You can explicitly choose a runtime by adding the ``"tokio-runtime"`` or ``"async-std-runtime"``
feature flags to the ``mongodb`` dependency.
```

2023-10-20 16:19 UTC, pierwill commented on source/fundamentals/runtimes.txt
> +Configure Asynchronous and Synchronous Runtimes
Thanks, @isabelatkinson ! That makes sense. I like "Async and Synch APIs" as a title. I'll look through the doc an make some adjustments, then tag you again. :)

2023-10-30 16:50 UTC, isabelatkinson approved these changes

2023-10-30 16:57 UTC, merged