DOCSP-30509: Usage examples landing page
mongodb/docs-rust pull request #61
Opened 2023-10-16 13:54 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30509>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-10-16 16:15 UTC, rustagir requested changes
a few small things! - also can you investigate why this is failing the vale check

2023-10-16 16:15 UTC, rustagir commented on source/usage-examples.txt
> +  your own environment
```suggestion
- A Rust program that you can run in your own environment
```

2023-10-16 16:15 UTC, rustagir commented on source/usage-examples.txt
> +
Add the info about sync async here:
```suggestion

Every usage example provides the same example using both the asynchronous and synchronous runtimes.
.. To learn more about runtimnes... link to future page
```

2023-10-16 16:15 UTC, rustagir commented on source/usage-examples.txt
> +more about getting started with the {+driver-short+}.
```suggestion
Once you import the datasets, you can copy and paste a usage example into your
development environment of choice. Follow the :ref:`rust-quickstart` to learn
more about creating a sample app that uses the {+driver-short+}.
```

2023-10-16 16:15 UTC, rustagir commented on source/usage-examples.txt
> +   // Replace the bracketed text with your MongoDB deployment's connection string
```suggestion
   // Replace the placeholder with your MongoDB deployment's connection string
```

2023-10-16 16:15 UTC, rustagir commented on source/usage-examples.txt
> +After you have copied a usage example into your development environment, you
```suggestion
After you copy a usage example into your development environment, you
```

2023-10-16 19:20 UTC, ccho-mongodb commented on source/usage-examples.txt
> +</server/import/>`.
Issue:

I noticed that this link redirects to atlas/sample-data which only shows how to import the sample dataset into Atlas and not a local instance. I wasn't able to find a good page to link to in the five minutes I spent looking, so maybe there's some reason why it's not in the docs. Could you reach out to the other docs teams in our Slack channels for advice on a replacement url?

2023-10-16 19:20 UTC, ccho-mongodb commented on source/usage-examples.txt
> +more about creating an application that uses the {+driver-short+}.
Suggestion:

No change needed, but if you wanted to improve this description, a couple areas that I think can be addressed are:

- Provide information that explains what "creating an application" has to do with "copy and paste a usage example". I think there's some assumptions the reader needs to make to understand this, so it could be beneficial to provide some explanation.
- Use the imperative mood to explain more concisely and definitively how the reader can get to the goal.

2023-10-16 19:20 UTC, ccho-mongodb commented on source/usage-examples.txt
> +How to Use the Usage Examples
Suggestion:
Since this starts with "How to...", I think it might be better to represent as a [task](https://www.mongodb.com/docs/meta/style-guide/style/tasks/#std-label-tasks), and the information on this page should be converted to fit that model. This can be ticketed out if it seems out of scope.

One alternative that I can think of is to remove details on how to perform the tasks and just provide links to the different options the reader can follow for setup. E.g.


```
Run the Usage Examples
---

To run the usage examples, load the Atlas sample datasets into your MongoDB deployment. To learn how to load the datasets into your Atlas cluster, see ... To learn how to load the datasets into your local deployment, see...

Each example contains placeholders including one for the connection string. To learn how to find your connection string, see...
```

2023-10-16 20:29 UTC, norareidy commented on source/usage-examples.txt
> +and synchronous runtimes.
I included information about the runtimes in the list itself, but kept the sentence directing readers to further information on runtimes after the list (commented out in a TODO for now)

2023-10-16 21:16 UTC, norareidy commented on source/usage-examples.txt
> +How to Use the Usage Examples
Reformatted this section to fit the task model

2023-10-16 21:17 UTC, norareidy commented on source/usage-examples.txt
> +collection in the ``sample_restaurants`` database. You can load the sample
Since this info is now included in a paragraph introducing the Atlas sample data setup steps, I think it's relevant -- let me know what you think

2023-10-16 21:49 UTC, norareidy commented on source/usage-examples.txt
> +more about creating an application that uses the {+driver-short+}.
I reworded to the imperative mood, and also to clarify that you're pasting into an application file

2023-10-16 21:58 UTC, norareidy commented on source/usage-examples.txt
> +</server/import/>`.
Since a page on this topic doesn't exist (according to JW's response in #docs-writers), I just took this part out

2023-10-17 20:49 UTC, rustagir requested changes
a few things, but moving in the right direction!

2023-10-17 20:49 UTC, rustagir commented on source/index.txt
> +methods, see :ref:`rust-usage-examples`.
S: we have moved away from using "snippet" in most contexts

```suggestion
For fully runnable code examples and explanations of common
MongoDB operations, see :ref:`rust-usage-examples`.
```

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +a MongoDB operation. Each usage example includes the following:
```suggestion
Usage examples enable you gain a broad understanding of common MongoDB operations by 
demonstrating how to organize and run a small sample application. Each usage example includes the following:
```

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +  in your own environment
```suggestion
- Asynchronous and synchronous Rust code examples that you can run
  in your own environment
```

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +- The expected output of the program
```suggestion
- The expected output of the code example
```

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +</sample-data>` provided by Atlas. Before running the programs included in the
S: don't link here, since the instructions on loading the sample data are included in the procedure step "Retrieve the Sample Datasets" anyways

```suggestion
``sample_restaurants`` database. This dataset is one of the sample datasets
included in the Atlas sample data. Before running the programs included in the
```

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +your development environment.
S: edit this sentence. Right now, this sentence only describes step 1

```suggestion
usage examples, perform the following actions:
```

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +      to import the sample datasets into your database on the free tier of MongoDB Atlas.
S: link to this page instead of the Getting started guide: https://www.mongodb.com/docs/atlas/sample-data/

Alternatively, you should provide more information in this section that describes that the user needs to also have an atlas account before even loading the sample data

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +   .. step:: Use the Sample Datasets in your Development Environment
S: update this step name to more accurately match the step text

```suggestion
   .. step:: Add the Usage Example Code to your Development Environment
```

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +      In your application file, edit the connection URI to connect to your MongoDB instance:
```suggestion
      In your application file, replace the connection string placeholder so that the program connects to your 
      MongoDB deployment:
```

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +         // Replace the placeholder with your MongoDB deployment's connection string
S: if you accept my previous comment, this code comment is no longer needed

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +
S: delete extra line

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +and see the output described on the program's corresponding usage example page.
```suggestion
After completing these steps, you can run a program in your development environment
and see the output described in the **Expected Output** section of the corresponding usage example.
```

2023-10-17 20:49 UTC, rustagir commented on source/usage-examples.txt
> +    - :ref:`Find Distinct Values<rust-distinct-usage>`
S: though we will edit these as we work on the tickets, add the space before the <
```suggestion
    - :ref:`Find a Document <rust-find-one-usage>`
    - :ref:`Find Multiple Documents <rust-find-usage>`
    - :ref:`Insert a Document<rust-insert-one-usage>`
    - :ref:`Insert Multiple Documents<rust-insert-many-usage>`
    - :ref:`Update a Document<rust-update-one-usage>`
    - :ref:`Update Multiple Documents<rust-update-many-usage>`
    - :ref:`Replace a Document<rust-replace-usage>`
    - :ref:`Delete a Document<rust-delete-one-usage>`
    - :ref:`Delete Multiple Documents<rust-delete-many-usage>`
    - :ref:`Count Documents<rust-count-usage>`
    - :ref:`Find Distinct Values<rust-distinct-usage>`
```

2023-10-17 21:04 UTC, ccho-mongodb commented on source/usage-examples.txt
> +   .. step:: Retrieve the Sample Datasets
Suggestion:
I think "Load" is a more accurate verb and is what is used in the Atlas docs in the title "Load Sample Data". I think "Retrieve" used in this context only describes the process of downloading them.

2023-10-17 21:10 UTC, ccho-mongodb commented on source/usage-examples.txt
> +   .. step:: Edit the Connection String
Suggestion:
I think "Edit" might not be the most precise verb and "Connection String" might not portray the object since it's a placeholder. I think "Replace the Connection String Placeholder" would match the wording in Rea's suggestion and be easier to understand.

2023-10-18 21:31 UTC, norareidy commented on source/usage-examples.txt
> +      to import the sample datasets into your database on the free tier of MongoDB Atlas.
Since the current link (Getting Started guide) includes steps to create an account, create/connect to a cluster, and load sample data, would it be better to leave it instead of just linking to the Load Sample Data page? I think that way I can leave out info about making an account, but let me know what you think

2023-10-19 14:59 UTC, ccho-mongodb requested changes

2023-10-19 14:59 UTC, ccho-mongodb commented on source/usage-examples.txt
> +- A general overview of the MongoDB operation
Suggestion:

Per the style guide on [List Items](https://www.mongodb.com/docs/meta/style-guide/style/lists/#list-items):
> Avoid using articles (a, an, the) to start list items.

Also, I think "overview" can be too indefinite and is usually interpreted as a "big picture" description which probably doesn't match what we intend to include. I would recommend something like this:

"Description of the MongoDB operation"

2023-10-19 14:59 UTC, ccho-mongodb commented on source/usage-examples.txt
> +- The expected output of the code example
```suggestion
- Output printed by the code example
```

2023-10-19 14:59 UTC, ccho-mongodb commented on source/usage-examples.txt
> +      Copy the usage example program that you wish to run. Then, navigate to a file in
Issue:

From the style guide [terms](https://www.mongodb.com/docs/meta/style-guide/terminology/alphabetical-terms/#w):
> Use want, or another appropriate word, instead of desire or wish.

Suggestion:

In addition to following the style guide guidance, I think it would be helpful to include instructions from scratch in which no pre-existing file is assumed.

I think the following could be a good replacement for these two sentences:
"Copy the example code from the Usage Example page and paste it into a new file in your preferred directory."

2023-10-19 14:59 UTC, ccho-mongodb commented on source/usage-examples.txt
> +the usage examples, perform the following actions:
Suggestions:

- I think presenting the usage examples on data would be helpful. 
- I think the reason why they should perform the following actions is missing.
- I think the option not to perform the setup should be mentioned since the usage examples will still run, but probably not match the output.
- I think it's not important to mention which database or collection since the instructions only show how to load all the sample data at once and not individually.
 
```suggestion
The usage examples are designed to run operations on a MongoDB deployment that
contains the Atlas sample datasets. When you run the example code without the Atlas
data, the output may not match. To set up your MongoDB deployment with the Atlas data
and run the example code in your development environment, perform the following actions:
```

2023-10-19 14:59 UTC, ccho-mongodb commented on source/usage-examples.txt
> +         let uri = "<connection string>";
Suggestion:

I think the code example may not demonstrate what the user needs to do. 

```suggestion
In your example code, replace the ``connection string`` placeholder with your MongoDB deployment connection string. For example, if your connection string is ..., your connection string assignment should resemble the following:
...
```

2023-10-19 14:59 UTC, ccho-mongodb commented on source/usage-examples.txt
> +usage example.
Suggestion:

I think this isn't the completion state for "how to use a usage example" since they haven't run the program yet, and needs to continue to use the imperative mood ("do this") rather than one of possibility ("you can").

I think running the code should be a separate step even though it might need to be generalized for different development environments.

"Run your application in your development environment. If you run your Rust applications on the command line, the command should resemble the following: ..."

2023-10-19 16:41 UTC, ccho-mongodb commented on source/usage-examples.txt
> +      ``"mongodb://localhost:27017"``, your connection string assignment should resemble the
Suggestion:

Since this section mentions Atlas deployments, I think it would be better to use the DNS seedlist format.
Also, I think you can replace the subjunctive "should" as follows:

```suggestion
      ``"mongodb+srv://mongodb-example:27017"``, your connection string assignment resembles the
```

2023-10-19 16:44 UTC, ccho-mongodb commented on source/usage-examples.txt
> +the Atlas sample datasets. When you run the example code without the Atlas data, the output
I think "sample" could be a slightly more precise adjective than "Atlas" in this case.

```suggestion
the Atlas sample datasets. When you run the example code without the sample data, the output
```

2023-10-19 16:44 UTC, ccho-mongodb commented on source/usage-examples.txt
> +Follow this tutorial to set up your MongoDB deployment with the Atlas data and run the
Suggestion: 
Similar to the previous comment:

```suggestion
Follow this tutorial to set up your MongoDB deployment with the sample data and run the
```

2023-10-19 16:46 UTC, ccho-mongodb commented on source/usage-examples.txt
> +      your preferred application directory.
Suggestion:

I think "application directory" could be confused with a system directory that holds applications such as "Applications" in MacOS, and omitting "application" could lower the chance of confusion.

```suggestion
      your preferred directory.
```

2023-10-19 16:47 UTC, ccho-mongodb approved these changes
LGTM! Added a couple suggestions.

2023-10-31 16:50 UTC, merged