DOCSP-30547: indexes
mongodb/docs-rust pull request #62
Opened 2023-10-16 15:49 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30547>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30547-indexes/fundamentals/indexes/
[fundamentals sections list](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30547-indexes/#fundamentals)

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-10-16 20:04 UTC, norareidy requested changes
Looks great, added a few suggestions!

2023-10-16 20:04 UTC, norareidy commented on source/fundamentals/indexes.txt
> +- :manual:`Compound Text Index Restrictions </core/index-text/#std-label-text-index-compound>`
```suggestion
- :manual:`Compound Text Index Restrictions </core/index-text/#compound-text-indexes>`
```

2023-10-17 13:50 UTC, rustagir commented on source/fundamentals/indexes.txt
> +``city`` field in the ``zips`` collection:
I am divided on this, since there isn't even any reference to the collection name in the code snippets anyways. Should I just remove the collection reference altogether?

2023-10-17 13:52 UTC, rustagir commented on source/fundamentals/indexes.txt
> +``city`` field in the ``zips`` collection:
this would apply to all of the examples that mention a collection

2023-10-17 14:02 UTC, rustagir commented on source/fundamentals/indexes.txt
> +``location`` field in the ``stores`` collection:
see earlier reply

2023-10-17 14:02 UTC, rustagir commented on source/fundamentals/indexes.txt
> +``user_id`` field in the ``users`` collection:
see earlier reply

2023-10-17 14:03 UTC, rustagir commented on source/fundamentals/indexes.txt
> +To learn more about the methods and types discussed in this
will need to change everywhere - can add this to v2 cleanup

2023-10-17 15:34 UTC, norareidy commented on source/fundamentals/indexes.txt
> +``city`` field in the ``zips`` collection:
True, I mainly mentioned the databases since the examples do switch between datasets pretty often and it could be confusing to someone trying to run all the examples without extra clarity. Many of the fundamentals page have a section on top just to clarify what sample data the examples are using -- maybe you could just add a sentence to the overview information saying that the page uses collections from the Atlas sample_training database?

2023-10-17 15:38 UTC, norareidy commented on source/fundamentals/indexes.txt
> +To learn more about the methods and types discussed in this
Yeah I remember a comment from Chris on avoiding "discussed" in the docs, seems like a good idea to fix elsewhere

2023-10-17 16:01 UTC, norareidy approved these changes
LGTM but I'll follow up on the database discussion

2023-10-18 14:55 UTC, abr-egn approved these changes
LGTM!

2023-10-18 15:25 UTC, merged