DOCSP-30518: Delete Many Usage Example
mongodb/docs-rust pull request #67
Opened 2023-10-31 19:49 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30518>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-11-01 18:24 UTC, rustagir requested changes
A few small things!

2023-11-01 18:24 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +with the collection.
S: move this information into a tip admonition because it is a useful suggestion, but not directly in line with the goal of the page.

2023-11-01 18:24 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +instance.
```suggestion
The ``delete_many()`` method returns a ``DeleteResult`` type, which contains
information about the delete operation, such as the total number of
documents deleted.
```

2023-11-01 18:24 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +and the value of the ``street`` field is ``"Broadway"``.
```suggestion
and the value of the ``address.street`` field is ``"Broadway"``.
```

2023-11-01 18:24 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +guide.
```suggestion
To learn more about delete operations, see the :ref:`rust-delete-guide` guide.
```

2023-11-01 18:24 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +the Databases and Collections guide.
S: move this to the tip admonition I suggested earlier

2023-11-01 18:24 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +To learn more about using query filters, see the :ref:`rust-query-guide` guide.
```suggestion
To learn more about creating query filters, see the :ref:`rust-query-guide` guide.
```

2023-11-01 18:24 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +- `deleted_count <{+api+}/results/struct.DeleteResult.html#structfield.deleted_count>`__
S: Since this is a field of the previously linked `DeleteResult` type, you can remove this link

2023-11-01 18:24 UTC, rustagir commented on source/includes/usage-examples/code-snippets/delete-many-sync.rs
> +    borough: String,
S: remove this field since it is not used anywhere

2023-11-01 18:24 UTC, rustagir commented on source/includes/usage-examples/code-snippets/delete-many-sync.rs
> +    borough: String,
applies to other code file too

2023-11-02 14:33 UTC, norareidy commented on source/usage-examples/deleteMany.txt
> +.. _rust-delete-many-usage:
Yeah I was torn about that since all the usage example files in other repos use camel case for the file names (and lowercase for fundamentals pages), but happy to change

2023-11-02 14:34 UTC, norareidy commented on source/includes/usage-examples/code-snippets/delete-many-sync.rs
> +    borough: String,
I do query for borough, do you mean the "name" field? I can remove "name," but I feel like it makes the sample output more readable to have the restaurant name

2023-11-02 14:53 UTC, norareidy commented on source/includes/usage-examples/code-snippets/delete-many-sync.rs
> +    borough: String,
Oh nvm this code example doesn't output any documents, I'll take out "name"

2023-11-02 15:08 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +.. _rust-delete-many-usage:
No need to change, but I think it makes the URL look cleaner to use kebab case.

2023-11-02 15:22 UTC, rustagir approved these changes
approving with a few last comments!

2023-11-02 15:22 UTC, rustagir commented on source/includes/usage-examples/code-snippets/delete-many-sync.rs
> +    borough: String,
oops, my bad for not noticing the query on borough. Sure, removing the `name` field sgtm

2023-11-02 15:22 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +    associated with the collection.
S: remove all of the redundant information thats repeated in the linked section - that's where that info can be found is a user is looking for it!

```suggestion
    To delete all of the data in a collection in a single operation, call the ``drop()``
    method on a ``Collection`` instance.
```

2023-11-02 15:22 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +    section in the Databases and Collections guide.
```suggestion
    To learn more about the ``drop()`` method, see the :ref:`rust-drop-collection`
    section of the Databases and Collections guide.
```

2023-11-02 15:22 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +documents deleted.
S: move this information before the admonition to keep it all together. Otherwise this kind of gets lost sandwiched between a header and an admonition

2023-11-02 15:22 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +a query filter. The example uses a ``Restaurant`` struct that has ``address``
```suggestion
This example deletes all of the documents from the ``restaurants`` collection that match
a query filter. The example uses a ``Restaurant`` struct that has ``address``
```

2023-11-02 15:22 UTC, rustagir commented on source/usage-examples/deleteMany.txt
> +            Deleted documents: 615
Q: what do you think about adding a note here that suggests that a user's output might differ because of previous CRUD operations they might have performed on their collection? I did that [here](https://github.com/mongodb/docs-rust/pull/70/files#diff-f148b6f939801e1fcdcedc70d15ef9899d0ee46e6e782ac7b3e9868a82a067beR51)

2023-11-02 20:03 UTC, norareidy commented on source/usage-examples/deleteMany.txt
> +            Deleted documents: 615
Sounds good

2023-11-02 20:19 UTC, merged