DOCSP-30510: Find One Usage Example
mongodb/docs-rust pull request #68
Opened 2023-11-01 15:17 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30510>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-11-01 22:35 UTC, ccho-mongodb requested changes
Looks pretty good. I added a few suggestions and identified a couple issues; requested changes because I'd like to take another look at the updated version.

2023-11-01 22:35 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +``Some`` if a document matches the query filter and ``None`` if no documents match.
Suggestion:

I think this info about "Some" and "None" values could be omitted since this information repeats the [Retrieve Data](https://www.mongodb.com/docs/drivers/rust/current/fundamentals/crud/read-operations/retrieve/#find-one-document) content and isn't used in the Usage Example.

2023-11-01 22:35 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +This example finds a document from the ``sample_restaurants.restaurants`` collection
Issue:

Since collection names can have periods in them, this refers to a collection with the name "sample_restaurants.restaurants" rather than what I think is intended (a database name of "sample_restauarants" and collection name of "restaurants").

Suggestion:

I think calling it a "namespace" works, but maybe identifying the database name and collection name separately would be helpful for the target personas. I think the example retrieves a document that matches a query filter. I think "finds" might be used more for cases in which there's only a check for its existence.

```suggestion
This example retrieves a document from the ``restaurants`` collection in the ``sample_restaurants`` database
```

2023-11-01 22:35 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +and ``cuisine`` fields to model the documents in the collection.
Suggestion:

Since modeling of documents (comparing the document to the struct) is not shown, that information could be omitted. Instead, I think it could be more helpful to identify its purpose in the example.

```suggestion
that matches a query filter. The example populates a ``Restaurant`` struct with the data from the retrieved document.
```

2023-11-01 22:35 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +The filter matches documents where the value of the ``name`` field is ``"Tompkins Square Bagels"``.
Suggestion:

I think that this could be made more concise by assuming that the reader read the previous section that contained similar information ("Pass a query filter...").

```suggestion
The following code example uses a query filter that matches documents in which the value of the ``name`` field is ``"Tompkins Square Bagels"``.

2023-11-01 22:35 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +
Question:

Would it be helpful to explain that they should select the tab that best applies to their usage, or is there some other information in the docs about this that I wasn't able to locate?

I noticed that in [Retrieve Data](https://www.mongodb.com/docs/drivers/rust/current/fundamentals/crud/read-operations/retrieve/), there isn't any information explaining it's the asynchronous version which could be confusing.

2023-11-01 22:35 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +- `Result <{+api+}/error/type.Result.html>`__
Suggestion:

Not sure if you're set on including these sections on every Usage Example page, but I think these repeat info in the Retrieve Data page. I think the page could be made more concise and less repetitive if these sections were replaced by the following:

- Inline API links for the first mention of the types and methods
- Include a link to the Retrieve Data page in the introduction since this information should be covered there

2023-11-02 15:06 UTC, norareidy commented on source/usage-examples/findOne.txt
> +This example finds a document from the ``sample_restaurants.restaurants`` collection
Fixed -- I think all of the other Rust usage ex pages so far have used "sample_restaurants.restaurants," so would be good to standardize that. I'll fix it in one of my open PRs.

2023-11-02 15:14 UTC, norareidy commented on source/usage-examples/findOne.txt
> +
I think including a sentence about selecting the right tab, similar to C# usage examples, is a good idea

2023-11-02 21:18 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +in the Server manual glossary.
Issue:
This sentence repeats the link in the previous sentence.

Suggestion:

I think one of the following actions could resolve this issue:
- Omit the "term" role in the previous section.
- Omit the last sentence since the "term" role in the previous sentence contains the same link.

2023-11-02 21:18 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +the first matching document according to their :term:`natural order` in the database, or
Suggestion:

I think commas before "or" should only be used when it separates an independent clause. Since the phrase starting with "according to the sort order..." isn't an independent clause, it should be omitted.

```suggestion
the first matching document according to their :term:`natural order` in the database or
```

2023-11-02 21:18 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +This example finds a document from the ``sample_restaurants.restaurants`` collection
Thanks. Another suggestion:

I think the description of what document is retrieved (matches the filter) should be placed next to the mention of the document rather than separated by the description of where the document is retrieved from. E.g.

"This example retrieves a document that matches a specified query filter from..."

2023-11-02 21:24 UTC, ccho-mongodb approved these changes
LGTM, a couple minor items to address.

2023-11-02 21:24 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +``Restaurant`` struct with the data from the retrieved document.
Suggestion:

I think the description of what document is retrieved (matches the filter) should be placed next to the mention of the document rather than separated by the description of where the document is retrieved from. E.g.

"This example retrieves a document that matches a specified query filter from..."

Similar suggestion for the find multiple documents usage example (as well as [this comment](https://github.com/mongodb/docs-rust/pull/68#discussion_r1379390868)).

2023-11-03 14:52 UTC, norareidy commented on source/usage-examples/findOne.txt
> +the first matching document according to their :term:`natural order` in the database, or
I think I would still need a comma here, since the phrase following the comma means the same as what precedes (and "or" is used to introduce a synonym/explanation)

2023-11-03 15:01 UTC, ccho-mongodb commented on source/usage-examples/findOne.txt
> +the first matching document according to their :term:`natural order` in the database, or
I think "or" is a conjunction that signals a different item, not a synonym or explanation. When presenting two different items, it should not be preceded by a comma. Let me know if I'm missing something.

2023-11-03 15:09 UTC, merged