DOCSP-30548: monitoring (command, connection pool, cluster topology)
mongodb/docs-rust pull request #69
Opened 2023-11-01 15:36 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30548>
Staging:
- [Cluster](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30548-monitoring/fundamentals/monitoring/cluster-monitoring/)
- [command](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30548-monitoring/fundamentals/monitoring/command-monitoring/)
- [connection pool](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30548-monitoring/fundamentals/monitoring/connection-monitoring/)

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-11-01 21:32 UTC, norareidy requested changes
Nice job, just a few things from me!

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/command-monitoring.txt
> +To learn more about performing operations MongoDB, see the
I:
```suggestion
To learn more about performing MongoDB operations, see the
```

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/command-monitoring.txt
> +- `CommandEventHandler <{+api+}/event/cmap/trait.CommandEventHandler.html>`__
I: broken links

```suggestion
- `CommandEventHandler <{+api+}/event/command/trait.CommandEventHandler.html>`__
```

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/command-monitoring.txt
> +- `handle_command_started_event() <{+api+}/event/cmap/trait.CommandEventHandler.html#method.handle_command_started_event>`__
```suggestion
- `handle_command_started_event() <{+api+}/event/command/trait.CommandEventHandler.html#method.handle_command_started_event>`__
```

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/command-monitoring.txt
> +- `CommandStartedEvent <{+api+}/event/cmap/struct.CommandStartedEvent.html>`__
```suggestion
- `CommandStartedEvent <{+api+}/event/command/struct.CommandStartedEvent.html>`__
```

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/connection-monitoring.txt
> +connections your driver maintains with a MongoDB instance. Connection
S: 
```suggestion
connections that your driver maintains with a MongoDB instance. Connection
```

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/connection-monitoring.txt
> +driver's **connection pool**. A connection pool is a set of open TCP
S: not necessary, but helpful to spell out the full acronym first
```suggestion
driver's **connection pool**. A connection pool is a set of open Transmission Control Protocol (TCP)
```

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/connection-monitoring.txt
> +pools help reduce the number of network handshakes your application
S: "network handshakes" might qualify as [jargon to avoid](https://www.mongodb.com/docs/meta/style-guide/terminology/terms-for-global-audience/#use-jargon-with-care); maybe say something like "number of times new connections are created" instead?

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/connection-monitoring.txt
> +Event Descriptions
S: same suggestion about reordering sections as above

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/connection-monitoring.txt
> +     - Created when an operation fails to acquire a connection for
S: to avoid "fails"

```suggestion
     - Created when an operation cannot acquire a connection for
```

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/cluster-monitoring.txt
> +     - Created when an instance state changes, such as a replica set
S:
```suggestion
     - Created when an instance state changes, such as when a replica set
```

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/cluster-monitoring.txt
> +     - Created when the topology changes, such as an election of a new
S: just to be a little more specific

```suggestion
     - Created when the topology description changes, such as an election of a new
```

2023-11-01 21:32 UTC, norareidy commented on source/fundamentals/monitoring/cluster-monitoring.txt
> +       primary or a ``mongos`` proxy disconnecting.
Q: does the topology description change after a new primary election or mongos proxy disconnection? Or just the topology itself?

2023-11-02 14:07 UTC, rustagir commented on source/fundamentals/monitoring/cluster-monitoring.txt
> +- `SdamEventHandler <{+api+}/event/cmap/trait.SdamEventHandler.html>`__
fixed all

2023-11-02 14:08 UTC, rustagir commented on source/fundamentals/monitoring/command-monitoring.txt
> +- `CommandEventHandler <{+api+}/event/cmap/trait.CommandEventHandler.html>`__
fixed all

2023-11-02 14:12 UTC, rustagir commented on source/fundamentals/monitoring/cluster-monitoring.txt
> +       primary or a ``mongos`` proxy disconnecting.
I think the description follows from the topology, but technically this event only is generated when the description changes

2023-11-02 21:13 UTC, norareidy approved these changes
LGTM!

2023-11-02 21:13 UTC, norareidy commented on source/fundamentals/monitoring/connection-monitoring.txt
> +driver's **connection pool**. A connection pool is a set of open
S: nit, but since "cluster" and "command" aren't bold in the other two monitoring pages, I feel like "connection pool" shouldn't be. I'm actually not sure what the general rule is for bolding terms, so ignore if you want to keep it bold

2023-11-02 21:13 UTC, norareidy commented on source/fundamentals/monitoring/command-monitoring.txt
> +- `CommandStartedEvent <{+api+}/event/command/struct.CommandStartedEvent.html>`__
S: you could also link to CommandFailedEvent and CommandSucceededEvent

2023-11-02 21:13 UTC, norareidy commented on source/fundamentals/monitoring/connection-monitoring.txt
> +- `ConnectionCreatedEvent <{+api+}/event/cmap/struct.ConnectionCreatedEvent.html>`__
S: same suggestion as my comment on cluster monitoring (line 238)

2023-11-02 21:13 UTC, norareidy commented on source/fundamentals/monitoring/cluster-monitoring.txt
> +- `ServerOpeningEvent <{+api+}/event/sdam/struct.ServerOpeningEvent.html>`__
S: it would be a lot to include every event struct mentioned in this list, so I get why you limited to just the one in the event subscription example -- maybe you could link to the API docs in the Event Descriptions table itself (like link all the event names to their api docs)? up to you

2023-11-03 20:41 UTC, isabelatkinson approved these changes

2023-11-03 21:31 UTC, merged