finish setup pages
mongodb/docs-rust pull request #7
Opened 2023-07-17 18:25 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA:
- [DOCSP-30534](https://jira.mongodb.org/browse/DOCSP-30534)
- [DOCSP-30535](https://jira.mongodb.org/browse/DOCSP-30535)
- [DOCSP-30558](https://jira.mongodb.org/browse/DOCSP-30558)

Staging:
- [Crud landing page](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/30528-30534-30535-30558-remaining-setup/fundamentals/crud/)
- [Write ops landing page ](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/30528-30534-30535-30558-remaining-setup/fundamentals/crud/write-operations/)
- [Read ops landing page](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/30528-30534-30535-30558-remaining-setup/fundamentals/crud/read-operations/)
- [Issues & Help](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/30528-30534-30535-30558-remaining-setup/issues-and-help/)

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-07-17 22:24 UTC, ccho-mongodb commented on source/fundamentals/crud.txt
> +  or delete documents.
Issue:

The Chicago Manual of Style requires a subscription, but I was able to find this info (our Style Guide mentions using it for guidance):

https://www.grammarly.com/blog/capitalization-after-colons/#:~:text=Capitalize%20after%20colon%3A%20Chicago,at%20the%20examples%20below%3A

Suggestion:

Use lower case after the colons since the list item is not followed by at least two complete sentences.

2023-07-18 15:02 UTC, ccho-mongodb requested changes
Looks good, identified a few updates I think would help make it easier to understand and more compliant with the style guide.

2023-07-18 15:24 UTC, rustagir commented on source/issues-and-help.txt
> +1. `Create an account and login <https://jira.mongodb.org>`_.
added more instructions

2023-07-18 17:38 UTC, ccho-mongodb approved these changes
LGTM! Left few suggestions and a minor issue.

2023-07-18 17:38 UTC, ccho-mongodb commented on source/issues-and-help.txt
> +#. Navigate to the `RUST JIRA project <https://jira.mongodb.org/browse/RUST>`_.
Question:
Does this need to be a named link or [can it be anonymous](https://github.com/mongodb/docs-rust/pull/7#discussion_r1266822061)?

2023-07-18 17:38 UTC, ccho-mongodb commented on source/issues-and-help.txt
> +   Create an account, then log in to JIRA.
Suggestion:
I think it would be good to avoid comma splices to join two independent clauses. See "How to fix a comma splice" in [this article](https://www.grammarly.com/blog/comma-splice/).

2023-07-18 17:38 UTC, ccho-mongodb commented on source/issues-and-help.txt
> +To get started, clone the source code and create a feature branch with
Suggestion:
I think the correct terminology is clone the "repository" rather than the "source code", so I would use that here.

2023-07-18 17:38 UTC, ccho-mongodb commented on source/issues-and-help.txt
> +JIRA by performing the following steps:
Issue:

I think a comma is required after "JIRA" because it's a nonessential appositive.

Suggestion:

Add the comma as suggested here: https://github.com/mongodb/docs-rust/pull/7#discussion_r1266898321

2023-07-18 17:38 UTC, ccho-mongodb commented on source/issues-and-help.txt
> +`{+driver-short+} repository <https://github.com/mongodb/mongo-rust-driver>`__ on GitHub.
👍

2023-07-18 17:38 UTC, ccho-mongodb commented on source/issues-and-help.txt
> +After making changes, follow the `testing guidelines
Suggestion:

I think it could be helpful to specify the type of changes that would require running tests, e.g.:
"After making any code changes"

2023-07-18 18:23 UTC, rustagir commented on source/issues-and-help.txt
> +#. Navigate to the `RUST JIRA project <https://jira.mongodb.org/browse/RUST>`_.
fixed

2023-07-18 18:35 UTC, merged