DOCSP-30520: distinct usage example
mongodb/docs-rust pull request #72
Opened 2023-11-02 18:58 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30520>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30520-distinct-usageex/usage-examples/distinct/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?

2023-11-02 21:23 UTC, jordan-smith721 requested changes
Just a couple suggestions!

2023-11-02 21:23 UTC, jordan-smith721 commented on source/usage-examples/distinct.txt
> +method on a ``Collection`` instance.
This sentence was confusing to me. I think the "across a collection" part makes it less clear. It might be more clear worded something like this:

```suggestion
You can list the values of a field that are distinct from one another across a collection
by calling the `distinct() <{+api+}/struct.Collection.html#method.distinct>`__
method on a ``Collection`` instance.
```

2023-11-02 21:23 UTC, jordan-smith721 commented on source/usage-examples/distinct.txt
> +a parameter to find distinct values only in a subset of matched
Suggestion: The first time I read this I read it as "to find distinct values only..." where only is referring to "distinct values" rather than "only in a subset." (hope that explanation makes sense)  
 
```suggestion
the distinct values for that field. You can also pass a query filter as
a parameter to find distinct values from only a subset of matched
```

2023-11-02 21:23 UTC, jordan-smith721 commented on source/usage-examples/distinct.txt
> +``restaurants`` collection of the ``sample_restaurants`` database. The
Similar to my comment earlier, I think "for a field across the collection" makes the sentence a little harder to understand. 

```suggestion
This example finds values for a field that are distinct across the
``restaurants`` collection of the ``sample_restaurants`` database. The
```

2023-11-02 21:23 UTC, jordan-smith721 commented on source/usage-examples/distinct.txt
> +is ``"Turkish"``.
```suggestion
is ``"Turkish"``:
```

2023-11-03 14:01 UTC, rustagir commented on source/usage-examples/distinct.txt
> +method on a ``Collection`` instance.
should I just remove the phrase "across a collection" instead? Is this implicit in the fact that you call the method on a `Collection` instance?

2023-11-03 14:04 UTC, rustagir commented on source/usage-examples/distinct.txt
> +``restaurants`` collection of the ``sample_restaurants`` database. The
What about "distinct field values"

2023-11-03 14:04 UTC, rustagir commented on source/usage-examples/distinct.txt
> +is ``"Turkish"``.
will change in all merged UEs

2023-11-06 20:09 UTC, jordan-smith721 commented on source/usage-examples/distinct.txt
> +method on a ``Collection`` instance.
Yeah you're right, I think since it's pointed out that it's being called on `Collection` makes it implicit that it's "across the collection." Maybe removing "across the collection" and then phrasing it as "distinct field values" (like it is in the examples section) makes it feel more clear IMO. So:

"You can list the distinct field values of a document by calling the . . . "

2023-11-06 20:11 UTC, jordan-smith721 approved these changes
I left one follow up comment on the opening sentence in the overview. Otherwise LGTM!

2023-11-06 21:33 UTC, merged