DOCSP-34105: Update by ID example
mongodb/docs-rust pull request #79
Opened 2023-11-06 20:21 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-34105>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-11-06 21:48 UTC, rustagir requested changes
a few content changes requested

2023-11-06 21:48 UTC, rustagir commented on source/fundamentals/crud/write-operations/change.txt
> +document's unique ``"_id"`` value. Then, the code performs an update operation with the
```suggestion
document's unique ``_id`` value. Then, the code performs an update operation with the
```

2023-11-06 21:48 UTC, rustagir commented on source/fundamentals/crud/write-operations/change.txt
> +``update_one()`` method. The method has the following parameters:
```suggestion
``update_one()`` method. The ``update_one()`` takes the following parameters:
```

2023-11-06 21:48 UTC, rustagir commented on source/fundamentals/crud/write-operations/change.txt
> +      Modified 1 document(s)
S: To avoid the failing vale checks, can you change the printed output to be
"Modified documents: 1"

across this page and in the referenced code examples? Sorry it is out of scope for the other examples on this page, but a good proactive change.

2023-11-06 21:48 UTC, rustagir commented on source/fundamentals/crud/write-operations/change.txt
> +   page in the Server manual.
S: I don't think it's necessary to call out that users _id field might be different. If a user wants to copy this example, they probably would just copy and paste the sample document and insert it.

Instead, this note could be a tip and just cross link.

2023-11-06 21:48 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/change.rs
>      println!("Modified {} document(s)", res.modified_count);
S: change this to not fail the vale check as mentioned in my previous comments (all examples)

2023-11-06 21:48 UTC, rustagir commented on source/includes/fundamentals/code-snippets/crud/change.rs
> +    let filter = doc! { "_id": ObjectId::from_str("4501").expect("Could not convert to ObjectId") };
I: I didnt realize this page already contained am objectid operation. It it out of scope for the ticket, but now that this api is shown in the correct section, can you change this example (code and text on page) to be simpler, as in querying by name or something? LMK if you want to discuss more what I mean if i wasnt descriptive enough!

2023-11-06 22:19 UTC, norareidy commented on source/fundamentals/crud/write-operations/change.txt
> +      Modified 1 document(s)
Very quick change so no worries!

2023-11-06 22:22 UTC, norareidy commented on source/includes/fundamentals/code-snippets/crud/change.rs
> +    let filter = doc! { "_id": ObjectId::from_str("4501").expect("Could not convert to ObjectId") };
This makes a lot of sense, changed!

2023-11-07 17:00 UTC, rustagir approved these changes
a few small last suggestions, lmk if you want another look before merging

2023-11-07 17:00 UTC, rustagir commented on source/fundamentals/crud/write-operations/change.txt
>  The following shows the updated documents resulting from the preceding update operation:
S: this sentence sounds disjointed right now with just "The following..." , not sure if "code" is the right word here, though, but it is probably fine

Change everywhere on this page.

```suggestion
The following code shows the updated documents resulting from the preceding update operation:
```

2023-11-09 17:01 UTC, merged