DOCSP-30552: Collations guide
mongodb/docs-rust pull request #82
Opened 2023-11-08 22:15 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30552>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-11-10 17:01 UTC, rustagir requested changes
a few things, happy to talk to fine tune anything

2023-11-10 17:01 UTC, rustagir commented on source/fundamentals/collations.txt
> +   { "name" : "Ça", "length" : "1138" }
S: Instead of including the output, can you just give more detail in the preceding paragrah about what the matches are when they are compared as strings? For example, When the length values are compared as strings, 474 is considered alphabetically after 1000.

2023-11-10 17:01 UTC, rustagir commented on source/includes/fundamentals/code-snippets/collation.rs
> +
S: remove white space where unnecessary

2023-11-13 21:49 UTC, rustagir requested changes
a few more things, but great job responding to comments!

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +
S: add meta tags!

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +ordering conventions that apply to a specific language and locale.
S: "that apply to" could be confusing here. Could you use "based on" or "that correspond to"?
The conventions actually apply to your data/results, so I think this sentence should be more clear.

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +  to both the default collation and a custom collation
```suggestion
- :ref:`rust-mongodb-collations` describes how MongoDB sorts string values according
  to the default collation and custom collations
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +  using builder functions
S: remove some detail
```suggestion
- :ref:`rust-specify-collation` describes how to create a ``Collation`` struct instance
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +  delete operations
```suggestion
- :ref:`rust-op-collation` describes how to apply a collation to CRUD operations
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +method uses the `ASCII standard <https://en.wikipedia.org/wiki/ASCII>`_
S: use a permanent link. Also, per the style guide, make link text clear. Perhaps you can move the wiki to a tip
```suggestion
method uses the `ASCII standard <https://en.wikipedia.org/wiki/ASCII>`_
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +is lower than the "ô" character value.
Q: what do you mean by "lower" here?

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +is lower than the "ô" character value.
Should this be reversed?

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +You can define a collation by specifying your collation locale and related options in a
```suggestion
You can define a collation by specifying a collation locale and other options in a
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +   by chaining option builder functions one at a time.
```suggestion
   by chaining option builder methods.
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +   by chaining option builder functions one at a time.
use method for consistency with docs set

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +are optional:
```suggestion
The following table describes the builder methods that you can use to set fields of a ``Collation`` instance.
You must use the ``locale()`` function to build a valid ``Collation`` struct, but all other builder functions
are optional:
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +to build a ``CreateCollectionOptions`` instance. Then, call the ``create_collection()``
```suggestion
called on that collection. Set the collation by using the ``collation()`` function
when creating a ``CreateCollectionOptions`` instance. Then, call the ``create_collection()``
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +to the ``"fr"``, or French, locale conventions. The ``strength`` field is set to
S: reverse the two clauses of this setnece to alogn with the order of the code

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +Use the Collection's Collation Example
S: right now, this title is a little hard to follow. Perhaps something like "Collation ordering demonstration" would be more apt? Happy to brainstorm!

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +from the results.
```suggestion
These rules place words beginning with "Ç" after those beginning with "I". So, when the preceding find
operation follows binary collation rules, the document with the ``name`` value of ``"Ça"`` does not match
the filter criteria.
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +the collation covers the query.
S: omit the last sentence by integrating it with the first sentence
```suggestion
When you create a new index on a collection, you can define the collation for operations
that are covered by the index. To run an operation that uses the index and its collation, your operation
and index must specify the same collation.
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +``name`` field and specifies a new collation with an ``"en_US"`` locale:
S: avoid with
```suggestion
``name`` field and specifies a new collation corresponding to the ``"en_US"`` locale:
```

2023-11-13 21:49 UTC, rustagir commented on source/fundamentals/collations.txt
> +collection.
```suggestion
collection or index.
```

2023-11-14 16:32 UTC, norareidy commented on source/fundamentals/collations.txt
> +is lower than the "ô" character value.
I meant a lower ASCII code value, but yeah it's confusing so I will reword

2023-11-14 16:57 UTC, norareidy commented on source/fundamentals/collations.txt
> +Use the Collection's Collation Example
I was a little hesitant about just titling it "Collation Ordering Demonstration" since that doesn't mention that it's using the collation set for the collection, but since it's a subheading under "Set a Collation on a Collection" I feel like it does work -- changed!

2023-11-14 21:11 UTC, rustagir approved these changes
approved with two small suggestions, great job!

2023-11-14 21:11 UTC, rustagir commented on source/fundamentals/collations.txt
> +   page.
S: there's a wiki role!
```suggestion
   To learn more about the ASCII standard, see the :wikipedia:`ASCII <w/index.php?title=ASCII&oldid=1180396712>` 
   Wikipedia page.
```

2023-11-14 21:11 UTC, rustagir commented on source/fundamentals/collations.txt
> +   côté
S: set copyable false for these two blocks

2023-11-15 16:32 UTC, merged

2023-11-16 20:36 UTC, kevinAlbs reviewed
LGTM