DOCSP-30555: transactions guide
mongodb/docs-rust pull request #87
Opened 2023-11-16 19:30 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30555>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30555-txns/fundamentals/transactions/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2023-11-17 22:00 UTC, norareidy requested changes
Looks good, a few suggestions!

2023-11-17 22:00 UTC, norareidy commented on source/fundamentals/transactions.txt
> +visible. This feature is called atomicity.
S: I feel like bolding "atomicity" here would be good

2023-11-17 22:00 UTC, norareidy commented on source/fundamentals/transactions.txt
> +of operations and allow you to execute operations in an ACID-compliant transaction.
S: unsure if you need to add definitions of "causal consistency" and "ACID-compliant" or if we should just assume that the reader knows what these mean, but I think explaining ACID at least would help clarify. I.e., "... in an ACID-compliant transaction, or a transaction that maintains the atomicity, consistency, isolation, and durability of the database"

2023-11-17 22:00 UTC, norareidy commented on source/fundamentals/transactions.txt
> +``Client`` instance as a ``ClientSession`` type. You can improve your
S: "in" the driver seems a little confusing

```suggestion
When using the {+driver-short+}, you can create a new session from a
``Client`` instance as a ``ClientSession`` type. You can improve your
```

2023-11-17 22:00 UTC, norareidy commented on source/fundamentals/transactions.txt
> +     - | Commits the active transaction for this session. Returns an
S: following the format of most other table descriptions, I think you could keep the first sentence as a fragment but ensure that the following are complete sentences.

```suggestion
     - | Commits the active transaction for this session. This method returns an
```

2023-11-17 22:00 UTC, norareidy commented on source/fundamentals/transactions.txt
> +     - | Ends the active transaction for this session. Returns an
S: same suggestion as above (line 78)

2023-11-17 22:00 UTC, norareidy commented on source/fundamentals/transactions.txt
> +         handles any errors, so you do not need to implement error
S: for vale reasons

```suggestion
         handles any errors, so you can omit error
```

2023-11-17 22:00 UTC, norareidy commented on source/fundamentals/transactions.txt
> +   For example, to delete a document normally, you can use the
S: I feel like "normally" is a little subjective

```suggestion
   For example, to delete a document, you can generally use the
```

2023-11-17 22:00 UTC, norareidy commented on source/fundamentals/transactions.txt
> +The following code performs the following actions to perform the
S: just to avoid repeating "perform"

```suggestion
The following code performs the following actions to complete the
```

2023-11-17 22:00 UTC, norareidy commented on source/fundamentals/transactions.txt
> +If you need more control over your transactions, the `ClientSession API
S: to avoid need

```suggestion
If you require more control over your transactions, the `ClientSession API
```

2023-11-17 22:00 UTC, norareidy commented on source/includes/fundamentals/code-snippets/transaction.rs
> +            "name": "Sula".to_string(),
Q: do you need to use to_string() here (and elsewhere in this file)?

2023-11-20 16:42 UTC, rustagir commented on source/includes/fundamentals/code-snippets/transaction.rs
> +            "name": "Sula".to_string(),
yes, because the `&str` type is different than the `String` type

2023-11-20 20:03 UTC, norareidy approved these changes
LGTM!

2023-11-20 20:03 UTC, norareidy commented on source/includes/fundamentals/code-snippets/transaction.rs
> +            "name": "Sula".to_string(),
I ran the code without `to_string()` and got the same results, with the Atlas database identifying the data type as "String" either way -- this is very nitpicky so no need to change anything unless you feel inclined

2023-11-20 20:03 UTC, norareidy commented on source/fundamentals/transactions.txt
> +of operations and allow you to execute operations in an **ACID-compliant**
S: since the style guide doesn't like "execute"

```suggestion
of operations and allow you to run operations in an **ACID-compliant**
```

2023-11-21 15:42 UTC, kevinAlbs approved these changes
LGTM with two small suggestions.

2023-11-21 15:42 UTC, kevinAlbs commented on source/fundamentals/transactions.txt
> +         indicates that the entire transaction can be retried with the
```suggestion
         indicates that the entire transaction can be aborted then retried with the
```

If a transaction is not aborted before the retry, calling `start_transaction` on the same session results in a "transaction in progress" error.

2023-11-22 19:49 UTC, merged