DOCSP-30550: GridFS guide
mongodb/docs-rust pull request #89
Opened 2023-11-22 21:36 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30550>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2023-11-27 18:25 UTC, rachel-mack reviewed
Still in progress

2023-11-27 18:25 UTC, rachel-mack commented on source/fundamentals/gridfs.txt
> +a new GridFS bucket:
```suggestion
To upload new files or access existing ones, create a reference to a GridFS bucket.

The following example calls the ``gridfs_bucket()`` method on a database to create a reference to a either a new GridFS bucket or an existing one:
```

2023-11-27 18:25 UTC, rachel-mack commented on source/fundamentals/gridfs.txt
> +You can specify a custom bucket name and other options in a ``GridFsBucketOptions``
Is there a default name?

2023-11-27 18:25 UTC, rachel-mack commented on source/includes/fundamentals/code-snippets/gridfs.rs
> +        .build();
It might be useful to add include an example of specifying an option with a labeled value.

Like does including `write_concern(WriteConcern::w_timeout: 120)` make sense?

2023-11-27 18:25 UTC, rachel-mack commented on source/fundamentals/gridfs.txt
> +The following example specifies a ``GridFsBucketOptions`` instance and creates a
Again, because the creation doesn't happen until the first write operation:
```suggestion
The following example specifies a ``GridFsBucketOptions`` instance and references a
```

2023-11-27 19:15 UTC, ccho-mongodb commented on source/fundamentals/gridfs.txt
> +a new GridFS bucket:
Suggestion:
I think the first sentence should provide more information about the subject ("how to upload files"). While "create a reference" is a necessary step, it doesn't describe how to upload. Perhaps separating out "upload new files" and "access existing [files]" could be separated into two sentences so that each sentence could explain how to accomplish the complete task. E.g.

"To access an existing bucket, call the gridfs_bucket() on the database that contains the GridFS bucket. To upload a file to that bucket, call the ... method on the instance of the bucket."

2023-11-27 19:31 UTC, rachel-mack requested changes
Remaining comments

2023-11-27 21:18 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +  for types and methods mentioned in this guide
The titles in the TOC are descriptive enough to help a user find what they need, so good job there!

2023-11-27 21:38 UTC, mongoKart reviewed
nice job, @norareidy and @rachel-mack

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +MongoDB using **GridFS**. GridFS is a specification that describes how
```suggestion
MongoDB by using **GridFS**. GridFS is a specification that describes how
```

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +memory. For more detailed information on whether GridFS is suitable for your
```suggestion
memory. For more detailed information about whether GridFS is suitable for your
```

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +GridFS organizes files in a **bucket**, a group of MongoDB collections
Either one seems fine to me; the suggestion is wordier, but probably clearer. The SG doesn't specifically discuss this case or clarifying non-restrictive clauses.

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +- ``files``, which stores the file metadata
this got me too--the singular collection "chunks" has a plural name, so i think the original is right

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +collection to ensure efficient retrieval of files and related
I think a list is fine here, but SG suggests [not introducing lists with fragments.](https://www.mongodb.com/docs/meta/style-guide/style/lists/#:~:text=Avoid%20using%20fragments%20to%20introduce%20lists.%20Fragments%20can%20be%20harder%20to%20understand%20than%20sentences.) List items should also be capitalized.

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +files when uploading to a bucket:
If you want to keep the list, I'd probably keep the bit about dividing the files into smaller pieces. Should also capitalize the list items and reword the intro so it [doesn't end with "the following".](https://www.mongodb.com/docs/meta/style-guide/style/lists/#:~:text=Don%E2%80%99t%20tell%20users%20to%20%22do%20the%20following.%22%20The%20verb%20do%20is%20weak%2C%20using%20following%20as%20a%20noun%20in%20this%20context%20is%20incorrect%2C%20and%20the%20whole%20phrase%20is%20ambiguous.)

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +Create a GridFS Bucket
^^^ worth clarifying for sure

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +with your file bytes as a parameter to upload the file.
```suggestion
and pass your file bytes as a parameter to upload the file.
```

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +file bytes.
```suggestion
Then, call the ``read_to_end()`` method and pass a vector parameter to read and store the
file bytes.
```

will a user know what a vector parameter is?

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +The following example uses an download stream to download a file with an ``_id`` value
```suggestion
The following example uses a download stream to download a file with an ``_id`` value
```

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +   want to rename, and pass each value in separate calls to the ``rename()``
```suggestion
   want to rename, and pass each ``_id`` value in separate calls to the ``rename()``
```

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +   method.
makes sense

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +   the ``_id`` field from the files you want to delete, and pass each value
```suggestion
   the ``_id`` field from the files you want to delete, and pass each ``_id`` value
```

2023-11-27 21:38 UTC, mongoKart commented on source/fundamentals/gridfs.txt
> +The following example deletes the file in which the ``_id`` value is ``3289``:
```suggestion
The following example deletes the file in which the value of the ``_id`` field is ``3289``:
```

2023-11-28 18:38 UTC, norareidy commented on source/fundamentals/gridfs.txt
> +GridFS organizes files in a **bucket**, a group of MongoDB collections
I added "which is" for clarity, but reworded slightly to make it less wordy

2023-11-28 18:52 UTC, norareidy commented on source/fundamentals/gridfs.txt
> +they do not exist and when the bucket is empty. For more information on
I reworded, hopefully it's more clear now

2023-11-28 19:22 UTC, norareidy commented on source/fundamentals/gridfs.txt
> +You can specify a custom bucket name and other options in a ``GridFsBucketOptions``
Yes the default name is "fs" -- I included that in the table, do you think I should mention outside the table as well?

2023-11-28 19:53 UTC, norareidy commented on source/fundamentals/gridfs.txt
> +When you create a new GridFS bucket, the {+driver-short+} creates the ``chunks``
Based on the other drivers' GridFS pages and the Server docs, my understanding is that the driver does this work

2023-11-28 20:01 UTC, norareidy commented on source/fundamentals/gridfs.txt
> +Create a GridFS Bucket
Really good point, I did some experimenting to make sure but yes, the bucket is only created upon the first write operation. Changed!

2023-11-28 20:10 UTC, norareidy commented on source/fundamentals/gridfs.txt
> +a new GridFS bucket:
Since the following section ("Upload Files") explains how to upload a file, I don't think that info is needed here. I did reword this part of the "Reference a GridFS Bucket" section though to make it more clear.

2023-11-28 20:20 UTC, norareidy commented on source/fundamentals/gridfs.txt
> +   method.
Added an example! I think it might be a little repetitive, since the example isn't much different from the preceding one other than the number of times `rename()` is used, but let me know what you think

2023-11-28 20:52 UTC, norareidy commented on source/includes/fundamentals/code-snippets/gridfs.rs
> +        .build();
I included a 5 second timeout

2023-11-29 12:30 UTC, rachel-mack commented on source/fundamentals/gridfs.txt
> +You can specify a custom bucket name and other options in a ``GridFsBucketOptions``
I missed that, I think the table is sufficient.

2023-11-29 12:42 UTC, rachel-mack approved these changes
LGTM - just one suggestion.

2023-11-29 12:42 UTC, rachel-mack commented on source/includes/fundamentals/code-snippets/gridfs.rs
> +    // end-rename-many
I see what you mean by repetitive. I was thinking of using a loop over an array of id numbers.
In the case of loop, it would give the user something more useful to copy and paste.

So, I would either go back to using the note, but suggest using an array, or update the example to loop over an array.

2023-12-06 17:28 UTC, merged