DOCSP-31470: describe connection pool in perf page
mongodb/docs-rust pull request #93
Opened 2023-12-05 19:25 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-31470>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-31470-conn-pool-perf/fundamentals/performance/#connection-pool

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2023-12-05 21:58 UTC, norareidy requested changes
Really clear, just a few suggestions!

2023-12-05 21:58 UTC, norareidy commented on source/fundamentals/performance.txt
> +that server will wait until a connection becomes available.
S: since the style guide likes present tense

```suggestion
that server waits until a connection becomes available.
```

2023-12-05 21:58 UTC, norareidy commented on source/fundamentals/performance.txt
> +while specifying a value for ``max_pool_size``:
S: nitpicky suggestion, but since the focus is how to increase `max_pool_size`, I think this wording would be better:

```suggestion
option. The following code demonstrates how to specify a value for ``max_pool_size`` when instantiating a ``Client``:
```

2023-12-05 21:58 UTC, norareidy commented on source/fundamentals/performance.txt
> +  rate-limits on connection creation.
S: I don't think the hyphen is necessary (unless rate-limit is usually written that way)

```suggestion
  rate limits on connection creation.
```

2023-12-05 21:58 UTC, norareidy commented on source/fundamentals/performance.txt
> +idle, to drop below the minimum, the connection pool opens more sockets until the
I:

```suggestion
idle, drops below the minimum, the connection pool opens more sockets until the
```

2023-12-05 21:58 UTC, norareidy commented on source/fundamentals/performance.txt
> +pool removes and replaces it. This option defaults to ``0``, or no limit.
S: just to clarify "it"

```suggestion
pool removes and replaces that connection. This option defaults to ``0``, or no limit.
```

2023-12-05 21:58 UTC, norareidy commented on source/fundamentals/performance.txt
> +  than ``max_pool_size`` connections in the pool.
S: I think using the option's name as a stand-in for a value itself is a little confusing; you could reword to something like this:

```suggestion
- The connection pool finishes creating a connection and the number of connections in the pool is less than the value of ``max_pool_size``.
```

2023-12-05 21:58 UTC, norareidy commented on source/fundamentals/performance.txt
> +  than ``max_pool_size`` connections in the pool.
Applies elsewhere on the page (line 132)

2023-12-06 20:34 UTC, norareidy approved these changes
LGTM with one suggestion!

2023-12-06 20:34 UTC, norareidy commented on source/fundamentals/performance.txt
> +``2``, as is by default, the third request that attempts to concurrently
S: the wording of "as is by default" seems a little clunky, could be:

```suggestion
``2``, its default value, the third request that attempts to concurrently
```

2023-12-06 21:33 UTC, kevinAlbs approved these changes
LGTM with one comment

2023-12-06 21:33 UTC, kevinAlbs commented on source/fundamentals/performance.txt
> +  connections in the pool is less than the value of ``max_pool_size``.
```suggestion
  connections in the pool is less than or equal to the value of ``max_pool_size``.
```

2023-12-07 15:55 UTC, merged