DOCSP-30508: whats new
mongodb/docs-rust pull request #94
Opened 2023-12-06 19:45 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30508>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30508-whats-new/whats-new/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2023-12-06 21:57 UTC, ccho-mongodb requested changes
I learned a lot about the Rust driver from this info!

I found a couple issues with the consistency of the list items and how they're introduced that might some require larger changes, so I think it would be good to take another look.

2023-12-06 21:57 UTC, ccho-mongodb commented on source/whats-new.txt
> +  version 7.0 release.
Suggestion:

I think this could be more specific as to how the wire version change could potentially impact the reader. I wasn't able to understand whether this means that the wire version "21" enables certain functionality or if 7.0 requires "21".

2023-12-06 21:57 UTC, ccho-mongodb commented on source/whats-new.txt
> +- Updates the ``libmongocrypt`` version to use FLE2 version 2.
Suggestion:

1) I think the relation with libmongocrypt should be clarified. 
2) I think FLE2 version 2 might not be the official name. As far as I can tell, this should be [Queryable Encryption](https://www.mongodb.com/docs/manual/core/queryable-encryption/). If it is emphasizing some part that it was previously incompatible with, I think that should be mentioned here.

Perhaps something like this could address both points:
"Updates the libmongocrypt version in the driver dependencies in order to use Queryable Encryption with equality queries."

2023-12-06 21:57 UTC, ccho-mongodb commented on source/whats-new.txt
> +  serialize values given to CRUD methods as human readable. By default,
Issue:
I think number of prepositions in this sentence make it difficult to understand, especially the last part:
"configure the driver to serialize values given to CRUD methods as human readable".

Suggestion:
I think it could be good to break up the information or omit the parts that are not essential.

Perhaps something like this could work:

"Adds the \`\`human_readable_serialization\`\` option to \`\`CollectionOptions\`\` struct. You can use this setting to instruct the driver to serialize document data to a human readable format."

2023-12-06 21:57 UTC, ccho-mongodb commented on source/whats-new.txt
> +  the value of ``human_readable_serialization`` is ``false``, and
Suggestion:

I think the contrast between "true" and "false" could be more clear by separating them with sentences instead of making them independent clauses in the same sentence without signal words that indicate contrast. I think the independent clause at the end also talks about a performance tip, which could be important to draw reader attention to, perhaps in an admonition.

First clause:
"The default setting of ... is false."
Second clause:
"(warning admonition) If you enable this feature by setting it to \`\`true\`\`, insert operations may run more slowly."

2023-12-06 21:57 UTC, ccho-mongodb commented on source/whats-new.txt
> +    new connections up to the number of connections specified in the
Suggestion:

I think "up to ..." is usually used when preceded by the initial number rather than an adjective such as "new". E.g. "from 20 up to 100"

I think separating the purpose of the method and number of connections that it creates could be easier to understand. 

E.g.
"You can use ... method to instruct the driver to start adding new connections to the connection pool which can provide more predictable performance. This method attempts to create up to the number of connections defined in the min_pool_size setting."

2023-12-06 21:57 UTC, ccho-mongodb commented on source/whats-new.txt
> +    you use even handlers to reference external resources, as these
Issue:

I think this is a typo. Or, should "even" be omitted such that it's not a specific type of handler?

```suggestion
    you use event handlers to reference external resources, as these
```

2023-12-06 21:57 UTC, ccho-mongodb commented on source/whats-new.txt
> +  string that includes database and collection names, such as
Suggestion:

I think "parse" is usually used in the direction of reading a string and converting it to something else.

E.g.
"parse a string that includes a database and collection name, such as testdb.testcollection, into a Namespace instance".

2023-12-07 17:41 UTC, rustagir commented on source/whats-new.txt
> +   the driver source code on Github.
Instead of having this link, I can just link to the release notes for each release at the end of each version section as is done here: https://github.com/mongodb/docs-node/blob/3544d777c390fea8635ddea1a1e9092967abd179/source/whats-new.txt#L85-L87

2023-12-07 17:59 UTC, rustagir commented on source/whats-new.txt
> +  version 7.0 release.
From my research, the max wire version is the the latest version of the wire protocol that the instance is capable of using to communicate with clients.
In the associated RUST ticket, it looks like this is mostly for the compatibility check, and wont affect users, so I think I can remove.

2023-12-11 16:22 UTC, merged