DOCSP-30527: tls guide
mongodb/docs-rust pull request #96
Opened 2023-12-11 15:43 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-30527>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30527-tls/fundamentals/connections/tls/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2023-12-11 16:54 UTC, norareidy requested changes
A few suggestions, but looks really good!

2023-12-11 16:54 UTC, norareidy commented on source/fundamentals/connections/tls.txt
> +For a full list of client options, see :ref:`rust-connection-options`.
S:

```suggestion
For a full list of client options, see the :ref:`rust-connection-options` page.
```

2023-12-11 16:54 UTC, norareidy commented on source/fundamentals/connections/tls.txt
> +certificates must be stored as PEM files to enable TLS when connecting.
S: I think this sentence seems a little incomplete without specifying what you're connecting to

```suggestion
certificates must be stored as PEM files to enable TLS when connecting to a MongoDB deployment.
```

2023-12-11 16:54 UTC, norareidy commented on source/fundamentals/connections/tls.txt
> +     - One or more certificate authorities to
S: I don't think this description (or the other table descriptions, other than the one that's two sentences) needs a period since it's a sentence fragment

2023-12-11 16:54 UTC, norareidy commented on source/fundamentals/connections/tls.txt
> +instance and a ``Client`` instance with TLS enabled:
S: to avoid "with"

```suggestion
instance and a ``Client`` instance that has TLS enabled:
```

2023-12-11 16:54 UTC, norareidy commented on source/fundamentals/connections/tls.txt
> +  ``Tls`` enum and creating a ``ClientOptions`` instance with those options
S: Since the `ClientOptions` instance is created first, I think this description should be reworded a bit; also, it's a little unclear

```suggestion
- Setting the ``tls`` field of a ``ClientOptions`` instance to ``Tls::Enabled`` and instantiating a ``Client`` with those options
```

2023-12-11 16:54 UTC, norareidy commented on source/fundamentals/connections/tls.txt
> +to set fields to reference your certificate files.
S: since you mention the specific optional fields in the next paragraph, I think it makes sense to mention the specific required fields that you need to set
```suggestion
to set the ``ca_file_path`` and ``cert_key_file_path`` fields to reference your certificate files.
```

2023-12-11 16:54 UTC, norareidy commented on source/includes/fundamentals/code-snippets/tls.rs
> +    let ca_file = PathBuf::from(r"path to CA certificate");
S:
```suggestion
    let ca_file = PathBuf::from(r"<path to CA certificate>");
```

2023-12-11 16:54 UTC, norareidy commented on source/fundamentals/connections/tls.txt
> +In this guide, you can learn how to use the TLS protocol to secure
S: not necessary, but could be helpful to bold this term

```suggestion
In this guide, you can learn how to use the **TLS protocol** to secure 
```

2023-12-11 17:21 UTC, rustagir commented on source/fundamentals/connections/tls.txt
> +In this guide, you can learn how to use the TLS protocol to secure
also added a definition

2023-12-12 15:11 UTC, norareidy approved these changes
LGTM with one comment!

2023-12-12 15:11 UTC, norareidy commented on source/fundamentals/connections/tls.txt
> +certificates must be stored as PEM files to enable TLS when connecting
Q: should we assume the reader knows what PEM files are? Might be helpful to briefly explain

2023-12-12 16:08 UTC, rustagir commented on source/fundamentals/connections/tls.txt
> +certificates must be stored as PEM files to enable TLS when connecting
sure, added a little explanation

2023-12-12 16:09 UTC, merged