DOCSP-34184: Atlas Search indexes
mongodb/docs-rust pull request #99
Opened 2023-12-12 21:15 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-rust/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-34184>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2023-12-13 17:58 UTC, rustagir requested changes
a few things but looks really good!

2023-12-13 17:58 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +``"static_index"`` on the ``posts`` collection. The code specifies ``SearchIndexModel``
S: since these are not string values but index names, I don't think they need "" quotes. Applies throughout where index names are mentioned.
```suggestion
The following example creates two Atlas Search indexes, ``dynamic_index`` and
``static_index``, on the ``posts`` collection. The code specifies ``SearchIndexModel``
```

2023-12-13 17:58 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +method accepts the following parameters:
```suggestion
You can access information about a collection's existing Atlas Search indexes
by calling the ``list_search_indexes()`` method on the collection. This
method accepts the following parameters:
```

2023-12-13 17:58 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +to return information about all Atlas Search indexes without configuring options.
```suggestion
to return information about all Atlas Search indexes with default options.
```

2023-12-13 17:58 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +Then, the code iterates through the indexes and prints their information:
```suggestion
Then, the code outputs the names of the Search indexes:
```

2023-12-13 17:58 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +   :dedent:
I: should there be output here?

2023-12-13 17:58 UTC, rustagir commented on source/includes/fundamentals/code-snippets/indexes.rs
> +        .build();
I: avoid using numbers in variable names. Maybe you can call these variables `dyn_idx` and `static_idx` or something

2023-12-13 17:58 UTC, rustagir commented on source/whats-new.txt
> +  these methods, see the :ref:`rust-atlas-search-indexes` guide.
```suggestion
- Adds MongoDB Atlas Search index management methods. To learn more about
  these methods, see the :ref:`rust-atlas-search-indexes` guide.
```

2023-12-13 23:23 UTC, norareidy commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +Then, the code iterates through the indexes and prints their information:
Fixed with slightly different wording, since the example outputs all index information (not just the names)

2023-12-14 15:01 UTC, norareidy commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +allow you to use MongoDB's Atlas Search feature, which performs fast, full-text searches
I changed "which performs" to "to perform" and I think it resolves the personification issue, lmk what you think

2023-12-14 15:01 UTC, norareidy commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +which fields to index in one of the following ways:
They don't need to be strings; there are a few data types that aren't supported, but most are

2023-12-14 15:02 UTC, norareidy commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +  supported field types
I think it's more clear now after some restructuring, but lmk what you think

2023-12-14 15:40 UTC, rustagir requested changes
Looks really good! a few more suggestions

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +on data stored in an Atlas cluster. The Atlas Search index configures the behavior of Atlas
```suggestion
on data stored in an Atlas cluster. An Atlas Search index configures the behavior of Atlas
```

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +call the ``SearchIndexModel::builder()`` method.
S: I think starting this paragraph with "Before creating a search index..." is confusing because building a `SearchIndexModel` is part of the process of creating the search index.
Perhaps this could clarify:

```suggestion
To create an Atlas Search index, you must first must build a ``SearchIndexModel`` instance
that sets your index specifications. To begin building a ``SearchIndexModel`` instance,
call the ``SearchIndexModel::builder()`` method.
```

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +index only certain specified fields, enable static mappings by setting the ``mappings.dynamic``
S: redundant
```suggestion
index only specified fields, enable static mappings by setting the ``mappings.dynamic``
```

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +nested field to ``false`` and including a list of target fields.
```suggestion
nested field to ``false`` and including a list of fields you want to index.
```

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +.. note:: Instantiating Options
S: since this is not an options object, rename the title
```suggestion
.. note:: Instantiating Models
```

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +The following example creates instructions for a index named ``example_index`` in a
S: "Creates instructions" in this context sounds incomplete
```suggestion
The following example creates specifications for a index named ``example_index`` in a
```

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +and ``date`` fields by enabling static mappings:
```suggestion
``SearchIndexModel`` instance. The code sets a static mapping to index only the ``body``
and ``date`` fields:
```

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +your collection. This method accepts the following parameters:
```suggestion
You can create an Atlas Search index on a collection by calling the ``create_search_index()`` method on
a ``Collection`` instance. This method accepts the following parameters:
```

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +to set the index name and definition. Then, the code passes the ``SearchIndexModel``
S: remove unnecessary details
```suggestion
The code creates a ``SearchIndexModel`` that sets dynamic mapping and the index name.
Then, the code passes the ``SearchIndexModel``
```

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +instance to the ``create_search_index()`` method to dynamically index collection fields:
```suggestion
instance to the ``create_search_index()`` method to create the Search index:
```

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +your collection. This method accepts the following parameters:
change applies to all sections

2023-12-14 15:40 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +builder methods. Then, the code passes these models as a vector to the ``create_search_indexes()``
```suggestion
``static_index`` on the ``posts`` collection. The code creates ``SearchIndexModel``
instances for each index that specify the index names and definitions. Then, the code passes these models
as a vector to the ``create_search_indexes()``
```

2023-12-14 18:39 UTC, rustagir approved these changes
lgtm, just left a few last thoughts/suggestions!

2023-12-14 18:39 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +- `DropSearchIndexOptions <{+api+}/options/struct.DropSearchIndexOptions.html>`__
S: Leaving this up to you, but since this list is quite long, could be easier to traverse links if you inlined them, as we do on the [DB/collection guide](https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-34184-atlas-search-index/fundamentals/database-collection/) (for the same reason)

2023-12-14 18:39 UTC, rustagir commented on source/includes/fundamentals/code-snippets/indexes.rs
> +        .definition(doc! { "mappings": doc! {"dynamic": true} })
S:(nit) noticed that formatting isnt totally consistent throughout the file, could fix by running the formatter
```suggestion
        .definition(doc! { "mappings": doc! { "dynamic": true } })
```

2023-12-14 18:39 UTC, rustagir commented on source/fundamentals/indexes/atlas-search-indexes.txt
> +</atlas-search/>`.
S: I think we should link this in the overview of this page, as users might get to this page and want to read about the feature before reading the driver documentation. This section could link back out to the indexes page, and here are a few more pages we could link here:
- https://www.mongodb.com/docs/atlas/atlas-search/best-practices
- https://www.mongodb.com/docs/atlas/atlas-search/performance/
- https://www.mongodb.com/docs/atlas/atlas-search/limitations/
- https://www.mongodb.com/docs/atlas/atlas-search/faq/

2023-12-15 16:54 UTC, merged